export declare const linearSet: {
  "cil3dRotate": any[];
  "cil3d": any[];
  "cil4k": any[];
  "cilAccessibility": any[];
  "cilAccessible": any[];
  "cilAccountLogout": any[];
  "cilActionRedo": any[];
  "cilActionUndo": any[];
  "cilAddressBook": any[];
  "cilAddressCard": any[];
  "cilAirplaneModeOff": any[];
  "cilAirplaneMode": any[];
  "cilAirplay": any[];
  "cilAlarmAdd": any[];
  "cilAlarmOff": any[];
  "cilAlarmOn": any[];
  "cilAlarmSnooze": any[];
  "cilAlarm": any[];
  "cilAlbum": any[];
  "cilAlignCenter": any[];
  "cilAlignLeft": any[];
  "cilAlignRight": any[];
  "cilAmericanFootball": any[];
  "cilAnimal": any[];
  "cilAperture": any[];
  "cilApple": any[];
  "cilApplicationsSettings": any[];
  "cilApplications": any[];
  "cilAppsSettings": any[];
  "cilApps": any[];
  "cilArchive": any[];
  "cilArrowBottom": any[];
  "cilArrowCircleBottom": any[];
  "cilArrowCircleLeft": any[];
  "cilArrowCircleRight": any[];
  "cilArrowCircleTop": any[];
  "cilArrowLeft": any[];
  "cilArrowRight": any[];
  "cilArrowThickBottom": any[];
  "cilArrowThickCircleDown": any[];
  "cilArrowThickCircleLeft": any[];
  "cilArrowThickCircleRight": any[];
  "cilArrowThickCircleUp": any[];
  "cilArrowThickFromBottom": any[];
  "cilArrowThickFromLeft": any[];
  "cilArrowThickFromRight": any[];
  "cilArrowThickFromTop": any[];
  "cilArrowThickLeft": any[];
  "cilArrowThickRight": any[];
  "cilArrowThickSquareDown": any[];
  "cilArrowThickSquareLeft": any[];
  "cilArrowThickSquareRight": any[];
  "cilArrowThickSquareUp": any[];
  "cilArrowThickToBottom": any[];
  "cilArrowThickToLeft": any[];
  "cilArrowThickToRight": any[];
  "cilArrowThickToTop": any[];
  "cilArrowThickTop": any[];
  "cilArrowTop": any[];
  "cilArtTrack": any[];
  "cilAspectRatio": any[];
  "cilAssistiveListeningSystem": any[];
  "cilAsteriskCircle": any[];
  "cilAsterisk": any[];
  "cilAt": any[];
  "cilAudioDescription": any[];
  "cilAudioSpectrum": any[];
  "cilAudio": any[];
  "cilAvTimer": any[];
  "cilBabyCarriage": any[];
  "cilBaby": any[];
  "cilBackspace": any[];
  "cilBadge": any[];
  "cilBalanceScaleLeft": any[];
  "cilBalanceScaleRight": any[];
  "cilBalanceScale": any[];
  "cilBan": any[];
  "cilBank": any[];
  "cilBarChart": any[];
  "cilBarcode": any[];
  "cilBaseball": any[];
  "cilBasketArrowDown": any[];
  "cilBasketLoaded": any[];
  "cilBasketPlus": any[];
  "cilBasket": any[];
  "cilBasketball": any[];
  "cilBath": any[];
  "cilBathroom": any[];
  "cilBattery0": any[];
  "cilBattery1": any[];
  "cilBattery2": any[];
  "cilBattery3": any[];
  "cilBattery4": any[];
  "cilBattery5": any[];
  "cilBatteryAlert": any[];
  "cilBatteryAlt0": any[];
  "cilBatteryAlt1": any[];
  "cilBatteryAlt2": any[];
  "cilBatteryAlt3": any[];
  "cilBatteryAltEmpty": any[];
  "cilBatteryAltFull": any[];
  "cilBatteryAltSlash": any[];
  "cilBatteryCharge": any[];
  "cilBatteryEmpty": any[];
  "cilBatteryFull": any[];
  "cilBatterySlash": any[];
  "cilBatteryUnknown": any[];
  "cilBeachAccess": any[];
  "cilBeaker": any[];
  "cilBed": any[];
  "cilBellExclamation": any[];
  "cilBellPlus": any[];
  "cilBellRing": any[];
  "cilBellSlash": any[];
  "cilBell": any[];
  "cilBikeAlt": any[];
  "cilBike": any[];
  "cilBirthdayCake": any[];
  "cilBlind": any[];
  "cilBluetoothConnected": any[];
  "cilBluetoothSearching": any[];
  "cilBluetoothSettings": any[];
  "cilBluetoothSlash": any[];
  "cilBluetooth": any[];
  "cilBlurCircular": any[];
  "cilBlurLinear": any[];
  "cilBlurSlash": any[];
  "cilBlur": any[];
  "cilBoatAlt": any[];
  "cilBoat": any[];
  "cilBold": any[];
  "cilBoltAlt": any[];
  "cilBoltCircle": any[];
  "cilBolt": any[];
  "cilBookOpen": any[];
  "cilBook": any[];
  "cilBookmark": any[];
  "cilBookmarks": any[];
  "cilBorderAll": any[];
  "cilBorderBottom": any[];
  "cilBorderClear": any[];
  "cilBorderHorizontal": any[];
  "cilBorderInner": any[];
  "cilBorderLeft": any[];
  "cilBorderOuter": any[];
  "cilBorderRight": any[];
  "cilBorderStyle": any[];
  "cilBorderTop": any[];
  "cilBorderVertical": any[];
  "cilBowlingPins": any[];
  "cilBowling": any[];
  "cilBoxAlt": any[];
  "cilBox": any[];
  "cilBraille": any[];
  "cilBrandingWatermark": any[];
  "cilBriefcaseArrowLeft": any[];
  "cilBriefcaseArrowRight": any[];
  "cilBriefcaseSlash": any[];
  "cilBriefcase": any[];
  "cilBrightnessAuto": any[];
  "cilBrightnessHigh": any[];
  "cilBrightnessLow": any[];
  "cilBrightnessMedium": any[];
  "cilBrightness": any[];
  "cilBritishPoundCircle": any[];
  "cilBritishPoundSlash": any[];
  "cilBritishPound": any[];
  "cilBroadcastTower": any[];
  "cilBrowser": any[];
  "cilBrushAlt": any[];
  "cilBrush": any[];
  "cilBug": any[];
  "cilBuildingBusinessSlash": any[];
  "cilBuildingBusiness": any[];
  "cilBuildingSlash": any[];
  "cilBuilding": any[];
  "cilBullhorn": any[];
  "cilBurger": any[];
  "cilBurn": any[];
  "cilBusAlt": any[];
  "cilBusTimer": any[];
  "cilBus": any[];
  "cilCalculator": any[];
  "cilCalendarAlt": any[];
  "cilCalendarCheck": any[];
  "cilCalendarEvent": any[];
  "cilCalendarMinus": any[];
  "cilCalendarNote": any[];
  "cilCalendarPlus": any[];
  "cilCalendarTimes": any[];
  "cilCalendarToday": any[];
  "cilCalendarViewDay": any[];
  "cilCalendar": any[];
  "cilCallMade": any[];
  "cilCallMerge": any[];
  "cilCallMissedOutgoing": any[];
  "cilCallMissed": any[];
  "cilCallReceived": any[];
  "cilCallSplit": any[];
  "cilCallSwapCalls": any[];
  "cilCallToAction": any[];
  "cilCameraControl": any[];
  "cilCameraEnhance": any[];
  "cilCameraPlus": any[];
  "cilCameraRoll": any[];
  "cilCameraSwitch": any[];
  "cilCamera": any[];
  "cilCarAlt": any[];
  "cilCar": any[];
  "cilCardGiftcard": any[];
  "cilCardMembership": any[];
  "cilCardTravel": any[];
  "cilCaretBottom": any[];
  "cilCaretLeft": any[];
  "cilCaretRight": any[];
  "cilCaretTop": any[];
  "cilCartArrowDown": any[];
  "cilCartLoaded": any[];
  "cilCartPlus": any[];
  "cilCartSlash": any[];
  "cilCart": any[];
  "cilCash": any[];
  "cilCasino": any[];
  "cilCastConnected": any[];
  "cilCastForEducation": any[];
  "cilCast": any[];
  "cilCat": any[];
  "cilCc": any[];
  "cilCenterFocusWeak": any[];
  "cilCenterFocus": any[];
  "cilChalkboardTeacher": any[];
  "cilChartArea": any[];
  "cilChartBubble": any[];
  "cilChartDonut": any[];
  "cilChartLine": any[];
  "cilChartMultiline": any[];
  "cilChartPie": any[];
  "cilChartShow": any[];
  "cilChartTable": any[];
  "cilChart": any[];
  "cilChatBubble": any[];
  "cilChatSquare": any[];
  "cilCheckAlt": any[];
  "cilCheckCircle": any[];
  "cilCheckDoubleAlt": any[];
  "cilCheckDouble": any[];
  "cilCheck": any[];
  "cilChevronBottomAlt": any[];
  "cilChevronBottom": any[];
  "cilChevronCircleDownAlt": any[];
  "cilChevronCircleDown": any[];
  "cilChevronCircleLeftAlt": any[];
  "cilChevronCircleLeft": any[];
  "cilChevronCircleRightAlt": any[];
  "cilChevronCircleRight": any[];
  "cilChevronCircleUpAlt": any[];
  "cilChevronCircleUp": any[];
  "cilChevronDoubleDownAlt": any[];
  "cilChevronDoubleDown": any[];
  "cilChevronDoubleLeftAlt": any[];
  "cilChevronDoubleLeft": any[];
  "cilChevronDoubleRightAlt": any[];
  "cilChevronDoubleRight": any[];
  "cilChevronDoubleUpAlt": any[];
  "cilChevronDoubleUp": any[];
  "cilChevronLeftAlt": any[];
  "cilChevronLeft": any[];
  "cilChevronRightAlt": any[];
  "cilChevronRight": any[];
  "cilChevronSquareDownAlt": any[];
  "cilChevronSquareDown": any[];
  "cilChevronSquareLeftAlt": any[];
  "cilChevronSquareLeft": any[];
  "cilChevronSquareRightAlt": any[];
  "cilChevronSquareRight": any[];
  "cilChevronSquareUpAlt": any[];
  "cilChevronSquareUp": any[];
  "cilChevronTopAlt": any[];
  "cilChevronTop": any[];
  "cilChildFriendly": any[];
  "cilChild": any[];
  "cilCircle": any[];
  "cilCity": any[];
  "cilClearAll": any[];
  "cilClipboard": any[];
  "cilClock": any[];
  "cilClone": any[];
  "cilClosedCaptioning": any[];
  "cilCloudCheck": any[];
  "cilCloudCircle": any[];
  "cilCloudData": any[];
  "cilCloudDownload": any[];
  "cilCloudSlash": any[];
  "cilCloudUpload": any[];
  "cilCloud": any[];
  "cilCloudy": any[];
  "cilCode": any[];
  "cilCoffee": any[];
  "cilCog": any[];
  "cilColorBorder": any[];
  "cilColorFill": any[];
  "cilColorPalette": any[];
  "cilColumns": any[];
  "cilCommand": any[];
  "cilCommentBubbleCheck": any[];
  "cilCommentBubbleEdit": any[];
  "cilCommentBubbleExclamation": any[];
  "cilCommentBubbleLines": any[];
  "cilCommentBubbleMinus": any[];
  "cilCommentBubblePlus": any[];
  "cilCommentBubbleQuestion": any[];
  "cilCommentBubbleSmile": any[];
  "cilCommentBubbleX": any[];
  "cilCommentBubble": any[];
  "cilCommentSquareCheck": any[];
  "cilCommentSquareEdit": any[];
  "cilCommentSquareExclamation": any[];
  "cilCommentSquareImage": any[];
  "cilCommentSquareLines": any[];
  "cilCommentSquareMinus": any[];
  "cilCommentSquarePlus": any[];
  "cilCommentSquareRateReview": any[];
  "cilCommentSquareSmile": any[];
  "cilCommentSquareX": any[];
  "cilCommentSquare": any[];
  "cilCommute": any[];
  "cilCompare": any[];
  "cilCompassCalibration": any[];
  "cilCompassSlash": any[];
  "cilCompass": any[];
  "cilCompressWide": any[];
  "cilCompress": any[];
  "cilContactMail": any[];
  "cilContactPhone": any[];
  "cilContact": any[];
  "cilContacts": any[];
  "cilContrast": any[];
  "cilControl": any[];
  "cilCopy": any[];
  "cilCopyright": any[];
  "cilCouch": any[];
  "cilCreditCard": any[];
  "cilCropRotate": any[];
  "cilCrop": any[];
  "cilCursorMove": any[];
  "cilCursor": any[];
  "cilCut": any[];
  "cilDataTransferDown": any[];
  "cilDataTransferUp": any[];
  "cilDeaf": any[];
  "cilDelete": any[];
  "cilDescription": any[];
  "cilDeveloperBoard": any[];
  "cilDeviceUnknown": any[];
  "cilDevicesImportant": any[];
  "cilDevicesOther": any[];
  "cilDevicesSlash": any[];
  "cilDevices": any[];
  "cilDial": any[];
  "cilDialpad": any[];
  "cilDiamond": any[];
  "cilDinner": any[];
  "cilDirections": any[];
  "cilDisabled": any[];
  "cilDns": any[];
  "cilDock": any[];
  "cilDocument": any[];
  "cilDog": any[];
  "cilDollarCircleSlash": any[];
  "cilDollarCircle": any[];
  "cilDollarSlash": any[];
  "cilDollar": any[];
  "cilDonate": any[];
  "cilDoor": any[];
  "cilDoubleQuoteSansLeft": any[];
  "cilDoubleQuoteSansRight": any[];
  "cilDoubleQuoteSerifLeft": any[];
  "cilDoubleQuoteSerifRight": any[];
  "cilDrinkAlcohol": any[];
  "cilDrink": any[];
  "cilDropSlash": any[];
  "cilDrop": any[];
  "cilDvr": any[];
  "cilEar": any[];
  "cilEco": any[];
  "cilEducation": any[];
  "cilElevator": any[];
  "cilEllipsis": any[];
  "cilEnergyCircle": any[];
  "cilEnergy": any[];
  "cilEnvelopeClosed": any[];
  "cilEnvelopeLetter": any[];
  "cilEnvelopeMinus": any[];
  "cilEnvelopeOpen": any[];
  "cilEnvelopePlus": any[];
  "cilEqualizer": any[];
  "cilEthernetAlt": any[];
  "cilEthernet": any[];
  "cilEuroCircleSlash": any[];
  "cilEuroCircle": any[];
  "cilEuroSlash": any[];
  "cilEuro": any[];
  "cilEvStation": any[];
  "cilExcerpt": any[];
  "cilExclamationCircle": any[];
  "cilExclamation": any[];
  "cilExitToApp": any[];
  "cilExpandDown": any[];
  "cilExpandLeft": any[];
  "cilExpandRight": any[];
  "cilExpandUp": any[];
  "cilExposure": any[];
  "cilExternalLink": any[];
  "cilEyeSlash": any[];
  "cilEye": any[];
  "cilEyedropper": any[];
  "cilFaceDead": any[];
  "cilFace": any[];
  "cilFactorySlash": any[];
  "cilFactory": any[];
  "cilFastfood": any[];
  "cilFax": any[];
  "cilFeaturedPlaylist": any[];
  "cilFeaturedVideo": any[];
  "cilFiberDvr": any[];
  "cilFiberManual": any[];
  "cilFiberNew": any[];
  "cilFiberPin": any[];
  "cilFiberSmart": any[];
  "cilFileAcrobat": any[];
  "cilFileAdd": any[];
  "cilFileArchive": any[];
  "cilFileAudio": any[];
  "cilFileCode": any[];
  "cilFileDoc": any[];
  "cilFileExcel": any[];
  "cilFileImage": any[];
  "cilFilePdf": any[];
  "cilFilePowerpoint": any[];
  "cilFilePpt": any[];
  "cilFileVideo": any[];
  "cilFileWord": any[];
  "cilFileXls": any[];
  "cilFile": any[];
  "cilFilterFrames": any[];
  "cilFilterPhoto": any[];
  "cilFilterSquare": any[];
  "cilFilterX": any[];
  "cilFilter": any[];
  "cilFindInPage": any[];
  "cilFindReplace": any[];
  "cilFingerprint": any[];
  "cilFire": any[];
  "cilFlagAlt": any[];
  "cilFlagRectangle": any[];
  "cilFlagTriangle": any[];
  "cilFlag": any[];
  "cilFlame": any[];
  "cilFlash": any[];
  "cilFlightLand": any[];
  "cilFlightTakeoff": any[];
  "cilFlipToBack": any[];
  "cilFlipToFront": any[];
  "cilFlip": any[];
  "cilFlower": any[];
  "cilFolderAlt": any[];
  "cilFolderArrowLeft": any[];
  "cilFolderArrowRight": any[];
  "cilFolderBack": any[];
  "cilFolderMove": any[];
  "cilFolderOpen": any[];
  "cilFolderPlus": any[];
  "cilFolderShared": any[];
  "cilFolderSpecial": any[];
  "cilFolder": any[];
  "cilFont": any[];
  "cilFootball": any[];
  "cilFork": any[];
  "cilFridge": any[];
  "cilFrown": any[];
  "cilFullscreenExit": any[];
  "cilFullscreen": any[];
  "cilFunctionsAlt": any[];
  "cilFunctions": any[];
  "cilGamepad": any[];
  "cilGarage": any[];
  "cilGauge": any[];
  "cilGem": any[];
  "cilGif": any[];
  "cilGift": any[];
  "cilGlass": any[];
  "cilGlobeAltLock": any[];
  "cilGlobeAlt": any[];
  "cilGlobeLock": any[];
  "cilGlobe": any[];
  "cilGolfAlt": any[];
  "cilGolf": any[];
  "cilGradient": any[];
  "cilGrain": any[];
  "cilGraph": any[];
  "cilGridSlash": any[];
  "cilGrid": any[];
  "cilGripDotsHorizontal": any[];
  "cilGripDotsVertical": any[];
  "cilGripDots": any[];
  "cilGripHorizontal": any[];
  "cilGripLinesHorizontal": any[];
  "cilGripLinesVertical": any[];
  "cilGripLines": any[];
  "cilGripVertical": any[];
  "cilGrip": any[];
  "cilGroupMinus": any[];
  "cilGroupPlus": any[];
  "cilGroupX": any[];
  "cilGroup": any[];
  "cilHamburgerMenu": any[];
  "cilHandLizard": any[];
  "cilHandPaper": any[];
  "cilHandPeace": any[];
  "cilHandPointDown": any[];
  "cilHandPointLeft": any[];
  "cilHandPointRight": any[];
  "cilHandPointUp": any[];
  "cilHandPointer": any[];
  "cilHandRock": any[];
  "cilHandScissors": any[];
  "cilHandSpock": any[];
  "cilHandshake": any[];
  "cilHappy": any[];
  "cilHardDrive": any[];
  "cilHd": any[];
  "cilHdrSlash": any[];
  "cilHdr": any[];
  "cilHeader": any[];
  "cilHeadphonesMic": any[];
  "cilHeadphonesMute": any[];
  "cilHeadphones": any[];
  "cilHealing": any[];
  "cilHeart": any[];
  "cilHighQuality": any[];
  "cilHighlighter": any[];
  "cilHighligt": any[];
  "cilHistory": any[];
  "cilHome": any[];
  "cilHospital": any[];
  "cilHotTub": any[];
  "cilHotel": any[];
  "cilHourglass": any[];
  "cilHouse": any[];
  "cilHq": any[];
  "cilHttp": any[];
  "cilHttps": any[];
  "cilIdBadge": any[];
  "cilIdCard": any[];
  "cilImageBroken": any[];
  "cilImagePlus": any[];
  "cilImage": any[];
  "cilImages": any[];
  "cilInboxIn": any[];
  "cilInboxOut": any[];
  "cilInbox": any[];
  "cilIndentDecrease": any[];
  "cilIndentIncrease": any[];
  "cilIndustrySlash": any[];
  "cilIndustry": any[];
  "cilInfinity": any[];
  "cilInfoCircle": any[];
  "cilInfo": any[];
  "cilInputAntenna": any[];
  "cilInputComponent": any[];
  "cilInputHdmi": any[];
  "cilInputPowerOff": any[];
  "cilInputPower": any[];
  "cilInputSvideo": any[];
  "cilInput": any[];
  "cilInstitution": any[];
  "cilInvert": any[];
  "cilItalic": any[];
  "cilJustifyCenter": any[];
  "cilJustifyLeft": any[];
  "cilJustifyRight": any[];
  "cilKeyAlt": any[];
  "cilKey": any[];
  "cilKeyboardHide": any[];
  "cilKeyboard": any[];
  "cilKitchen": any[];
  "cilLan": any[];
  "cilLanguage": any[];
  "cilLaptop": any[];
  "cilLaundry": any[];
  "cilLayersSlash": any[];
  "cilLayers": any[];
  "cilLeaf": any[];
  "cilLemon": any[];
  "cilLevelDown": any[];
  "cilLevelUp": any[];
  "cilLibraryAdd": any[];
  "cilLibraryBookmark": any[];
  "cilLibraryBooks": any[];
  "cilLibraryBuilding": any[];
  "cilLibraryMusic": any[];
  "cilLibrary": any[];
  "cilLifeRing": any[];
  "cilLightbulb": any[];
  "cilLineSpacing": any[];
  "cilLineStyle": any[];
  "cilLineWeight": any[];
  "cilLinkAlt": any[];
  "cilLinkBroken": any[];
  "cilLinkIntact": any[];
  "cilLinkSlash": any[];
  "cilLink": any[];
  "cilListFilter": any[];
  "cilListHighPriority": any[];
  "cilListLowPriority": any[];
  "cilListNumberedRtl": any[];
  "cilListNumbered": any[];
  "cilListRich": any[];
  "cilList": any[];
  "cilLocationGpsFixed": any[];
  "cilLocationGpsOff": any[];
  "cilLocationGps": any[];
  "cilLocationPinCheck": any[];
  "cilLocationPinEdit": any[];
  "cilLocationPinPlus": any[];
  "cilLocationPinSlash": any[];
  "cilLocationPin": any[];
  "cilLockLocked": any[];
  "cilLockMinus": any[];
  "cilLockPlus": any[];
  "cilLockUnlocked": any[];
  "cilLocomotive": any[];
  "cilLoop1": any[];
  "cilLoopCircular": any[];
  "cilLoopSquare": any[];
  "cilLoop": any[];
  "cilLowVision": any[];
  "cilLoyalty": any[];
  "cilMagnifyingGlass": any[];
  "cilMail": any[];
  "cilMailbox": any[];
  "cilMapAlt": any[];
  "cilMap": any[];
  "cilMediaEjectCircle": any[];
  "cilMediaEjectSquare": any[];
  "cilMediaEject": any[];
  "cilMediaPauseCircle": any[];
  "cilMediaPauseSquare": any[];
  "cilMediaPause": any[];
  "cilMediaPlayCircle": any[];
  "cilMediaPlaySquare": any[];
  "cilMediaPlay": any[];
  "cilMediaRecordCircle": any[];
  "cilMediaRecordSquare": any[];
  "cilMediaRecord": any[];
  "cilMediaSkipBackwardCircle": any[];
  "cilMediaSkipBackwardSquare": any[];
  "cilMediaSkipBackward": any[];
  "cilMediaSkipForwardCircle": any[];
  "cilMediaSkipForwardSquare": any[];
  "cilMediaSkipForward": any[];
  "cilMediaStepBackwardCircle": any[];
  "cilMediaStepBackwardSquare": any[];
  "cilMediaStepBackward": any[];
  "cilMediaStepForwardCircle": any[];
  "cilMediaStepForwardSquare": any[];
  "cilMediaStepForward": any[];
  "cilMediaStopCircle": any[];
  "cilMediaStopSquare": any[];
  "cilMediaStop": any[];
  "cilMedicalCross": any[];
  "cilMeh": any[];
  "cilMemory": any[];
  "cilMenu": any[];
  "cilMicAlt": any[];
  "cilMicSettings": any[];
  "cilMicSlash": any[];
  "cilMic": any[];
  "cilMicrochip": any[];
  "cilMicrophoneAlt": any[];
  "cilMicrophoneSettings": any[];
  "cilMicrophoneSlash": any[];
  "cilMicrophone": any[];
  "cilMinusCircle": any[];
  "cilMinusSquare": any[];
  "cilMinus": any[];
  "cilMobileArrowAdd": any[];
  "cilMobileArrowRemove": any[];
  "cilMobileCheck": any[];
  "cilMobileDeveloperMode": any[];
  "cilMobileLandscape": any[];
  "cilMobileLock": any[];
  "cilMobileMinus": any[];
  "cilMobilePlus": any[];
  "cilMobilePortrait": any[];
  "cilMobileSettings": any[];
  "cilMobileSlash": any[];
  "cilMobileSms": any[];
  "cilMobileSpeaker": any[];
  "cilMobileVolume": any[];
  "cilMobileX": any[];
  "cilMobile": any[];
  "cilMoneyBillAlt": any[];
  "cilMoneyBillAlt2": any[];
  "cilMoneyBill": any[];
  "cilMoney": any[];
  "cilMonitor": any[];
  "cilMoodBad": any[];
  "cilMoodGood": any[];
  "cilMoodVeryBad": any[];
  "cilMoodVeryGood": any[];
  "cilMoon": any[];
  "cilMore": any[];
  "cilMotorbike": any[];
  "cilMouseAlt": any[];
  "cilMouse": any[];
  "cilMouthSlash": any[];
  "cilMouth": any[];
  "cilMoveHorizontal": any[];
  "cilMoveVertical": any[];
  "cilMove": any[];
  "cilMovieAlt": any[];
  "cilMovie": any[];
  "cilMugTea": any[];
  "cilMug": any[];
  "cilMusicNoteAlt": any[];
  "cilMusicNoteSlash": any[];
  "cilMusicNote": any[];
  "cilMusicVideo": any[];
  "cilNetworkCheck": any[];
  "cilNewReleases": any[];
  "cilNew": any[];
  "cilNewspaper": any[];
  "cilNoteAdd": any[];
  "cilNote": any[];
  "cilNotes": any[];
  "cilObjectGroup": any[];
  "cilObjectUngroup": any[];
  "cilOpacity": any[];
  "cilOpentype": any[];
  "cilOptionsAlt": any[];
  "cilOptions": any[];
  "cilOven": any[];
  "cilOverscanSettings": any[];
  "cilOverscan": any[];
  "cilPageRestore": any[];
  "cilPage": any[];
  "cilPageview": any[];
  "cilPaintBucket": any[];
  "cilPaint": any[];
  "cilPaperPlane": any[];
  "cilPaperclip": any[];
  "cilParagraph": any[];
  "cilParking": any[];
  "cilPaw": any[];
  "cilPenAlt": any[];
  "cilPenFancy": any[];
  "cilPenNib": any[];
  "cilPen": any[];
  "cilPencil": any[];
  "cilPeopleMinus": any[];
  "cilPeoplePlus": any[];
  "cilPeopleX": any[];
  "cilPeople": any[];
  "cilPercent": any[];
  "cilPersonFemale": any[];
  "cilPerson": any[];
  "cilPetrolStation": any[];
  "cilPhoneBluetooth": any[];
  "cilPhoneCallEnd": any[];
  "cilPhoneCall": any[];
  "cilPhoneCallback": any[];
  "cilPhoneCheck": any[];
  "cilPhoneForward": any[];
  "cilPhoneInTalk": any[];
  "cilPhoneLock": any[];
  "cilPhoneMinus": any[];
  "cilPhoneMissed": any[];
  "cilPhonePaused": any[];
  "cilPhonePlus": any[];
  "cilPhoneRingVolume": any[];
  "cilPhoneSettings": any[];
  "cilPhoneSlash": any[];
  "cilPhoneSquare": any[];
  "cilPhoneVolume": any[];
  "cilPhoneX": any[];
  "cilPhone": any[];
  "cilPictureInPictureAlt": any[];
  "cilPictureInPicture": any[];
  "cilPin": any[];
  "cilPizza": any[];
  "cilPlant": any[];
  "cilPlaylistAddCheck": any[];
  "cilPlaylistAdd": any[];
  "cilPlaylistPlay": any[];
  "cilPlusCircle": any[];
  "cilPlusOne": any[];
  "cilPlusSquare": any[];
  "cilPlus": any[];
  "cilPool": any[];
  "cilPortableWifiOff": any[];
  "cilPortableWifi": any[];
  "cilPowerSettings": any[];
  "cilPowerStandby": any[];
  "cilPregnant": any[];
  "cilPrint": any[];
  "cilPrinterSlash": any[];
  "cilPrinter": any[];
  "cilPushchair": any[];
  "cilPuzzlePiece": any[];
  "cilPuzzle": any[];
  "cilQrCode": any[];
  "cilQueueAdd": any[];
  "cilQueueMusic": any[];
  "cilQueuePlayNext": any[];
  "cilQueueRemove": any[];
  "cilQueue": any[];
  "cilRadio": any[];
  "cilRailway": any[];
  "cilRain": any[];
  "cilRandom": any[];
  "cilRecentActors": any[];
  "cilRectangle": any[];
  "cilRecycle": any[];
  "cilRegistered": any[];
  "cilReload": any[];
  "cilRemoteControl": any[];
  "cilRemoteSettings": any[];
  "cilReplay": any[];
  "cilReportSlash": any[];
  "cilReport": any[];
  "cilResizeBoth": any[];
  "cilResizeHeight": any[];
  "cilResizeWidth": any[];
  "cilRestaurantMenu": any[];
  "cilRestaurant": any[];
  "cilRestore": any[];
  "cilRights": any[];
  "cilRoomSlash": any[];
  "cilRoom": any[];
  "cilRotateLeft": any[];
  "cilRotateRight": any[];
  "cilRoundedCorner": any[];
  "cilRouter": any[];
  "cilRowing": any[];
  "cilRssAlt": any[];
  "cilRssSquare": any[];
  "cilRss": any[];
  "cilRubleCircleSlash": any[];
  "cilRubleCircle": any[];
  "cilRubleSlash": any[];
  "cilRuble": any[];
  "cilRunning": any[];
  "cilSad": any[];
  "cilSatelite": any[];
  "cilSave": any[];
  "cilScaleImage": any[];
  "cilScale": any[];
  "cilScanner": any[];
  "cilSchool": any[];
  "cilScooter": any[];
  "cilScreenDeskopSlash": any[];
  "cilScreenDesktop": any[];
  "cilScreenHorizontal": any[];
  "cilScreenLandscape": any[];
  "cilScreenLockHorizontal": any[];
  "cilScreenLockLandscape": any[];
  "cilScreenLockPortrait": any[];
  "cilScreenLockRotation": any[];
  "cilScreenLockVertical": any[];
  "cilScreenMirroring": any[];
  "cilScreenPortrait": any[];
  "cilScreenRotation": any[];
  "cilScreenSmartphone": any[];
  "cilScreenVertical": any[];
  "cilScript": any[];
  "cilScrubber": any[];
  "cilSdcard": any[];
  "cilSearch": any[];
  "cilSecurity": any[];
  "cilSelectAll": any[];
  "cilSelect": any[];
  "cilSend": any[];
  "cilSettingsAlt": any[];
  "cilSettings": any[];
  "cilShareAll": any[];
  "cilShareAlt": any[];
  "cilShareBoxed": any[];
  "cilShare": any[];
  "cilShieldAlt": any[];
  "cilShieldCheck": any[];
  "cilShieldMinus": any[];
  "cilShieldPlus": any[];
  "cilShieldSlash": any[];
  "cilShieldX": any[];
  "cilShield": any[];
  "cilShopMediaTwo": any[];
  "cilShopMedia": any[];
  "cilShortText": any[];
  "cilShower": any[];
  "cilSignLanguage": any[];
  "cilSignalCellular0": any[];
  "cilSignalCellular1": any[];
  "cilSignalCellular2": any[];
  "cilSignalCellular3": any[];
  "cilSignalCellular4": any[];
  "cilSignalCellularNoInternet0": any[];
  "cilSignalCellularNoInternet1": any[];
  "cilSignalCellularNoInternet2": any[];
  "cilSignalCellularNoInternet3": any[];
  "cilSignalCellularNoInternet4": any[];
  "cilSignalCellularOff": any[];
  "cilSignalOff": any[];
  "cilSignal": any[];
  "cilSignpost": any[];
  "cilSimSlash": any[];
  "cilSim": any[];
  "cilSitemap": any[];
  "cilSlowMotion": any[];
  "cilSmilePlus": any[];
  "cilSmile": any[];
  "cilSmokeFree": any[];
  "cilSmokeSlash": any[];
  "cilSmoke": any[];
  "cilSmokingRoom": any[];
  "cilSnow": any[];
  "cilSnowflake": any[];
  "cilSoccer": any[];
  "cilSofa": any[];
  "cilSorroundSound": any[];
  "cilSortAlphaDown": any[];
  "cilSortAlphaUp": any[];
  "cilSortAscending": any[];
  "cilSortDescending": any[];
  "cilSortNumericDown": any[];
  "cilSortNumericUp": any[];
  "cilSound": any[];
  "cilSpa": any[];
  "cilSpaceBar": any[];
  "cilSpeak": any[];
  "cilSpeakerGroup": any[];
  "cilSpeaker": any[];
  "cilSpeechBubble": any[];
  "cilSpeechNotesSlash": any[];
  "cilSpeechNotes": any[];
  "cilSpeech": any[];
  "cilSpeedometer": any[];
  "cilSpreadsheet": any[];
  "cilSquare": any[];
  "cilStarCircle": any[];
  "cilStarHalf": any[];
  "cilStar": any[];
  "cilStickyNote": any[];
  "cilStorage": any[];
  "cilStore": any[];
  "cilStream": any[];
  "cilStrikethrough": any[];
  "cilSubtitles": any[];
  "cilSubway": any[];
  "cilSun": any[];
  "cilSwapHorizontalCircle": any[];
  "cilSwapHorizontal": any[];
  "cilSwapVerticalCircle": any[];
  "cilSwapVertical": any[];
  "cilSwimming": any[];
  "cilSyncDisabled": any[];
  "cilSyncProblem": any[];
  "cilSync": any[];
  "cilTablet": any[];
  "cilTag": any[];
  "cilTags": any[];
  "cilTarget": any[];
  "cilTask": any[];
  "cilTaxi": any[];
  "cilTemperatureAlt": any[];
  "cilTemperatureHigh": any[];
  "cilTemperatureLow": any[];
  "cilTemperature": any[];
  "cilTennisBall": any[];
  "cilTennis": any[];
  "cilTerminal": any[];
  "cilTerrain": any[];
  "cilTextDirectionLtr": any[];
  "cilTextDirectionRtl": any[];
  "cilTextFormatClear": any[];
  "cilTextHeight": any[];
  "cilTextRotateVertical": any[];
  "cilTextRotationDown": any[];
  "cilTextRotationNone": any[];
  "cilTextRotationUp": any[];
  "cilTextShapes": any[];
  "cilTextSize": any[];
  "cilTextSquare": any[];
  "cilTextStrike": any[];
  "cilTextWidth": any[];
  "cilText": any[];
  "cilThermometerAlt": any[];
  "cilThermometer": any[];
  "cilThumbDown": any[];
  "cilThumbUp": any[];
  "cilTimeline": any[];
  "cilTimer": any[];
  "cilToggleOff": any[];
  "cilToggleOn": any[];
  "cilToilet": any[];
  "cilToll": any[];
  "cilTouchApp": any[];
  "cilTrademark": any[];
  "cilTraffic": any[];
  "cilTrainAlt": any[];
  "cilTrain": any[];
  "cilTram": any[];
  "cilTransferWithinAStation": any[];
  "cilTransfer": any[];
  "cilTranslate": any[];
  "cilTrashAlt": any[];
  "cilTrashArrowUp": any[];
  "cilTrashSweep": any[];
  "cilTrashX": any[];
  "cilTrash": any[];
  "cilTriangle": any[];
  "cilTruck": any[];
  "cilTty": any[];
  "cilTvDvr": any[];
  "cilTvLive": any[];
  "cilTvSlash": any[];
  "cilTv": any[];
  "cilUnderline": any[];
  "cilUniversalAccess": any[];
  "cilUpdate": any[];
  "cilUsb": any[];
  "cilUserFemaleFollow": any[];
  "cilUserFemaleMinus": any[];
  "cilUserFemalePlus": any[];
  "cilUserFemaleUnfollow": any[];
  "cilUserFemaleX": any[];
  "cilUserFemale": any[];
  "cilUserFollow": any[];
  "cilUserMinus": any[];
  "cilUserPlus": any[];
  "cilUserSecret": any[];
  "cilUserUnfollow": any[];
  "cilUserX": any[];
  "cilUser": any[];
  "cilVector": any[];
  "cilVericalSplit": any[];
  "cilVerticalAlignBottom": any[];
  "cilVerticalAlignCenter": any[];
  "cilVerticalAlignTop": any[];
  "cilVideoLabel": any[];
  "cilVideoLibrary": any[];
  "cilVideoMissed": any[];
  "cilVideoPlus": any[];
  "cilVideoSlash": any[];
  "cilVideoSwitch": any[];
  "cilVideo": any[];
  "cilVideogame": any[];
  "cilViewAgenda": any[];
  "cilViewArray": any[];
  "cilViewCarousel": any[];
  "cilViewColumn": any[];
  "cilViewList": any[];
  "cilViewModule": any[];
  "cilViewQuilt": any[];
  "cilViewRow": any[];
  "cilViewStream": any[];
  "cilVoiceOverRecord": any[];
  "cilVoiceOverSlash": any[];
  "cilVoice": any[];
  "cilVoicemail": any[];
  "cilVolumeHigh": any[];
  "cilVolumeLow": any[];
  "cilVolumeOff": any[];
  "cilVolume": any[];
  "cilVote": any[];
  "cilWalk": any[];
  "cilWallet": any[];
  "cilWallpaper": any[];
  "cilWarning": any[];
  "cilWatch": any[];
  "cilWaves": any[];
  "cilWc": any[];
  "cilWebcloud": any[];
  "cilWeightlifitng": any[];
  "cilWeights": any[];
  "cilWheelchair": any[];
  "cilWidgets": any[];
  "cilWifiLock": any[];
  "cilWifiSignal0": any[];
  "cilWifiSignal1": any[];
  "cilWifiSignal2": any[];
  "cilWifiSignal3": any[];
  "cilWifiSignal4": any[];
  "cilWifiSignalLock0": any[];
  "cilWifiSignalLock1": any[];
  "cilWifiSignalLock2": any[];
  "cilWifiSignalLock3": any[];
  "cilWifiSignalLock4": any[];
  "cilWifiSignalOff": any[];
  "cilWifi": any[];
  "cilWindowMaximize": any[];
  "cilWindowMinimize": any[];
  "cilWindowRestore": any[];
  "cilWindow": any[];
  "cilWrapText": any[];
  "cilXCircle": any[];
  "cilXSquare": any[];
  "cilX": any[];
  "cilYenCircleSlash": any[];
  "cilYenCircle": any[];
  "cilYenSlash": any[];
  "cilYen": any[];
  "cilZoomIn": any[];
  "cilZoomOut": any[];
  "cilZoom": any[];
}
export declare const cil3dRotate: any[];
export declare const cil3d: any[];
export declare const cil4k: any[];
export declare const cilAccessibility: any[];
export declare const cilAccessible: any[];
export declare const cilAccountLogout: any[];
export declare const cilActionRedo: any[];
export declare const cilActionUndo: any[];
export declare const cilAddressBook: any[];
export declare const cilAddressCard: any[];
export declare const cilAirplaneModeOff: any[];
export declare const cilAirplaneMode: any[];
export declare const cilAirplay: any[];
export declare const cilAlarmAdd: any[];
export declare const cilAlarmOff: any[];
export declare const cilAlarmOn: any[];
export declare const cilAlarmSnooze: any[];
export declare const cilAlarm: any[];
export declare const cilAlbum: any[];
export declare const cilAlignCenter: any[];
export declare const cilAlignLeft: any[];
export declare const cilAlignRight: any[];
export declare const cilAmericanFootball: any[];
export declare const cilAnimal: any[];
export declare const cilAperture: any[];
export declare const cilApple: any[];
export declare const cilApplicationsSettings: any[];
export declare const cilApplications: any[];
export declare const cilAppsSettings: any[];
export declare const cilApps: any[];
export declare const cilArchive: any[];
export declare const cilArrowBottom: any[];
export declare const cilArrowCircleBottom: any[];
export declare const cilArrowCircleLeft: any[];
export declare const cilArrowCircleRight: any[];
export declare const cilArrowCircleTop: any[];
export declare const cilArrowLeft: any[];
export declare const cilArrowRight: any[];
export declare const cilArrowThickBottom: any[];
export declare const cilArrowThickCircleDown: any[];
export declare const cilArrowThickCircleLeft: any[];
export declare const cilArrowThickCircleRight: any[];
export declare const cilArrowThickCircleUp: any[];
export declare const cilArrowThickFromBottom: any[];
export declare const cilArrowThickFromLeft: any[];
export declare const cilArrowThickFromRight: any[];
export declare const cilArrowThickFromTop: any[];
export declare const cilArrowThickLeft: any[];
export declare const cilArrowThickRight: any[];
export declare const cilArrowThickSquareDown: any[];
export declare const cilArrowThickSquareLeft: any[];
export declare const cilArrowThickSquareRight: any[];
export declare const cilArrowThickSquareUp: any[];
export declare const cilArrowThickToBottom: any[];
export declare const cilArrowThickToLeft: any[];
export declare const cilArrowThickToRight: any[];
export declare const cilArrowThickToTop: any[];
export declare const cilArrowThickTop: any[];
export declare const cilArrowTop: any[];
export declare const cilArtTrack: any[];
export declare const cilAspectRatio: any[];
export declare const cilAssistiveListeningSystem: any[];
export declare const cilAsteriskCircle: any[];
export declare const cilAsterisk: any[];
export declare const cilAt: any[];
export declare const cilAudioDescription: any[];
export declare const cilAudioSpectrum: any[];
export declare const cilAudio: any[];
export declare const cilAvTimer: any[];
export declare const cilBabyCarriage: any[];
export declare const cilBaby: any[];
export declare const cilBackspace: any[];
export declare const cilBadge: any[];
export declare const cilBalanceScaleLeft: any[];
export declare const cilBalanceScaleRight: any[];
export declare const cilBalanceScale: any[];
export declare const cilBan: any[];
export declare const cilBank: any[];
export declare const cilBarChart: any[];
export declare const cilBarcode: any[];
export declare const cilBaseball: any[];
export declare const cilBasketArrowDown: any[];
export declare const cilBasketLoaded: any[];
export declare const cilBasketPlus: any[];
export declare const cilBasket: any[];
export declare const cilBasketball: any[];
export declare const cilBath: any[];
export declare const cilBathroom: any[];
export declare const cilBattery0: any[];
export declare const cilBattery1: any[];
export declare const cilBattery2: any[];
export declare const cilBattery3: any[];
export declare const cilBattery4: any[];
export declare const cilBattery5: any[];
export declare const cilBatteryAlert: any[];
export declare const cilBatteryAlt0: any[];
export declare const cilBatteryAlt1: any[];
export declare const cilBatteryAlt2: any[];
export declare const cilBatteryAlt3: any[];
export declare const cilBatteryAltEmpty: any[];
export declare const cilBatteryAltFull: any[];
export declare const cilBatteryAltSlash: any[];
export declare const cilBatteryCharge: any[];
export declare const cilBatteryEmpty: any[];
export declare const cilBatteryFull: any[];
export declare const cilBatterySlash: any[];
export declare const cilBatteryUnknown: any[];
export declare const cilBeachAccess: any[];
export declare const cilBeaker: any[];
export declare const cilBed: any[];
export declare const cilBellExclamation: any[];
export declare const cilBellPlus: any[];
export declare const cilBellRing: any[];
export declare const cilBellSlash: any[];
export declare const cilBell: any[];
export declare const cilBikeAlt: any[];
export declare const cilBike: any[];
export declare const cilBirthdayCake: any[];
export declare const cilBlind: any[];
export declare const cilBluetoothConnected: any[];
export declare const cilBluetoothSearching: any[];
export declare const cilBluetoothSettings: any[];
export declare const cilBluetoothSlash: any[];
export declare const cilBluetooth: any[];
export declare const cilBlurCircular: any[];
export declare const cilBlurLinear: any[];
export declare const cilBlurSlash: any[];
export declare const cilBlur: any[];
export declare const cilBoatAlt: any[];
export declare const cilBoat: any[];
export declare const cilBold: any[];
export declare const cilBoltAlt: any[];
export declare const cilBoltCircle: any[];
export declare const cilBolt: any[];
export declare const cilBookOpen: any[];
export declare const cilBook: any[];
export declare const cilBookmark: any[];
export declare const cilBookmarks: any[];
export declare const cilBorderAll: any[];
export declare const cilBorderBottom: any[];
export declare const cilBorderClear: any[];
export declare const cilBorderHorizontal: any[];
export declare const cilBorderInner: any[];
export declare const cilBorderLeft: any[];
export declare const cilBorderOuter: any[];
export declare const cilBorderRight: any[];
export declare const cilBorderStyle: any[];
export declare const cilBorderTop: any[];
export declare const cilBorderVertical: any[];
export declare const cilBowlingPins: any[];
export declare const cilBowling: any[];
export declare const cilBoxAlt: any[];
export declare const cilBox: any[];
export declare const cilBraille: any[];
export declare const cilBrandingWatermark: any[];
export declare const cilBriefcaseArrowLeft: any[];
export declare const cilBriefcaseArrowRight: any[];
export declare const cilBriefcaseSlash: any[];
export declare const cilBriefcase: any[];
export declare const cilBrightnessAuto: any[];
export declare const cilBrightnessHigh: any[];
export declare const cilBrightnessLow: any[];
export declare const cilBrightnessMedium: any[];
export declare const cilBrightness: any[];
export declare const cilBritishPoundCircle: any[];
export declare const cilBritishPoundSlash: any[];
export declare const cilBritishPound: any[];
export declare const cilBroadcastTower: any[];
export declare const cilBrowser: any[];
export declare const cilBrushAlt: any[];
export declare const cilBrush: any[];
export declare const cilBug: any[];
export declare const cilBuildingBusinessSlash: any[];
export declare const cilBuildingBusiness: any[];
export declare const cilBuildingSlash: any[];
export declare const cilBuilding: any[];
export declare const cilBullhorn: any[];
export declare const cilBurger: any[];
export declare const cilBurn: any[];
export declare const cilBusAlt: any[];
export declare const cilBusTimer: any[];
export declare const cilBus: any[];
export declare const cilCalculator: any[];
export declare const cilCalendarAlt: any[];
export declare const cilCalendarCheck: any[];
export declare const cilCalendarEvent: any[];
export declare const cilCalendarMinus: any[];
export declare const cilCalendarNote: any[];
export declare const cilCalendarPlus: any[];
export declare const cilCalendarTimes: any[];
export declare const cilCalendarToday: any[];
export declare const cilCalendarViewDay: any[];
export declare const cilCalendar: any[];
export declare const cilCallMade: any[];
export declare const cilCallMerge: any[];
export declare const cilCallMissedOutgoing: any[];
export declare const cilCallMissed: any[];
export declare const cilCallReceived: any[];
export declare const cilCallSplit: any[];
export declare const cilCallSwapCalls: any[];
export declare const cilCallToAction: any[];
export declare const cilCameraControl: any[];
export declare const cilCameraEnhance: any[];
export declare const cilCameraPlus: any[];
export declare const cilCameraRoll: any[];
export declare const cilCameraSwitch: any[];
export declare const cilCamera: any[];
export declare const cilCarAlt: any[];
export declare const cilCar: any[];
export declare const cilCardGiftcard: any[];
export declare const cilCardMembership: any[];
export declare const cilCardTravel: any[];
export declare const cilCaretBottom: any[];
export declare const cilCaretLeft: any[];
export declare const cilCaretRight: any[];
export declare const cilCaretTop: any[];
export declare const cilCartArrowDown: any[];
export declare const cilCartLoaded: any[];
export declare const cilCartPlus: any[];
export declare const cilCartSlash: any[];
export declare const cilCart: any[];
export declare const cilCash: any[];
export declare const cilCasino: any[];
export declare const cilCastConnected: any[];
export declare const cilCastForEducation: any[];
export declare const cilCast: any[];
export declare const cilCat: any[];
export declare const cilCc: any[];
export declare const cilCenterFocusWeak: any[];
export declare const cilCenterFocus: any[];
export declare const cilChalkboardTeacher: any[];
export declare const cilChartArea: any[];
export declare const cilChartBubble: any[];
export declare const cilChartDonut: any[];
export declare const cilChartLine: any[];
export declare const cilChartMultiline: any[];
export declare const cilChartPie: any[];
export declare const cilChartShow: any[];
export declare const cilChartTable: any[];
export declare const cilChart: any[];
export declare const cilChatBubble: any[];
export declare const cilChatSquare: any[];
export declare const cilCheckAlt: any[];
export declare const cilCheckCircle: any[];
export declare const cilCheckDoubleAlt: any[];
export declare const cilCheckDouble: any[];
export declare const cilCheck: any[];
export declare const cilChevronBottomAlt: any[];
export declare const cilChevronBottom: any[];
export declare const cilChevronCircleDownAlt: any[];
export declare const cilChevronCircleDown: any[];
export declare const cilChevronCircleLeftAlt: any[];
export declare const cilChevronCircleLeft: any[];
export declare const cilChevronCircleRightAlt: any[];
export declare const cilChevronCircleRight: any[];
export declare const cilChevronCircleUpAlt: any[];
export declare const cilChevronCircleUp: any[];
export declare const cilChevronDoubleDownAlt: any[];
export declare const cilChevronDoubleDown: any[];
export declare const cilChevronDoubleLeftAlt: any[];
export declare const cilChevronDoubleLeft: any[];
export declare const cilChevronDoubleRightAlt: any[];
export declare const cilChevronDoubleRight: any[];
export declare const cilChevronDoubleUpAlt: any[];
export declare const cilChevronDoubleUp: any[];
export declare const cilChevronLeftAlt: any[];
export declare const cilChevronLeft: any[];
export declare const cilChevronRightAlt: any[];
export declare const cilChevronRight: any[];
export declare const cilChevronSquareDownAlt: any[];
export declare const cilChevronSquareDown: any[];
export declare const cilChevronSquareLeftAlt: any[];
export declare const cilChevronSquareLeft: any[];
export declare const cilChevronSquareRightAlt: any[];
export declare const cilChevronSquareRight: any[];
export declare const cilChevronSquareUpAlt: any[];
export declare const cilChevronSquareUp: any[];
export declare const cilChevronTopAlt: any[];
export declare const cilChevronTop: any[];
export declare const cilChildFriendly: any[];
export declare const cilChild: any[];
export declare const cilCircle: any[];
export declare const cilCity: any[];
export declare const cilClearAll: any[];
export declare const cilClipboard: any[];
export declare const cilClock: any[];
export declare const cilClone: any[];
export declare const cilClosedCaptioning: any[];
export declare const cilCloudCheck: any[];
export declare const cilCloudCircle: any[];
export declare const cilCloudData: any[];
export declare const cilCloudDownload: any[];
export declare const cilCloudSlash: any[];
export declare const cilCloudUpload: any[];
export declare const cilCloud: any[];
export declare const cilCloudy: any[];
export declare const cilCode: any[];
export declare const cilCoffee: any[];
export declare const cilCog: any[];
export declare const cilColorBorder: any[];
export declare const cilColorFill: any[];
export declare const cilColorPalette: any[];
export declare const cilColumns: any[];
export declare const cilCommand: any[];
export declare const cilCommentBubbleCheck: any[];
export declare const cilCommentBubbleEdit: any[];
export declare const cilCommentBubbleExclamation: any[];
export declare const cilCommentBubbleLines: any[];
export declare const cilCommentBubbleMinus: any[];
export declare const cilCommentBubblePlus: any[];
export declare const cilCommentBubbleQuestion: any[];
export declare const cilCommentBubbleSmile: any[];
export declare const cilCommentBubbleX: any[];
export declare const cilCommentBubble: any[];
export declare const cilCommentSquareCheck: any[];
export declare const cilCommentSquareEdit: any[];
export declare const cilCommentSquareExclamation: any[];
export declare const cilCommentSquareImage: any[];
export declare const cilCommentSquareLines: any[];
export declare const cilCommentSquareMinus: any[];
export declare const cilCommentSquarePlus: any[];
export declare const cilCommentSquareRateReview: any[];
export declare const cilCommentSquareSmile: any[];
export declare const cilCommentSquareX: any[];
export declare const cilCommentSquare: any[];
export declare const cilCommute: any[];
export declare const cilCompare: any[];
export declare const cilCompassCalibration: any[];
export declare const cilCompassSlash: any[];
export declare const cilCompass: any[];
export declare const cilCompressWide: any[];
export declare const cilCompress: any[];
export declare const cilContactMail: any[];
export declare const cilContactPhone: any[];
export declare const cilContact: any[];
export declare const cilContacts: any[];
export declare const cilContrast: any[];
export declare const cilControl: any[];
export declare const cilCopy: any[];
export declare const cilCopyright: any[];
export declare const cilCouch: any[];
export declare const cilCreditCard: any[];
export declare const cilCropRotate: any[];
export declare const cilCrop: any[];
export declare const cilCursorMove: any[];
export declare const cilCursor: any[];
export declare const cilCut: any[];
export declare const cilDataTransferDown: any[];
export declare const cilDataTransferUp: any[];
export declare const cilDeaf: any[];
export declare const cilDelete: any[];
export declare const cilDescription: any[];
export declare const cilDeveloperBoard: any[];
export declare const cilDeviceUnknown: any[];
export declare const cilDevicesImportant: any[];
export declare const cilDevicesOther: any[];
export declare const cilDevicesSlash: any[];
export declare const cilDevices: any[];
export declare const cilDial: any[];
export declare const cilDialpad: any[];
export declare const cilDiamond: any[];
export declare const cilDinner: any[];
export declare const cilDirections: any[];
export declare const cilDisabled: any[];
export declare const cilDns: any[];
export declare const cilDock: any[];
export declare const cilDocument: any[];
export declare const cilDog: any[];
export declare const cilDollarCircleSlash: any[];
export declare const cilDollarCircle: any[];
export declare const cilDollarSlash: any[];
export declare const cilDollar: any[];
export declare const cilDonate: any[];
export declare const cilDoor: any[];
export declare const cilDoubleQuoteSansLeft: any[];
export declare const cilDoubleQuoteSansRight: any[];
export declare const cilDoubleQuoteSerifLeft: any[];
export declare const cilDoubleQuoteSerifRight: any[];
export declare const cilDrinkAlcohol: any[];
export declare const cilDrink: any[];
export declare const cilDropSlash: any[];
export declare const cilDrop: any[];
export declare const cilDvr: any[];
export declare const cilEar: any[];
export declare const cilEco: any[];
export declare const cilEducation: any[];
export declare const cilElevator: any[];
export declare const cilEllipsis: any[];
export declare const cilEnergyCircle: any[];
export declare const cilEnergy: any[];
export declare const cilEnvelopeClosed: any[];
export declare const cilEnvelopeLetter: any[];
export declare const cilEnvelopeMinus: any[];
export declare const cilEnvelopeOpen: any[];
export declare const cilEnvelopePlus: any[];
export declare const cilEqualizer: any[];
export declare const cilEthernetAlt: any[];
export declare const cilEthernet: any[];
export declare const cilEuroCircleSlash: any[];
export declare const cilEuroCircle: any[];
export declare const cilEuroSlash: any[];
export declare const cilEuro: any[];
export declare const cilEvStation: any[];
export declare const cilExcerpt: any[];
export declare const cilExclamationCircle: any[];
export declare const cilExclamation: any[];
export declare const cilExitToApp: any[];
export declare const cilExpandDown: any[];
export declare const cilExpandLeft: any[];
export declare const cilExpandRight: any[];
export declare const cilExpandUp: any[];
export declare const cilExposure: any[];
export declare const cilExternalLink: any[];
export declare const cilEyeSlash: any[];
export declare const cilEye: any[];
export declare const cilEyedropper: any[];
export declare const cilFaceDead: any[];
export declare const cilFace: any[];
export declare const cilFactorySlash: any[];
export declare const cilFactory: any[];
export declare const cilFastfood: any[];
export declare const cilFax: any[];
export declare const cilFeaturedPlaylist: any[];
export declare const cilFeaturedVideo: any[];
export declare const cilFiberDvr: any[];
export declare const cilFiberManual: any[];
export declare const cilFiberNew: any[];
export declare const cilFiberPin: any[];
export declare const cilFiberSmart: any[];
export declare const cilFileAcrobat: any[];
export declare const cilFileAdd: any[];
export declare const cilFileArchive: any[];
export declare const cilFileAudio: any[];
export declare const cilFileCode: any[];
export declare const cilFileDoc: any[];
export declare const cilFileExcel: any[];
export declare const cilFileImage: any[];
export declare const cilFilePdf: any[];
export declare const cilFilePowerpoint: any[];
export declare const cilFilePpt: any[];
export declare const cilFileVideo: any[];
export declare const cilFileWord: any[];
export declare const cilFileXls: any[];
export declare const cilFile: any[];
export declare const cilFilterFrames: any[];
export declare const cilFilterPhoto: any[];
export declare const cilFilterSquare: any[];
export declare const cilFilterX: any[];
export declare const cilFilter: any[];
export declare const cilFindInPage: any[];
export declare const cilFindReplace: any[];
export declare const cilFingerprint: any[];
export declare const cilFire: any[];
export declare const cilFlagAlt: any[];
export declare const cilFlagRectangle: any[];
export declare const cilFlagTriangle: any[];
export declare const cilFlag: any[];
export declare const cilFlame: any[];
export declare const cilFlash: any[];
export declare const cilFlightLand: any[];
export declare const cilFlightTakeoff: any[];
export declare const cilFlipToBack: any[];
export declare const cilFlipToFront: any[];
export declare const cilFlip: any[];
export declare const cilFlower: any[];
export declare const cilFolderAlt: any[];
export declare const cilFolderArrowLeft: any[];
export declare const cilFolderArrowRight: any[];
export declare const cilFolderBack: any[];
export declare const cilFolderMove: any[];
export declare const cilFolderOpen: any[];
export declare const cilFolderPlus: any[];
export declare const cilFolderShared: any[];
export declare const cilFolderSpecial: any[];
export declare const cilFolder: any[];
export declare const cilFont: any[];
export declare const cilFootball: any[];
export declare const cilFork: any[];
export declare const cilFridge: any[];
export declare const cilFrown: any[];
export declare const cilFullscreenExit: any[];
export declare const cilFullscreen: any[];
export declare const cilFunctionsAlt: any[];
export declare const cilFunctions: any[];
export declare const cilGamepad: any[];
export declare const cilGarage: any[];
export declare const cilGauge: any[];
export declare const cilGem: any[];
export declare const cilGif: any[];
export declare const cilGift: any[];
export declare const cilGlass: any[];
export declare const cilGlobeAltLock: any[];
export declare const cilGlobeAlt: any[];
export declare const cilGlobeLock: any[];
export declare const cilGlobe: any[];
export declare const cilGolfAlt: any[];
export declare const cilGolf: any[];
export declare const cilGradient: any[];
export declare const cilGrain: any[];
export declare const cilGraph: any[];
export declare const cilGridSlash: any[];
export declare const cilGrid: any[];
export declare const cilGripDotsHorizontal: any[];
export declare const cilGripDotsVertical: any[];
export declare const cilGripDots: any[];
export declare const cilGripHorizontal: any[];
export declare const cilGripLinesHorizontal: any[];
export declare const cilGripLinesVertical: any[];
export declare const cilGripLines: any[];
export declare const cilGripVertical: any[];
export declare const cilGrip: any[];
export declare const cilGroupMinus: any[];
export declare const cilGroupPlus: any[];
export declare const cilGroupX: any[];
export declare const cilGroup: any[];
export declare const cilHamburgerMenu: any[];
export declare const cilHandLizard: any[];
export declare const cilHandPaper: any[];
export declare const cilHandPeace: any[];
export declare const cilHandPointDown: any[];
export declare const cilHandPointLeft: any[];
export declare const cilHandPointRight: any[];
export declare const cilHandPointUp: any[];
export declare const cilHandPointer: any[];
export declare const cilHandRock: any[];
export declare const cilHandScissors: any[];
export declare const cilHandSpock: any[];
export declare const cilHandshake: any[];
export declare const cilHappy: any[];
export declare const cilHardDrive: any[];
export declare const cilHd: any[];
export declare const cilHdrSlash: any[];
export declare const cilHdr: any[];
export declare const cilHeader: any[];
export declare const cilHeadphonesMic: any[];
export declare const cilHeadphonesMute: any[];
export declare const cilHeadphones: any[];
export declare const cilHealing: any[];
export declare const cilHeart: any[];
export declare const cilHighQuality: any[];
export declare const cilHighlighter: any[];
export declare const cilHighligt: any[];
export declare const cilHistory: any[];
export declare const cilHome: any[];
export declare const cilHospital: any[];
export declare const cilHotTub: any[];
export declare const cilHotel: any[];
export declare const cilHourglass: any[];
export declare const cilHouse: any[];
export declare const cilHq: any[];
export declare const cilHttp: any[];
export declare const cilHttps: any[];
export declare const cilIdBadge: any[];
export declare const cilIdCard: any[];
export declare const cilImageBroken: any[];
export declare const cilImagePlus: any[];
export declare const cilImage: any[];
export declare const cilImages: any[];
export declare const cilInboxIn: any[];
export declare const cilInboxOut: any[];
export declare const cilInbox: any[];
export declare const cilIndentDecrease: any[];
export declare const cilIndentIncrease: any[];
export declare const cilIndustrySlash: any[];
export declare const cilIndustry: any[];
export declare const cilInfinity: any[];
export declare const cilInfoCircle: any[];
export declare const cilInfo: any[];
export declare const cilInputAntenna: any[];
export declare const cilInputComponent: any[];
export declare const cilInputHdmi: any[];
export declare const cilInputPowerOff: any[];
export declare const cilInputPower: any[];
export declare const cilInputSvideo: any[];
export declare const cilInput: any[];
export declare const cilInstitution: any[];
export declare const cilInvert: any[];
export declare const cilItalic: any[];
export declare const cilJustifyCenter: any[];
export declare const cilJustifyLeft: any[];
export declare const cilJustifyRight: any[];
export declare const cilKeyAlt: any[];
export declare const cilKey: any[];
export declare const cilKeyboardHide: any[];
export declare const cilKeyboard: any[];
export declare const cilKitchen: any[];
export declare const cilLan: any[];
export declare const cilLanguage: any[];
export declare const cilLaptop: any[];
export declare const cilLaundry: any[];
export declare const cilLayersSlash: any[];
export declare const cilLayers: any[];
export declare const cilLeaf: any[];
export declare const cilLemon: any[];
export declare const cilLevelDown: any[];
export declare const cilLevelUp: any[];
export declare const cilLibraryAdd: any[];
export declare const cilLibraryBookmark: any[];
export declare const cilLibraryBooks: any[];
export declare const cilLibraryBuilding: any[];
export declare const cilLibraryMusic: any[];
export declare const cilLibrary: any[];
export declare const cilLifeRing: any[];
export declare const cilLightbulb: any[];
export declare const cilLineSpacing: any[];
export declare const cilLineStyle: any[];
export declare const cilLineWeight: any[];
export declare const cilLinkAlt: any[];
export declare const cilLinkBroken: any[];
export declare const cilLinkIntact: any[];
export declare const cilLinkSlash: any[];
export declare const cilLink: any[];
export declare const cilListFilter: any[];
export declare const cilListHighPriority: any[];
export declare const cilListLowPriority: any[];
export declare const cilListNumberedRtl: any[];
export declare const cilListNumbered: any[];
export declare const cilListRich: any[];
export declare const cilList: any[];
export declare const cilLocationGpsFixed: any[];
export declare const cilLocationGpsOff: any[];
export declare const cilLocationGps: any[];
export declare const cilLocationPinCheck: any[];
export declare const cilLocationPinEdit: any[];
export declare const cilLocationPinPlus: any[];
export declare const cilLocationPinSlash: any[];
export declare const cilLocationPin: any[];
export declare const cilLockLocked: any[];
export declare const cilLockMinus: any[];
export declare const cilLockPlus: any[];
export declare const cilLockUnlocked: any[];
export declare const cilLocomotive: any[];
export declare const cilLoop1: any[];
export declare const cilLoopCircular: any[];
export declare const cilLoopSquare: any[];
export declare const cilLoop: any[];
export declare const cilLowVision: any[];
export declare const cilLoyalty: any[];
export declare const cilMagnifyingGlass: any[];
export declare const cilMail: any[];
export declare const cilMailbox: any[];
export declare const cilMapAlt: any[];
export declare const cilMap: any[];
export declare const cilMediaEjectCircle: any[];
export declare const cilMediaEjectSquare: any[];
export declare const cilMediaEject: any[];
export declare const cilMediaPauseCircle: any[];
export declare const cilMediaPauseSquare: any[];
export declare const cilMediaPause: any[];
export declare const cilMediaPlayCircle: any[];
export declare const cilMediaPlaySquare: any[];
export declare const cilMediaPlay: any[];
export declare const cilMediaRecordCircle: any[];
export declare const cilMediaRecordSquare: any[];
export declare const cilMediaRecord: any[];
export declare const cilMediaSkipBackwardCircle: any[];
export declare const cilMediaSkipBackwardSquare: any[];
export declare const cilMediaSkipBackward: any[];
export declare const cilMediaSkipForwardCircle: any[];
export declare const cilMediaSkipForwardSquare: any[];
export declare const cilMediaSkipForward: any[];
export declare const cilMediaStepBackwardCircle: any[];
export declare const cilMediaStepBackwardSquare: any[];
export declare const cilMediaStepBackward: any[];
export declare const cilMediaStepForwardCircle: any[];
export declare const cilMediaStepForwardSquare: any[];
export declare const cilMediaStepForward: any[];
export declare const cilMediaStopCircle: any[];
export declare const cilMediaStopSquare: any[];
export declare const cilMediaStop: any[];
export declare const cilMedicalCross: any[];
export declare const cilMeh: any[];
export declare const cilMemory: any[];
export declare const cilMenu: any[];
export declare const cilMicAlt: any[];
export declare const cilMicSettings: any[];
export declare const cilMicSlash: any[];
export declare const cilMic: any[];
export declare const cilMicrochip: any[];
export declare const cilMicrophoneAlt: any[];
export declare const cilMicrophoneSettings: any[];
export declare const cilMicrophoneSlash: any[];
export declare const cilMicrophone: any[];
export declare const cilMinusCircle: any[];
export declare const cilMinusSquare: any[];
export declare const cilMinus: any[];
export declare const cilMobileArrowAdd: any[];
export declare const cilMobileArrowRemove: any[];
export declare const cilMobileCheck: any[];
export declare const cilMobileDeveloperMode: any[];
export declare const cilMobileLandscape: any[];
export declare const cilMobileLock: any[];
export declare const cilMobileMinus: any[];
export declare const cilMobilePlus: any[];
export declare const cilMobilePortrait: any[];
export declare const cilMobileSettings: any[];
export declare const cilMobileSlash: any[];
export declare const cilMobileSms: any[];
export declare const cilMobileSpeaker: any[];
export declare const cilMobileVolume: any[];
export declare const cilMobileX: any[];
export declare const cilMobile: any[];
export declare const cilMoneyBillAlt: any[];
export declare const cilMoneyBillAlt2: any[];
export declare const cilMoneyBill: any[];
export declare const cilMoney: any[];
export declare const cilMonitor: any[];
export declare const cilMoodBad: any[];
export declare const cilMoodGood: any[];
export declare const cilMoodVeryBad: any[];
export declare const cilMoodVeryGood: any[];
export declare const cilMoon: any[];
export declare const cilMore: any[];
export declare const cilMotorbike: any[];
export declare const cilMouseAlt: any[];
export declare const cilMouse: any[];
export declare const cilMouthSlash: any[];
export declare const cilMouth: any[];
export declare const cilMoveHorizontal: any[];
export declare const cilMoveVertical: any[];
export declare const cilMove: any[];
export declare const cilMovieAlt: any[];
export declare const cilMovie: any[];
export declare const cilMugTea: any[];
export declare const cilMug: any[];
export declare const cilMusicNoteAlt: any[];
export declare const cilMusicNoteSlash: any[];
export declare const cilMusicNote: any[];
export declare const cilMusicVideo: any[];
export declare const cilNetworkCheck: any[];
export declare const cilNewReleases: any[];
export declare const cilNew: any[];
export declare const cilNewspaper: any[];
export declare const cilNoteAdd: any[];
export declare const cilNote: any[];
export declare const cilNotes: any[];
export declare const cilObjectGroup: any[];
export declare const cilObjectUngroup: any[];
export declare const cilOpacity: any[];
export declare const cilOpentype: any[];
export declare const cilOptionsAlt: any[];
export declare const cilOptions: any[];
export declare const cilOven: any[];
export declare const cilOverscanSettings: any[];
export declare const cilOverscan: any[];
export declare const cilPageRestore: any[];
export declare const cilPage: any[];
export declare const cilPageview: any[];
export declare const cilPaintBucket: any[];
export declare const cilPaint: any[];
export declare const cilPaperPlane: any[];
export declare const cilPaperclip: any[];
export declare const cilParagraph: any[];
export declare const cilParking: any[];
export declare const cilPaw: any[];
export declare const cilPenAlt: any[];
export declare const cilPenFancy: any[];
export declare const cilPenNib: any[];
export declare const cilPen: any[];
export declare const cilPencil: any[];
export declare const cilPeopleMinus: any[];
export declare const cilPeoplePlus: any[];
export declare const cilPeopleX: any[];
export declare const cilPeople: any[];
export declare const cilPercent: any[];
export declare const cilPersonFemale: any[];
export declare const cilPerson: any[];
export declare const cilPetrolStation: any[];
export declare const cilPhoneBluetooth: any[];
export declare const cilPhoneCallEnd: any[];
export declare const cilPhoneCall: any[];
export declare const cilPhoneCallback: any[];
export declare const cilPhoneCheck: any[];
export declare const cilPhoneForward: any[];
export declare const cilPhoneInTalk: any[];
export declare const cilPhoneLock: any[];
export declare const cilPhoneMinus: any[];
export declare const cilPhoneMissed: any[];
export declare const cilPhonePaused: any[];
export declare const cilPhonePlus: any[];
export declare const cilPhoneRingVolume: any[];
export declare const cilPhoneSettings: any[];
export declare const cilPhoneSlash: any[];
export declare const cilPhoneSquare: any[];
export declare const cilPhoneVolume: any[];
export declare const cilPhoneX: any[];
export declare const cilPhone: any[];
export declare const cilPictureInPictureAlt: any[];
export declare const cilPictureInPicture: any[];
export declare const cilPin: any[];
export declare const cilPizza: any[];
export declare const cilPlant: any[];
export declare const cilPlaylistAddCheck: any[];
export declare const cilPlaylistAdd: any[];
export declare const cilPlaylistPlay: any[];
export declare const cilPlusCircle: any[];
export declare const cilPlusOne: any[];
export declare const cilPlusSquare: any[];
export declare const cilPlus: any[];
export declare const cilPool: any[];
export declare const cilPortableWifiOff: any[];
export declare const cilPortableWifi: any[];
export declare const cilPowerSettings: any[];
export declare const cilPowerStandby: any[];
export declare const cilPregnant: any[];
export declare const cilPrint: any[];
export declare const cilPrinterSlash: any[];
export declare const cilPrinter: any[];
export declare const cilPushchair: any[];
export declare const cilPuzzlePiece: any[];
export declare const cilPuzzle: any[];
export declare const cilQrCode: any[];
export declare const cilQueueAdd: any[];
export declare const cilQueueMusic: any[];
export declare const cilQueuePlayNext: any[];
export declare const cilQueueRemove: any[];
export declare const cilQueue: any[];
export declare const cilRadio: any[];
export declare const cilRailway: any[];
export declare const cilRain: any[];
export declare const cilRandom: any[];
export declare const cilRecentActors: any[];
export declare const cilRectangle: any[];
export declare const cilRecycle: any[];
export declare const cilRegistered: any[];
export declare const cilReload: any[];
export declare const cilRemoteControl: any[];
export declare const cilRemoteSettings: any[];
export declare const cilReplay: any[];
export declare const cilReportSlash: any[];
export declare const cilReport: any[];
export declare const cilResizeBoth: any[];
export declare const cilResizeHeight: any[];
export declare const cilResizeWidth: any[];
export declare const cilRestaurantMenu: any[];
export declare const cilRestaurant: any[];
export declare const cilRestore: any[];
export declare const cilRights: any[];
export declare const cilRoomSlash: any[];
export declare const cilRoom: any[];
export declare const cilRotateLeft: any[];
export declare const cilRotateRight: any[];
export declare const cilRoundedCorner: any[];
export declare const cilRouter: any[];
export declare const cilRowing: any[];
export declare const cilRssAlt: any[];
export declare const cilRssSquare: any[];
export declare const cilRss: any[];
export declare const cilRubleCircleSlash: any[];
export declare const cilRubleCircle: any[];
export declare const cilRubleSlash: any[];
export declare const cilRuble: any[];
export declare const cilRunning: any[];
export declare const cilSad: any[];
export declare const cilSatelite: any[];
export declare const cilSave: any[];
export declare const cilScaleImage: any[];
export declare const cilScale: any[];
export declare const cilScanner: any[];
export declare const cilSchool: any[];
export declare const cilScooter: any[];
export declare const cilScreenDeskopSlash: any[];
export declare const cilScreenDesktop: any[];
export declare const cilScreenHorizontal: any[];
export declare const cilScreenLandscape: any[];
export declare const cilScreenLockHorizontal: any[];
export declare const cilScreenLockLandscape: any[];
export declare const cilScreenLockPortrait: any[];
export declare const cilScreenLockRotation: any[];
export declare const cilScreenLockVertical: any[];
export declare const cilScreenMirroring: any[];
export declare const cilScreenPortrait: any[];
export declare const cilScreenRotation: any[];
export declare const cilScreenSmartphone: any[];
export declare const cilScreenVertical: any[];
export declare const cilScript: any[];
export declare const cilScrubber: any[];
export declare const cilSdcard: any[];
export declare const cilSearch: any[];
export declare const cilSecurity: any[];
export declare const cilSelectAll: any[];
export declare const cilSelect: any[];
export declare const cilSend: any[];
export declare const cilSettingsAlt: any[];
export declare const cilSettings: any[];
export declare const cilShareAll: any[];
export declare const cilShareAlt: any[];
export declare const cilShareBoxed: any[];
export declare const cilShare: any[];
export declare const cilShieldAlt: any[];
export declare const cilShieldCheck: any[];
export declare const cilShieldMinus: any[];
export declare const cilShieldPlus: any[];
export declare const cilShieldSlash: any[];
export declare const cilShieldX: any[];
export declare const cilShield: any[];
export declare const cilShopMediaTwo: any[];
export declare const cilShopMedia: any[];
export declare const cilShortText: any[];
export declare const cilShower: any[];
export declare const cilSignLanguage: any[];
export declare const cilSignalCellular0: any[];
export declare const cilSignalCellular1: any[];
export declare const cilSignalCellular2: any[];
export declare const cilSignalCellular3: any[];
export declare const cilSignalCellular4: any[];
export declare const cilSignalCellularNoInternet0: any[];
export declare const cilSignalCellularNoInternet1: any[];
export declare const cilSignalCellularNoInternet2: any[];
export declare const cilSignalCellularNoInternet3: any[];
export declare const cilSignalCellularNoInternet4: any[];
export declare const cilSignalCellularOff: any[];
export declare const cilSignalOff: any[];
export declare const cilSignal: any[];
export declare const cilSignpost: any[];
export declare const cilSimSlash: any[];
export declare const cilSim: any[];
export declare const cilSitemap: any[];
export declare const cilSlowMotion: any[];
export declare const cilSmilePlus: any[];
export declare const cilSmile: any[];
export declare const cilSmokeFree: any[];
export declare const cilSmokeSlash: any[];
export declare const cilSmoke: any[];
export declare const cilSmokingRoom: any[];
export declare const cilSnow: any[];
export declare const cilSnowflake: any[];
export declare const cilSoccer: any[];
export declare const cilSofa: any[];
export declare const cilSorroundSound: any[];
export declare const cilSortAlphaDown: any[];
export declare const cilSortAlphaUp: any[];
export declare const cilSortAscending: any[];
export declare const cilSortDescending: any[];
export declare const cilSortNumericDown: any[];
export declare const cilSortNumericUp: any[];
export declare const cilSound: any[];
export declare const cilSpa: any[];
export declare const cilSpaceBar: any[];
export declare const cilSpeak: any[];
export declare const cilSpeakerGroup: any[];
export declare const cilSpeaker: any[];
export declare const cilSpeechBubble: any[];
export declare const cilSpeechNotesSlash: any[];
export declare const cilSpeechNotes: any[];
export declare const cilSpeech: any[];
export declare const cilSpeedometer: any[];
export declare const cilSpreadsheet: any[];
export declare const cilSquare: any[];
export declare const cilStarCircle: any[];
export declare const cilStarHalf: any[];
export declare const cilStar: any[];
export declare const cilStickyNote: any[];
export declare const cilStorage: any[];
export declare const cilStore: any[];
export declare const cilStream: any[];
export declare const cilStrikethrough: any[];
export declare const cilSubtitles: any[];
export declare const cilSubway: any[];
export declare const cilSun: any[];
export declare const cilSwapHorizontalCircle: any[];
export declare const cilSwapHorizontal: any[];
export declare const cilSwapVerticalCircle: any[];
export declare const cilSwapVertical: any[];
export declare const cilSwimming: any[];
export declare const cilSyncDisabled: any[];
export declare const cilSyncProblem: any[];
export declare const cilSync: any[];
export declare const cilTablet: any[];
export declare const cilTag: any[];
export declare const cilTags: any[];
export declare const cilTarget: any[];
export declare const cilTask: any[];
export declare const cilTaxi: any[];
export declare const cilTemperatureAlt: any[];
export declare const cilTemperatureHigh: any[];
export declare const cilTemperatureLow: any[];
export declare const cilTemperature: any[];
export declare const cilTennisBall: any[];
export declare const cilTennis: any[];
export declare const cilTerminal: any[];
export declare const cilTerrain: any[];
export declare const cilTextDirectionLtr: any[];
export declare const cilTextDirectionRtl: any[];
export declare const cilTextFormatClear: any[];
export declare const cilTextHeight: any[];
export declare const cilTextRotateVertical: any[];
export declare const cilTextRotationDown: any[];
export declare const cilTextRotationNone: any[];
export declare const cilTextRotationUp: any[];
export declare const cilTextShapes: any[];
export declare const cilTextSize: any[];
export declare const cilTextSquare: any[];
export declare const cilTextStrike: any[];
export declare const cilTextWidth: any[];
export declare const cilText: any[];
export declare const cilThermometerAlt: any[];
export declare const cilThermometer: any[];
export declare const cilThumbDown: any[];
export declare const cilThumbUp: any[];
export declare const cilTimeline: any[];
export declare const cilTimer: any[];
export declare const cilToggleOff: any[];
export declare const cilToggleOn: any[];
export declare const cilToilet: any[];
export declare const cilToll: any[];
export declare const cilTouchApp: any[];
export declare const cilTrademark: any[];
export declare const cilTraffic: any[];
export declare const cilTrainAlt: any[];
export declare const cilTrain: any[];
export declare const cilTram: any[];
export declare const cilTransferWithinAStation: any[];
export declare const cilTransfer: any[];
export declare const cilTranslate: any[];
export declare const cilTrashAlt: any[];
export declare const cilTrashArrowUp: any[];
export declare const cilTrashSweep: any[];
export declare const cilTrashX: any[];
export declare const cilTrash: any[];
export declare const cilTriangle: any[];
export declare const cilTruck: any[];
export declare const cilTty: any[];
export declare const cilTvDvr: any[];
export declare const cilTvLive: any[];
export declare const cilTvSlash: any[];
export declare const cilTv: any[];
export declare const cilUnderline: any[];
export declare const cilUniversalAccess: any[];
export declare const cilUpdate: any[];
export declare const cilUsb: any[];
export declare const cilUserFemaleFollow: any[];
export declare const cilUserFemaleMinus: any[];
export declare const cilUserFemalePlus: any[];
export declare const cilUserFemaleUnfollow: any[];
export declare const cilUserFemaleX: any[];
export declare const cilUserFemale: any[];
export declare const cilUserFollow: any[];
export declare const cilUserMinus: any[];
export declare const cilUserPlus: any[];
export declare const cilUserSecret: any[];
export declare const cilUserUnfollow: any[];
export declare const cilUserX: any[];
export declare const cilUser: any[];
export declare const cilVector: any[];
export declare const cilVericalSplit: any[];
export declare const cilVerticalAlignBottom: any[];
export declare const cilVerticalAlignCenter: any[];
export declare const cilVerticalAlignTop: any[];
export declare const cilVideoLabel: any[];
export declare const cilVideoLibrary: any[];
export declare const cilVideoMissed: any[];
export declare const cilVideoPlus: any[];
export declare const cilVideoSlash: any[];
export declare const cilVideoSwitch: any[];
export declare const cilVideo: any[];
export declare const cilVideogame: any[];
export declare const cilViewAgenda: any[];
export declare const cilViewArray: any[];
export declare const cilViewCarousel: any[];
export declare const cilViewColumn: any[];
export declare const cilViewList: any[];
export declare const cilViewModule: any[];
export declare const cilViewQuilt: any[];
export declare const cilViewRow: any[];
export declare const cilViewStream: any[];
export declare const cilVoiceOverRecord: any[];
export declare const cilVoiceOverSlash: any[];
export declare const cilVoice: any[];
export declare const cilVoicemail: any[];
export declare const cilVolumeHigh: any[];
export declare const cilVolumeLow: any[];
export declare const cilVolumeOff: any[];
export declare const cilVolume: any[];
export declare const cilVote: any[];
export declare const cilWalk: any[];
export declare const cilWallet: any[];
export declare const cilWallpaper: any[];
export declare const cilWarning: any[];
export declare const cilWatch: any[];
export declare const cilWaves: any[];
export declare const cilWc: any[];
export declare const cilWebcloud: any[];
export declare const cilWeightlifitng: any[];
export declare const cilWeights: any[];
export declare const cilWheelchair: any[];
export declare const cilWidgets: any[];
export declare const cilWifiLock: any[];
export declare const cilWifiSignal0: any[];
export declare const cilWifiSignal1: any[];
export declare const cilWifiSignal2: any[];
export declare const cilWifiSignal3: any[];
export declare const cilWifiSignal4: any[];
export declare const cilWifiSignalLock0: any[];
export declare const cilWifiSignalLock1: any[];
export declare const cilWifiSignalLock2: any[];
export declare const cilWifiSignalLock3: any[];
export declare const cilWifiSignalLock4: any[];
export declare const cilWifiSignalOff: any[];
export declare const cilWifi: any[];
export declare const cilWindowMaximize: any[];
export declare const cilWindowMinimize: any[];
export declare const cilWindowRestore: any[];
export declare const cilWindow: any[];
export declare const cilWrapText: any[];
export declare const cilXCircle: any[];
export declare const cilXSquare: any[];
export declare const cilX: any[];
export declare const cilYenCircleSlash: any[];
export declare const cilYenCircle: any[];
export declare const cilYenSlash: any[];
export declare const cilYen: any[];
export declare const cilZoomIn: any[];
export declare const cilZoomOut: any[];
export declare const cilZoom: any[];