version: '3.3'

services:
  client:
    build: .
    restart: unless-stopped
    container_name: monitoring_service
    ports:
      - 3000:3000
    volumes:
      - ./packages/landingpage:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env
