export declare const solidSet: {
  "cis3dRotate": any[];
  "cis3d": any[];
  "cis4k": any[];
  "cisAccessibility": any[];
  "cisAccessible": any[];
  "cisAccountLogout": any[];
  "cisActionRedo": any[];
  "cisActionUndo": any[];
  "cisAddressBook": any[];
  "cisAddressCard": any[];
  "cisAirplaneModeOff": any[];
  "cisAirplaneMode": any[];
  "cisAirplay": any[];
  "cisAlarmAdd": any[];
  "cisAlarmOff": any[];
  "cisAlarmOn": any[];
  "cisAlarmSnooze": any[];
  "cisAlarm": any[];
  "cisAlbum": any[];
  "cisAlignCenter": any[];
  "cisAlignLeft": any[];
  "cisAlignRight": any[];
  "cisAmericanFootball": any[];
  "cisAnimal": any[];
  "cisAperture": any[];
  "cisApple": any[];
  "cisApplicationsSettings": any[];
  "cisApplications": any[];
  "cisAppsSettings": any[];
  "cisApps": any[];
  "cisArchive": any[];
  "cisArrowBottom": any[];
  "cisArrowCircleBottom": any[];
  "cisArrowCircleLeft": any[];
  "cisArrowCircleRight": any[];
  "cisArrowCircleTop": any[];
  "cisArrowLeft": any[];
  "cisArrowRight": any[];
  "cisArrowThickBottom": any[];
  "cisArrowThickCircleDown": any[];
  "cisArrowThickCircleLeft": any[];
  "cisArrowThickCircleRight": any[];
  "cisArrowThickCircleUp": any[];
  "cisArrowThickFromBottom": any[];
  "cisArrowThickFromLeft": any[];
  "cisArrowThickFromRight": any[];
  "cisArrowThickFromTop": any[];
  "cisArrowThickLeft": any[];
  "cisArrowThickRight": any[];
  "cisArrowThickSquareDown": any[];
  "cisArrowThickSquareLeft": any[];
  "cisArrowThickSquareRight": any[];
  "cisArrowThickSquareUp": any[];
  "cisArrowThickToBottom": any[];
  "cisArrowThickToLeft": any[];
  "cisArrowThickToRight": any[];
  "cisArrowThickToTop": any[];
  "cisArrowThickTop": any[];
  "cisArrowTop": any[];
  "cisArtTrack": any[];
  "cisAspectRatio": any[];
  "cisAssistiveListeningSystem": any[];
  "cisAsteriskCircle": any[];
  "cisAsterisk": any[];
  "cisAt": any[];
  "cisAudioDescription": any[];
  "cisAudioSpectrum": any[];
  "cisAudio": any[];
  "cisAvTimer": any[];
  "cisBabyCarriage": any[];
  "cisBaby": any[];
  "cisBackspace": any[];
  "cisBadge": any[];
  "cisBalanceScaleLeft": any[];
  "cisBalanceScaleRight": any[];
  "cisBalanceScale": any[];
  "cisBan": any[];
  "cisBank": any[];
  "cisBarChart": any[];
  "cisBarcode": any[];
  "cisBaseball": any[];
  "cisBasketArrowDown": any[];
  "cisBasketLoaded": any[];
  "cisBasketPlus": any[];
  "cisBasket": any[];
  "cisBasketball": any[];
  "cisBath": any[];
  "cisBathroom": any[];
  "cisBattery0": any[];
  "cisBattery1": any[];
  "cisBattery2": any[];
  "cisBattery3": any[];
  "cisBattery4": any[];
  "cisBattery5": any[];
  "cisBatteryAlert": any[];
  "cisBatteryAlt0": any[];
  "cisBatteryAlt1": any[];
  "cisBatteryAlt2": any[];
  "cisBatteryAlt3": any[];
  "cisBatteryAltEmpty": any[];
  "cisBatteryAltFull": any[];
  "cisBatteryAltSlash": any[];
  "cisBatteryCharge": any[];
  "cisBatteryEmpty": any[];
  "cisBatteryFull": any[];
  "cisBatterySlash": any[];
  "cisBatteryUnknown": any[];
  "cisBeachAccess": any[];
  "cisBeaker": any[];
  "cisBed": any[];
  "cisBellExclamation": any[];
  "cisBellPlus": any[];
  "cisBellRing": any[];
  "cisBellSlash": any[];
  "cisBell": any[];
  "cisBikeAlt": any[];
  "cisBike": any[];
  "cisBirthdayCake": any[];
  "cisBlind": any[];
  "cisBluetoothConnected": any[];
  "cisBluetoothSearching": any[];
  "cisBluetoothSettings": any[];
  "cisBluetoothSlash": any[];
  "cisBluetooth": any[];
  "cisBlurCircular": any[];
  "cisBlurLinear": any[];
  "cisBlurSlash": any[];
  "cisBlur": any[];
  "cisBoatAlt": any[];
  "cisBoat": any[];
  "cisBold": any[];
  "cisBoltAlt": any[];
  "cisBoltCircle": any[];
  "cisBolt": any[];
  "cisBookOpen": any[];
  "cisBook": any[];
  "cisBookmark": any[];
  "cisBookmarks": any[];
  "cisBorderAll": any[];
  "cisBorderBottom": any[];
  "cisBorderClear": any[];
  "cisBorderHorizontal": any[];
  "cisBorderInner": any[];
  "cisBorderLeft": any[];
  "cisBorderOuter": any[];
  "cisBorderRight": any[];
  "cisBorderStyle": any[];
  "cisBorderTop": any[];
  "cisBorderVertical": any[];
  "cisBowlingPins": any[];
  "cisBowling": any[];
  "cisBoxAlt": any[];
  "cisBox": any[];
  "cisBraille": any[];
  "cisBrandingWatermark": any[];
  "cisBriefcaseArrowLeft": any[];
  "cisBriefcaseArrowRight": any[];
  "cisBriefcaseSlash": any[];
  "cisBriefcase": any[];
  "cisBrightnessAuto": any[];
  "cisBrightnessHigh": any[];
  "cisBrightnessLow": any[];
  "cisBrightnessMedium": any[];
  "cisBrightness": any[];
  "cisBritishPoundCircle": any[];
  "cisBritishPoundSlash": any[];
  "cisBritishPound": any[];
  "cisBroadcastTower": any[];
  "cisBrowser": any[];
  "cisBrushAlt": any[];
  "cisBrush": any[];
  "cisBug": any[];
  "cisBuildingBusinessSlash": any[];
  "cisBuildingBusiness": any[];
  "cisBuildingSlash": any[];
  "cisBuilding": any[];
  "cisBullhorn": any[];
  "cisBurger": any[];
  "cisBurn": any[];
  "cisBusAlt": any[];
  "cisBusTimer": any[];
  "cisBus": any[];
  "cisCalculator": any[];
  "cisCalendarAlt": any[];
  "cisCalendarCheck": any[];
  "cisCalendarEvent": any[];
  "cisCalendarMinus": any[];
  "cisCalendarNote": any[];
  "cisCalendarPlus": any[];
  "cisCalendarTimes": any[];
  "cisCalendarToday": any[];
  "cisCalendarViewDay": any[];
  "cisCalendar": any[];
  "cisCallMade": any[];
  "cisCallMerge": any[];
  "cisCallMissedOutgoing": any[];
  "cisCallMissed": any[];
  "cisCallReceived": any[];
  "cisCallSplit": any[];
  "cisCallSwapCalls": any[];
  "cisCallToAction": any[];
  "cisCameraControl": any[];
  "cisCameraEnhance": any[];
  "cisCameraPlus": any[];
  "cisCameraRoll": any[];
  "cisCameraSwitch": any[];
  "cisCamera": any[];
  "cisCarAlt": any[];
  "cisCar": any[];
  "cisCardGiftcard": any[];
  "cisCardMembership": any[];
  "cisCardTravel": any[];
  "cisCaretBottom": any[];
  "cisCaretLeft": any[];
  "cisCaretRight": any[];
  "cisCaretTop": any[];
  "cisCartArrowDown": any[];
  "cisCartLoaded": any[];
  "cisCartPlus": any[];
  "cisCartSlash": any[];
  "cisCart": any[];
  "cisCash": any[];
  "cisCasino": any[];
  "cisCastConnected": any[];
  "cisCastForEducation": any[];
  "cisCast": any[];
  "cisCat": any[];
  "cisCc": any[];
  "cisCenterFocusWeak": any[];
  "cisCenterFocus": any[];
  "cisChalkboardTeacher": any[];
  "cisChartArea": any[];
  "cisChartBubble": any[];
  "cisChartDonut": any[];
  "cisChartLine": any[];
  "cisChartMultiline": any[];
  "cisChartPie": any[];
  "cisChartShow": any[];
  "cisChartTable": any[];
  "cisChart": any[];
  "cisChatBubble": any[];
  "cisChatSquare": any[];
  "cisCheckAlt": any[];
  "cisCheckCircle": any[];
  "cisCheckDoubleAlt": any[];
  "cisCheckDouble": any[];
  "cisCheck": any[];
  "cisChevronBottomAlt": any[];
  "cisChevronBottom": any[];
  "cisChevronCircleDownAlt": any[];
  "cisChevronCircleDown": any[];
  "cisChevronCircleLeftAlt": any[];
  "cisChevronCircleLeft": any[];
  "cisChevronCircleRightAlt": any[];
  "cisChevronCircleRight": any[];
  "cisChevronCircleUpAlt": any[];
  "cisChevronCircleUp": any[];
  "cisChevronDoubleDownAlt": any[];
  "cisChevronDoubleDown": any[];
  "cisChevronDoubleLeftAlt": any[];
  "cisChevronDoubleLeft": any[];
  "cisChevronDoubleRightAlt": any[];
  "cisChevronDoubleRight": any[];
  "cisChevronDoubleUpAlt": any[];
  "cisChevronDoubleUp": any[];
  "cisChevronLeftAlt": any[];
  "cisChevronLeft": any[];
  "cisChevronRightAlt": any[];
  "cisChevronRight": any[];
  "cisChevronSquareDownAlt": any[];
  "cisChevronSquareDown": any[];
  "cisChevronSquareLeftAlt": any[];
  "cisChevronSquareLeft": any[];
  "cisChevronSquareRightAlt": any[];
  "cisChevronSquareRight": any[];
  "cisChevronSquareUpAlt": any[];
  "cisChevronSquareUp": any[];
  "cisChevronTopAlt": any[];
  "cisChevronTop": any[];
  "cisChildFriendly": any[];
  "cisChild": any[];
  "cisCircle": any[];
  "cisCity": any[];
  "cisClearAll": any[];
  "cisClipboard": any[];
  "cisClock": any[];
  "cisClone": any[];
  "cisClosedCaptioning": any[];
  "cisCloudCheck": any[];
  "cisCloudCircle": any[];
  "cisCloudData": any[];
  "cisCloudDownload": any[];
  "cisCloudSlash": any[];
  "cisCloudUpload": any[];
  "cisCloud": any[];
  "cisCloudy": any[];
  "cisCode": any[];
  "cisCoffee": any[];
  "cisCog": any[];
  "cisColorBorder": any[];
  "cisColorFill": any[];
  "cisColorPalette": any[];
  "cisColumns": any[];
  "cisCommand": any[];
  "cisCommentBubbleCheck": any[];
  "cisCommentBubbleEdit": any[];
  "cisCommentBubbleExclamation": any[];
  "cisCommentBubbleLines": any[];
  "cisCommentBubbleMinus": any[];
  "cisCommentBubblePlus": any[];
  "cisCommentBubbleQuestion": any[];
  "cisCommentBubbleSmile": any[];
  "cisCommentBubbleX": any[];
  "cisCommentBubble": any[];
  "cisCommentSquareCheck": any[];
  "cisCommentSquareEdit": any[];
  "cisCommentSquareExclamation": any[];
  "cisCommentSquareImage": any[];
  "cisCommentSquareLines": any[];
  "cisCommentSquareMinus": any[];
  "cisCommentSquarePlus": any[];
  "cisCommentSquareRateReview": any[];
  "cisCommentSquareSmile": any[];
  "cisCommentSquareX": any[];
  "cisCommentSquare": any[];
  "cisCommute": any[];
  "cisCompare": any[];
  "cisCompassCalibration": any[];
  "cisCompassSlash": any[];
  "cisCompass": any[];
  "cisCompressWide": any[];
  "cisCompress": any[];
  "cisContactMail": any[];
  "cisContactPhone": any[];
  "cisContact": any[];
  "cisContacts": any[];
  "cisContrast": any[];
  "cisControl": any[];
  "cisCopy": any[];
  "cisCopyright": any[];
  "cisCouch": any[];
  "cisCreditCard": any[];
  "cisCropRotate": any[];
  "cisCrop": any[];
  "cisCursorMove": any[];
  "cisCursor": any[];
  "cisCut": any[];
  "cisDataTransferDown": any[];
  "cisDataTransferUp": any[];
  "cisDeaf": any[];
  "cisDelete": any[];
  "cisDescription": any[];
  "cisDeveloperBoard": any[];
  "cisDeviceUnknown": any[];
  "cisDevicesImportant": any[];
  "cisDevicesOther": any[];
  "cisDevicesSlash": any[];
  "cisDevices": any[];
  "cisDial": any[];
  "cisDialpad": any[];
  "cisDiamond": any[];
  "cisDinner": any[];
  "cisDirections": any[];
  "cisDisabled": any[];
  "cisDns": any[];
  "cisDock": any[];
  "cisDocument": any[];
  "cisDog": any[];
  "cisDollarCircleSlash": any[];
  "cisDollarCircle": any[];
  "cisDollarSlash": any[];
  "cisDollar": any[];
  "cisDonate": any[];
  "cisDoor": any[];
  "cisDoubleQuoteSansLeft": any[];
  "cisDoubleQuoteSansRight": any[];
  "cisDoubleQuoteSerifLeft": any[];
  "cisDoubleQuoteSerifRight": any[];
  "cisDrinkAlcohol": any[];
  "cisDrink": any[];
  "cisDropSlash": any[];
  "cisDrop": any[];
  "cisDvr": any[];
  "cisEar": any[];
  "cisEco": any[];
  "cisEducation": any[];
  "cisElevator": any[];
  "cisEllipsis": any[];
  "cisEnergyCircle": any[];
  "cisEnergy": any[];
  "cisEnvelopeClosed": any[];
  "cisEnvelopeLetter": any[];
  "cisEnvelopeMinus": any[];
  "cisEnvelopeOpen": any[];
  "cisEnvelopePlus": any[];
  "cisEqualizer": any[];
  "cisEthernetAlt": any[];
  "cisEthernet": any[];
  "cisEuroCircleSlash": any[];
  "cisEuroCircle": any[];
  "cisEuroSlash": any[];
  "cisEuro": any[];
  "cisEvStation": any[];
  "cisExcerpt": any[];
  "cisExclamationCircle": any[];
  "cisExclamation": any[];
  "cisExitToApp": any[];
  "cisExpandDown": any[];
  "cisExpandLeft": any[];
  "cisExpandRight": any[];
  "cisExpandUp": any[];
  "cisExposure": any[];
  "cisExternalLink": any[];
  "cisEyeSlash": any[];
  "cisEye": any[];
  "cisEyedropper": any[];
  "cisFaceDead": any[];
  "cisFace": any[];
  "cisFactorySlash": any[];
  "cisFactory": any[];
  "cisFastfood": any[];
  "cisFax": any[];
  "cisFeaturedPlaylist": any[];
  "cisFeaturedVideo": any[];
  "cisFiberDvr": any[];
  "cisFiberManual": any[];
  "cisFiberNew": any[];
  "cisFiberPin": any[];
  "cisFiberSmart": any[];
  "cisFileAcrobat": any[];
  "cisFileAdd": any[];
  "cisFileArchive": any[];
  "cisFileAudio": any[];
  "cisFileCode": any[];
  "cisFileDoc": any[];
  "cisFileExcel": any[];
  "cisFileImage": any[];
  "cisFilePdf": any[];
  "cisFilePowerpoint": any[];
  "cisFilePpt": any[];
  "cisFileVideo": any[];
  "cisFileWord": any[];
  "cisFileXls": any[];
  "cisFile": any[];
  "cisFilterFrames": any[];
  "cisFilterPhoto": any[];
  "cisFilterSquare": any[];
  "cisFilterX": any[];
  "cisFilter": any[];
  "cisFindInPage": any[];
  "cisFindReplace": any[];
  "cisFingerprint": any[];
  "cisFire": any[];
  "cisFlagAlt": any[];
  "cisFlagRectangle": any[];
  "cisFlagTriangle": any[];
  "cisFlag": any[];
  "cisFlame": any[];
  "cisFlash": any[];
  "cisFlightLand": any[];
  "cisFlightTakeoff": any[];
  "cisFlipToBack": any[];
  "cisFlipToFront": any[];
  "cisFlip": any[];
  "cisFlower": any[];
  "cisFolderAlt": any[];
  "cisFolderArrowLeft": any[];
  "cisFolderArrowRight": any[];
  "cisFolderBack": any[];
  "cisFolderMove": any[];
  "cisFolderOpen": any[];
  "cisFolderPlus": any[];
  "cisFolderShared": any[];
  "cisFolderSpecial": any[];
  "cisFolder": any[];
  "cisFont": any[];
  "cisFootball": any[];
  "cisFork": any[];
  "cisFridge": any[];
  "cisFrown": any[];
  "cisFullscreenExit": any[];
  "cisFullscreen": any[];
  "cisFunctionsAlt": any[];
  "cisFunctions": any[];
  "cisGamepad": any[];
  "cisGarage": any[];
  "cisGauge": any[];
  "cisGem": any[];
  "cisGif": any[];
  "cisGift": any[];
  "cisGlass": any[];
  "cisGlobeAltLock": any[];
  "cisGlobeAlt": any[];
  "cisGlobeLock": any[];
  "cisGlobe": any[];
  "cisGolfAlt": any[];
  "cisGolf": any[];
  "cisGradient": any[];
  "cisGrain": any[];
  "cisGraph": any[];
  "cisGridSlash": any[];
  "cisGrid": any[];
  "cisGripDotsHorizontal": any[];
  "cisGripDotsVertical": any[];
  "cisGripDots": any[];
  "cisGripHorizontal": any[];
  "cisGripLinesHorizontal": any[];
  "cisGripLinesVertical": any[];
  "cisGripLines": any[];
  "cisGripVertical": any[];
  "cisGrip": any[];
  "cisGroupMinus": any[];
  "cisGroupPlus": any[];
  "cisGroupX": any[];
  "cisGroup": any[];
  "cisHamburgerMenu": any[];
  "cisHandLizard": any[];
  "cisHandPaper": any[];
  "cisHandPeace": any[];
  "cisHandPointDown": any[];
  "cisHandPointLeft": any[];
  "cisHandPointRight": any[];
  "cisHandPointUp": any[];
  "cisHandPointer": any[];
  "cisHandRock": any[];
  "cisHandScissors": any[];
  "cisHandSpock": any[];
  "cisHandshake": any[];
  "cisHappy": any[];
  "cisHardDrive": any[];
  "cisHd": any[];
  "cisHdrSlash": any[];
  "cisHdr": any[];
  "cisHeader": any[];
  "cisHeadphonesMic": any[];
  "cisHeadphonesMute": any[];
  "cisHeadphones": any[];
  "cisHealing": any[];
  "cisHeart": any[];
  "cisHighQuality": any[];
  "cisHighlighter": any[];
  "cisHighligt": any[];
  "cisHistory": any[];
  "cisHome": any[];
  "cisHospital": any[];
  "cisHotTub": any[];
  "cisHotel": any[];
  "cisHourglass": any[];
  "cisHouse": any[];
  "cisHq": any[];
  "cisHttp": any[];
  "cisHttps": any[];
  "cisIdBadge": any[];
  "cisIdCard": any[];
  "cisImageBroken": any[];
  "cisImagePlus": any[];
  "cisImage": any[];
  "cisImages": any[];
  "cisInboxIn": any[];
  "cisInboxOut": any[];
  "cisInbox": any[];
  "cisIndentDecrease": any[];
  "cisIndentIncrease": any[];
  "cisIndustrySlash": any[];
  "cisIndustry": any[];
  "cisInfinity": any[];
  "cisInfoCircle": any[];
  "cisInfo": any[];
  "cisInputAntenna": any[];
  "cisInputComponent": any[];
  "cisInputHdmi": any[];
  "cisInputPowerOff": any[];
  "cisInputPower": any[];
  "cisInputSvideo": any[];
  "cisInput": any[];
  "cisInstitution": any[];
  "cisInvert": any[];
  "cisItalic": any[];
  "cisJustifyCenter": any[];
  "cisJustifyLeft": any[];
  "cisJustifyRight": any[];
  "cisKeyAlt": any[];
  "cisKey": any[];
  "cisKeyboardHide": any[];
  "cisKeyboard": any[];
  "cisKitchen": any[];
  "cisLan": any[];
  "cisLanguage": any[];
  "cisLaptop": any[];
  "cisLaundry": any[];
  "cisLayersSlash": any[];
  "cisLayers": any[];
  "cisLeaf": any[];
  "cisLemon": any[];
  "cisLevelDown": any[];
  "cisLevelUp": any[];
  "cisLibraryAdd": any[];
  "cisLibraryBookmark": any[];
  "cisLibraryBooks": any[];
  "cisLibraryBuilding": any[];
  "cisLibraryMusic": any[];
  "cisLibrary": any[];
  "cisLifeRing": any[];
  "cisLightbulb": any[];
  "cisLineSpacing": any[];
  "cisLineStyle": any[];
  "cisLineWeight": any[];
  "cisLinkAlt": any[];
  "cisLinkBroken": any[];
  "cisLinkIntact": any[];
  "cisLinkSlash": any[];
  "cisLink": any[];
  "cisListFilter": any[];
  "cisListHighPriority": any[];
  "cisListLowPriority": any[];
  "cisListNumberedRtl": any[];
  "cisListNumbered": any[];
  "cisListRich": any[];
  "cisList": any[];
  "cisLocationGpsFixed": any[];
  "cisLocationGpsOff": any[];
  "cisLocationGps": any[];
  "cisLocationPinCheck": any[];
  "cisLocationPinEdit": any[];
  "cisLocationPinPlus": any[];
  "cisLocationPinSlash": any[];
  "cisLocationPin": any[];
  "cisLockLocked": any[];
  "cisLockMinus": any[];
  "cisLockPlus": any[];
  "cisLockUnlocked": any[];
  "cisLocomotive": any[];
  "cisLoop1": any[];
  "cisLoopCircular": any[];
  "cisLoopSquare": any[];
  "cisLoop": any[];
  "cisLowVision": any[];
  "cisLoyalty": any[];
  "cisMagnifyingGlass": any[];
  "cisMail": any[];
  "cisMailbox": any[];
  "cisMapAlt": any[];
  "cisMap": any[];
  "cisMediaEjectCircle": any[];
  "cisMediaEjectSquare": any[];
  "cisMediaEject": any[];
  "cisMediaPauseCircle": any[];
  "cisMediaPauseSquare": any[];
  "cisMediaPause": any[];
  "cisMediaPlayCircle": any[];
  "cisMediaPlaySquare": any[];
  "cisMediaPlay": any[];
  "cisMediaRecordCircle": any[];
  "cisMediaRecordSquare": any[];
  "cisMediaRecord": any[];
  "cisMediaSkipBackwardCircle": any[];
  "cisMediaSkipBackwardSquare": any[];
  "cisMediaSkipBackward": any[];
  "cisMediaSkipForwardCircle": any[];
  "cisMediaSkipForwardSquare": any[];
  "cisMediaSkipForward": any[];
  "cisMediaStepBackwardCircle": any[];
  "cisMediaStepBackwardSquare": any[];
  "cisMediaStepBackward": any[];
  "cisMediaStepForwardCircle": any[];
  "cisMediaStepForwardSquare": any[];
  "cisMediaStepForward": any[];
  "cisMediaStopCircle": any[];
  "cisMediaStopSquare": any[];
  "cisMediaStop": any[];
  "cisMedicalCross": any[];
  "cisMeh": any[];
  "cisMemory": any[];
  "cisMenu": any[];
  "cisMicAlt": any[];
  "cisMicSettings": any[];
  "cisMicSlash": any[];
  "cisMic": any[];
  "cisMicrochip": any[];
  "cisMicrophoneAlt": any[];
  "cisMicrophoneSettings": any[];
  "cisMicrophoneSlash": any[];
  "cisMicrophone": any[];
  "cisMinusCircle": any[];
  "cisMinusSquare": any[];
  "cisMinus": any[];
  "cisMobileArrowAdd": any[];
  "cisMobileArrowRemove": any[];
  "cisMobileCheck": any[];
  "cisMobileDeveloperMode": any[];
  "cisMobileLandscape": any[];
  "cisMobileLock": any[];
  "cisMobileMinus": any[];
  "cisMobilePlus": any[];
  "cisMobilePortrait": any[];
  "cisMobileSettings": any[];
  "cisMobileSlash": any[];
  "cisMobileSms": any[];
  "cisMobileSpeaker": any[];
  "cisMobileVolume": any[];
  "cisMobileX": any[];
  "cisMobile": any[];
  "cisMoneyBillAlt": any[];
  "cisMoneyBillAlt2": any[];
  "cisMoneyBill": any[];
  "cisMoney": any[];
  "cisMonitor": any[];
  "cisMoodBad": any[];
  "cisMoodGood": any[];
  "cisMoodVeryBad": any[];
  "cisMoodVeryGood": any[];
  "cisMoon": any[];
  "cisMore": any[];
  "cisMotorbike": any[];
  "cisMouseAlt": any[];
  "cisMouse": any[];
  "cisMouthSlash": any[];
  "cisMouth": any[];
  "cisMoveHorizontal": any[];
  "cisMoveVertical": any[];
  "cisMove": any[];
  "cisMovieAlt": any[];
  "cisMovie": any[];
  "cisMugTea": any[];
  "cisMug": any[];
  "cisMusicNoteAlt": any[];
  "cisMusicNoteSlash": any[];
  "cisMusicNote": any[];
  "cisMusicVideo": any[];
  "cisNetworkCheck": any[];
  "cisNewReleases": any[];
  "cisNew": any[];
  "cisNewspaper": any[];
  "cisNoteAdd": any[];
  "cisNote": any[];
  "cisNotes": any[];
  "cisObjectGroup": any[];
  "cisObjectUngroup": any[];
  "cisOpacity": any[];
  "cisOpentype": any[];
  "cisOptionsAlt": any[];
  "cisOptions": any[];
  "cisOven": any[];
  "cisOverscanSettings": any[];
  "cisOverscan": any[];
  "cisPageRestore": any[];
  "cisPage": any[];
  "cisPageview": any[];
  "cisPaintBucket": any[];
  "cisPaint": any[];
  "cisPaperPlane": any[];
  "cisPaperclip": any[];
  "cisParagraph": any[];
  "cisParking": any[];
  "cisPaw": any[];
  "cisPenAlt": any[];
  "cisPenFancy": any[];
  "cisPenNib": any[];
  "cisPen": any[];
  "cisPencil": any[];
  "cisPeopleMinus": any[];
  "cisPeoplePlus": any[];
  "cisPeopleX": any[];
  "cisPeople": any[];
  "cisPercent": any[];
  "cisPersonFemale": any[];
  "cisPerson": any[];
  "cisPetrolStation": any[];
  "cisPhoneBluetooth": any[];
  "cisPhoneCallEnd": any[];
  "cisPhoneCall": any[];
  "cisPhoneCallback": any[];
  "cisPhoneCheck": any[];
  "cisPhoneForward": any[];
  "cisPhoneInTalk": any[];
  "cisPhoneLock": any[];
  "cisPhoneMinus": any[];
  "cisPhoneMissed": any[];
  "cisPhonePaused": any[];
  "cisPhonePlus": any[];
  "cisPhoneRingVolume": any[];
  "cisPhoneSettings": any[];
  "cisPhoneSlash": any[];
  "cisPhoneSquare": any[];
  "cisPhoneVolume": any[];
  "cisPhoneX": any[];
  "cisPhone": any[];
  "cisPictureInPictureAlt": any[];
  "cisPictureInPicture": any[];
  "cisPin": any[];
  "cisPizza": any[];
  "cisPlant": any[];
  "cisPlaylistAddCheck": any[];
  "cisPlaylistAdd": any[];
  "cisPlaylistPlay": any[];
  "cisPlusCircle": any[];
  "cisPlusOne": any[];
  "cisPlusSquare": any[];
  "cisPlus": any[];
  "cisPool": any[];
  "cisPortableWifiOff": any[];
  "cisPortableWifi": any[];
  "cisPowerSettings": any[];
  "cisPowerStandby": any[];
  "cisPregnant": any[];
  "cisPrint": any[];
  "cisPrinterSlash": any[];
  "cisPrinter": any[];
  "cisPushchair": any[];
  "cisPuzzlePiece": any[];
  "cisPuzzle": any[];
  "cisQrCode": any[];
  "cisQueueAdd": any[];
  "cisQueueMusic": any[];
  "cisQueuePlayNext": any[];
  "cisQueueRemove": any[];
  "cisQueue": any[];
  "cisRadio": any[];
  "cisRailway": any[];
  "cisRain": any[];
  "cisRandom": any[];
  "cisRecentActors": any[];
  "cisRectangle": any[];
  "cisRecycle": any[];
  "cisRegistered": any[];
  "cisReload": any[];
  "cisRemoteControl": any[];
  "cisRemoteSettings": any[];
  "cisReplay": any[];
  "cisReportSlash": any[];
  "cisReport": any[];
  "cisResizeBoth": any[];
  "cisResizeHeight": any[];
  "cisResizeWidth": any[];
  "cisRestaurantMenu": any[];
  "cisRestaurant": any[];
  "cisRestore": any[];
  "cisRights": any[];
  "cisRoomSlash": any[];
  "cisRoom": any[];
  "cisRotateLeft": any[];
  "cisRotateRight": any[];
  "cisRoundedCorner": any[];
  "cisRouter": any[];
  "cisRowing": any[];
  "cisRssAlt": any[];
  "cisRssSquare": any[];
  "cisRss": any[];
  "cisRubleCircleSlash": any[];
  "cisRubleCircle": any[];
  "cisRubleSlash": any[];
  "cisRuble": any[];
  "cisRunning": any[];
  "cisSad": any[];
  "cisSatelite": any[];
  "cisSave": any[];
  "cisScaleImage": any[];
  "cisScale": any[];
  "cisScanner": any[];
  "cisSchool": any[];
  "cisScooter": any[];
  "cisScreenDeskopSlash": any[];
  "cisScreenDesktop": any[];
  "cisScreenHorizontal": any[];
  "cisScreenLandscape": any[];
  "cisScreenLockHorizontal": any[];
  "cisScreenLockLandscape": any[];
  "cisScreenLockPortrait": any[];
  "cisScreenLockRotation": any[];
  "cisScreenLockVertical": any[];
  "cisScreenMirroring": any[];
  "cisScreenPortrait": any[];
  "cisScreenRotation": any[];
  "cisScreenSmartphone": any[];
  "cisScreenVertical": any[];
  "cisScript": any[];
  "cisScrubber": any[];
  "cisSdcard": any[];
  "cisSearch": any[];
  "cisSecurity": any[];
  "cisSelectAll": any[];
  "cisSelect": any[];
  "cisSend": any[];
  "cisSettingsAlt": any[];
  "cisSettings": any[];
  "cisShareAll": any[];
  "cisShareAlt": any[];
  "cisShareBoxed": any[];
  "cisShare": any[];
  "cisShieldAlt": any[];
  "cisShieldCheck": any[];
  "cisShieldMinus": any[];
  "cisShieldPlus": any[];
  "cisShieldSlash": any[];
  "cisShieldX": any[];
  "cisShield": any[];
  "cisShopMediaTwo": any[];
  "cisShopMedia": any[];
  "cisShortText": any[];
  "cisShower": any[];
  "cisSignLanguage": any[];
  "cisSignalCellular0": any[];
  "cisSignalCellular1": any[];
  "cisSignalCellular2": any[];
  "cisSignalCellular3": any[];
  "cisSignalCellular4": any[];
  "cisSignalCellularNoInternet0": any[];
  "cisSignalCellularNoInternet1": any[];
  "cisSignalCellularNoInternet2": any[];
  "cisSignalCellularNoInternet3": any[];
  "cisSignalCellularNoInternet4": any[];
  "cisSignalCellularOff": any[];
  "cisSignalCellularOff_1": any[];
  "cisSignal": any[];
  "cisSignpost": any[];
  "cisSimSlash": any[];
  "cisSim": any[];
  "cisSitemap": any[];
  "cisSlowMotion": any[];
  "cisSmilePlus": any[];
  "cisSmile": any[];
  "cisSmokeFree": any[];
  "cisSmokeSlash": any[];
  "cisSmoke": any[];
  "cisSmokingRoom": any[];
  "cisSnow": any[];
  "cisSnowflake": any[];
  "cisSoccer": any[];
  "cisSofa": any[];
  "cisSorroundSound": any[];
  "cisSortAlphaDown": any[];
  "cisSortAlphaUp": any[];
  "cisSortAscending": any[];
  "cisSortDescending": any[];
  "cisSortNumericDown": any[];
  "cisSortNumericUp": any[];
  "cisSound": any[];
  "cisSpa": any[];
  "cisSpaceBar": any[];
  "cisSpeak": any[];
  "cisSpeakerGroup": any[];
  "cisSpeaker": any[];
  "cisSpeechBubble": any[];
  "cisSpeechNotesSlash": any[];
  "cisSpeechNotes": any[];
  "cisSpeech": any[];
  "cisSpeedometer": any[];
  "cisSpreadsheet": any[];
  "cisSquare": any[];
  "cisStarCircle": any[];
  "cisStarHalf": any[];
  "cisStar": any[];
  "cisStickyNote": any[];
  "cisStorage": any[];
  "cisStore": any[];
  "cisStream": any[];
  "cisStrikethrough": any[];
  "cisSubtitles": any[];
  "cisSubway": any[];
  "cisSun": any[];
  "cisSwapHorizontalCircle": any[];
  "cisSwapHorizontal": any[];
  "cisSwapVerticalCircle": any[];
  "cisSwapVertical": any[];
  "cisSwimming": any[];
  "cisSyncDisabled": any[];
  "cisSyncProblem": any[];
  "cisSync": any[];
  "cisTablet": any[];
  "cisTag": any[];
  "cisTags": any[];
  "cisTarget": any[];
  "cisTask": any[];
  "cisTaxi": any[];
  "cisTemperatureAlt": any[];
  "cisTemperatureHigh": any[];
  "cisTemperatureLow": any[];
  "cisTemperature": any[];
  "cisTennisBall": any[];
  "cisTennis": any[];
  "cisTerminal": any[];
  "cisTerrain": any[];
  "cisTextDirectionLtr": any[];
  "cisTextDirectionRtl": any[];
  "cisTextFormatClear": any[];
  "cisTextHeight": any[];
  "cisTextRotateVertical": any[];
  "cisTextRotationDown": any[];
  "cisTextRotationNone": any[];
  "cisTextRotationUp": any[];
  "cisTextShapes": any[];
  "cisTextSize": any[];
  "cisTextSquare": any[];
  "cisTextStrike": any[];
  "cisTextWidth": any[];
  "cisText": any[];
  "cisThermometerAlt": any[];
  "cisThermometer": any[];
  "cisThumbDown": any[];
  "cisThumbUp": any[];
  "cisTimeline": any[];
  "cisTimer": any[];
  "cisToggleOff": any[];
  "cisToggleOn": any[];
  "cisToilet": any[];
  "cisToll": any[];
  "cisTouchApp": any[];
  "cisTrademark": any[];
  "cisTraffic": any[];
  "cisTrainAlt": any[];
  "cisTrain": any[];
  "cisTram": any[];
  "cisTransferWithinAStation": any[];
  "cisTransfer": any[];
  "cisTranslate": any[];
  "cisTrashAlt": any[];
  "cisTrashArrowUp": any[];
  "cisTrashSweep": any[];
  "cisTrashX": any[];
  "cisTrash": any[];
  "cisTriangle": any[];
  "cisTruck": any[];
  "cisTty": any[];
  "cisTvDvr": any[];
  "cisTvLive": any[];
  "cisTvSlash": any[];
  "cisTv": any[];
  "cisUnderline": any[];
  "cisUniversalAccess": any[];
  "cisUpdate": any[];
  "cisUsb": any[];
  "cisUserFemaleFollow": any[];
  "cisUserFemaleMinus": any[];
  "cisUserFemalePlus": any[];
  "cisUserFemaleUnfollow": any[];
  "cisUserFemaleX": any[];
  "cisUserFemale": any[];
  "cisUserFollow": any[];
  "cisUserMinus": any[];
  "cisUserPlus": any[];
  "cisUserSecret": any[];
  "cisUserUnfollow": any[];
  "cisUserX": any[];
  "cisUser": any[];
  "cisVector": any[];
  "cisVericalSplit": any[];
  "cisVerticalAlignBottom": any[];
  "cisVerticalAlignCenter": any[];
  "cisVerticalAlignTop": any[];
  "cisVideoLabel": any[];
  "cisVideoLibrary": any[];
  "cisVideoMissed": any[];
  "cisVideoPlus": any[];
  "cisVideoSlash": any[];
  "cisVideoSwitch": any[];
  "cisVideo": any[];
  "cisVideogame": any[];
  "cisViewAgenda": any[];
  "cisViewArray": any[];
  "cisViewCarousel": any[];
  "cisViewColumn": any[];
  "cisViewList": any[];
  "cisViewModule": any[];
  "cisViewQuilt": any[];
  "cisViewRow": any[];
  "cisViewStream": any[];
  "cisVoiceOverRecord": any[];
  "cisVoiceOverSlash": any[];
  "cisVoice": any[];
  "cisVoicemail": any[];
  "cisVolumeHigh": any[];
  "cisVolumeLow": any[];
  "cisVolumeOff": any[];
  "cisVolume": any[];
  "cisVote": any[];
  "cisWalk": any[];
  "cisWallet": any[];
  "cisWallpaper": any[];
  "cisWarning": any[];
  "cisWatch": any[];
  "cisWaves": any[];
  "cisWc": any[];
  "cisWebcloud": any[];
  "cisWeightlifitng": any[];
  "cisWeights": any[];
  "cisWheelchair": any[];
  "cisWidgets": any[];
  "cisWifiLock": any[];
  "cisWifiSignal0": any[];
  "cisWifiSignal1": any[];
  "cisWifiSignal2": any[];
  "cisWifiSignal3": any[];
  "cisWifiSignal4": any[];
  "cisWifiSignalLock0": any[];
  "cisWifiSignalLock1": any[];
  "cisWifiSignalLock2": any[];
  "cisWifiSignalLock3": any[];
  "cisWifiSignalLock4": any[];
  "cisWifiSignalOff": any[];
  "cisWifi": any[];
  "cisWindowMaximize": any[];
  "cisWindowMinimize": any[];
  "cisWindowRestore": any[];
  "cisWindow": any[];
  "cisWrapText": any[];
  "cisXCircle": any[];
  "cisXSquare": any[];
  "cisX": any[];
  "cisYenCircleSlash": any[];
  "cisYenCircle": any[];
  "cisYenSlash": any[];
  "cisYen": any[];
  "cisZoomIn": any[];
  "cisZoomOut": any[];
  "cisZoom": any[];
}
export declare const cis3dRotate: any[];
export declare const cis3d: any[];
export declare const cis4k: any[];
export declare const cisAccessibility: any[];
export declare const cisAccessible: any[];
export declare const cisAccountLogout: any[];
export declare const cisActionRedo: any[];
export declare const cisActionUndo: any[];
export declare const cisAddressBook: any[];
export declare const cisAddressCard: any[];
export declare const cisAirplaneModeOff: any[];
export declare const cisAirplaneMode: any[];
export declare const cisAirplay: any[];
export declare const cisAlarmAdd: any[];
export declare const cisAlarmOff: any[];
export declare const cisAlarmOn: any[];
export declare const cisAlarmSnooze: any[];
export declare const cisAlarm: any[];
export declare const cisAlbum: any[];
export declare const cisAlignCenter: any[];
export declare const cisAlignLeft: any[];
export declare const cisAlignRight: any[];
export declare const cisAmericanFootball: any[];
export declare const cisAnimal: any[];
export declare const cisAperture: any[];
export declare const cisApple: any[];
export declare const cisApplicationsSettings: any[];
export declare const cisApplications: any[];
export declare const cisAppsSettings: any[];
export declare const cisApps: any[];
export declare const cisArchive: any[];
export declare const cisArrowBottom: any[];
export declare const cisArrowCircleBottom: any[];
export declare const cisArrowCircleLeft: any[];
export declare const cisArrowCircleRight: any[];
export declare const cisArrowCircleTop: any[];
export declare const cisArrowLeft: any[];
export declare const cisArrowRight: any[];
export declare const cisArrowThickBottom: any[];
export declare const cisArrowThickCircleDown: any[];
export declare const cisArrowThickCircleLeft: any[];
export declare const cisArrowThickCircleRight: any[];
export declare const cisArrowThickCircleUp: any[];
export declare const cisArrowThickFromBottom: any[];
export declare const cisArrowThickFromLeft: any[];
export declare const cisArrowThickFromRight: any[];
export declare const cisArrowThickFromTop: any[];
export declare const cisArrowThickLeft: any[];
export declare const cisArrowThickRight: any[];
export declare const cisArrowThickSquareDown: any[];
export declare const cisArrowThickSquareLeft: any[];
export declare const cisArrowThickSquareRight: any[];
export declare const cisArrowThickSquareUp: any[];
export declare const cisArrowThickToBottom: any[];
export declare const cisArrowThickToLeft: any[];
export declare const cisArrowThickToRight: any[];
export declare const cisArrowThickToTop: any[];
export declare const cisArrowThickTop: any[];
export declare const cisArrowTop: any[];
export declare const cisArtTrack: any[];
export declare const cisAspectRatio: any[];
export declare const cisAssistiveListeningSystem: any[];
export declare const cisAsteriskCircle: any[];
export declare const cisAsterisk: any[];
export declare const cisAt: any[];
export declare const cisAudioDescription: any[];
export declare const cisAudioSpectrum: any[];
export declare const cisAudio: any[];
export declare const cisAvTimer: any[];
export declare const cisBabyCarriage: any[];
export declare const cisBaby: any[];
export declare const cisBackspace: any[];
export declare const cisBadge: any[];
export declare const cisBalanceScaleLeft: any[];
export declare const cisBalanceScaleRight: any[];
export declare const cisBalanceScale: any[];
export declare const cisBan: any[];
export declare const cisBank: any[];
export declare const cisBarChart: any[];
export declare const cisBarcode: any[];
export declare const cisBaseball: any[];
export declare const cisBasketArrowDown: any[];
export declare const cisBasketLoaded: any[];
export declare const cisBasketPlus: any[];
export declare const cisBasket: any[];
export declare const cisBasketball: any[];
export declare const cisBath: any[];
export declare const cisBathroom: any[];
export declare const cisBattery0: any[];
export declare const cisBattery1: any[];
export declare const cisBattery2: any[];
export declare const cisBattery3: any[];
export declare const cisBattery4: any[];
export declare const cisBattery5: any[];
export declare const cisBatteryAlert: any[];
export declare const cisBatteryAlt0: any[];
export declare const cisBatteryAlt1: any[];
export declare const cisBatteryAlt2: any[];
export declare const cisBatteryAlt3: any[];
export declare const cisBatteryAltEmpty: any[];
export declare const cisBatteryAltFull: any[];
export declare const cisBatteryAltSlash: any[];
export declare const cisBatteryCharge: any[];
export declare const cisBatteryEmpty: any[];
export declare const cisBatteryFull: any[];
export declare const cisBatterySlash: any[];
export declare const cisBatteryUnknown: any[];
export declare const cisBeachAccess: any[];
export declare const cisBeaker: any[];
export declare const cisBed: any[];
export declare const cisBellExclamation: any[];
export declare const cisBellPlus: any[];
export declare const cisBellRing: any[];
export declare const cisBellSlash: any[];
export declare const cisBell: any[];
export declare const cisBikeAlt: any[];
export declare const cisBike: any[];
export declare const cisBirthdayCake: any[];
export declare const cisBlind: any[];
export declare const cisBluetoothConnected: any[];
export declare const cisBluetoothSearching: any[];
export declare const cisBluetoothSettings: any[];
export declare const cisBluetoothSlash: any[];
export declare const cisBluetooth: any[];
export declare const cisBlurCircular: any[];
export declare const cisBlurLinear: any[];
export declare const cisBlurSlash: any[];
export declare const cisBlur: any[];
export declare const cisBoatAlt: any[];
export declare const cisBoat: any[];
export declare const cisBold: any[];
export declare const cisBoltAlt: any[];
export declare const cisBoltCircle: any[];
export declare const cisBolt: any[];
export declare const cisBookOpen: any[];
export declare const cisBook: any[];
export declare const cisBookmark: any[];
export declare const cisBookmarks: any[];
export declare const cisBorderAll: any[];
export declare const cisBorderBottom: any[];
export declare const cisBorderClear: any[];
export declare const cisBorderHorizontal: any[];
export declare const cisBorderInner: any[];
export declare const cisBorderLeft: any[];
export declare const cisBorderOuter: any[];
export declare const cisBorderRight: any[];
export declare const cisBorderStyle: any[];
export declare const cisBorderTop: any[];
export declare const cisBorderVertical: any[];
export declare const cisBowlingPins: any[];
export declare const cisBowling: any[];
export declare const cisBoxAlt: any[];
export declare const cisBox: any[];
export declare const cisBraille: any[];
export declare const cisBrandingWatermark: any[];
export declare const cisBriefcaseArrowLeft: any[];
export declare const cisBriefcaseArrowRight: any[];
export declare const cisBriefcaseSlash: any[];
export declare const cisBriefcase: any[];
export declare const cisBrightnessAuto: any[];
export declare const cisBrightnessHigh: any[];
export declare const cisBrightnessLow: any[];
export declare const cisBrightnessMedium: any[];
export declare const cisBrightness: any[];
export declare const cisBritishPoundCircle: any[];
export declare const cisBritishPoundSlash: any[];
export declare const cisBritishPound: any[];
export declare const cisBroadcastTower: any[];
export declare const cisBrowser: any[];
export declare const cisBrushAlt: any[];
export declare const cisBrush: any[];
export declare const cisBug: any[];
export declare const cisBuildingBusinessSlash: any[];
export declare const cisBuildingBusiness: any[];
export declare const cisBuildingSlash: any[];
export declare const cisBuilding: any[];
export declare const cisBullhorn: any[];
export declare const cisBurger: any[];
export declare const cisBurn: any[];
export declare const cisBusAlt: any[];
export declare const cisBusTimer: any[];
export declare const cisBus: any[];
export declare const cisCalculator: any[];
export declare const cisCalendarAlt: any[];
export declare const cisCalendarCheck: any[];
export declare const cisCalendarEvent: any[];
export declare const cisCalendarMinus: any[];
export declare const cisCalendarNote: any[];
export declare const cisCalendarPlus: any[];
export declare const cisCalendarTimes: any[];
export declare const cisCalendarToday: any[];
export declare const cisCalendarViewDay: any[];
export declare const cisCalendar: any[];
export declare const cisCallMade: any[];
export declare const cisCallMerge: any[];
export declare const cisCallMissedOutgoing: any[];
export declare const cisCallMissed: any[];
export declare const cisCallReceived: any[];
export declare const cisCallSplit: any[];
export declare const cisCallSwapCalls: any[];
export declare const cisCallToAction: any[];
export declare const cisCameraControl: any[];
export declare const cisCameraEnhance: any[];
export declare const cisCameraPlus: any[];
export declare const cisCameraRoll: any[];
export declare const cisCameraSwitch: any[];
export declare const cisCamera: any[];
export declare const cisCarAlt: any[];
export declare const cisCar: any[];
export declare const cisCardGiftcard: any[];
export declare const cisCardMembership: any[];
export declare const cisCardTravel: any[];
export declare const cisCaretBottom: any[];
export declare const cisCaretLeft: any[];
export declare const cisCaretRight: any[];
export declare const cisCaretTop: any[];
export declare const cisCartArrowDown: any[];
export declare const cisCartLoaded: any[];
export declare const cisCartPlus: any[];
export declare const cisCartSlash: any[];
export declare const cisCart: any[];
export declare const cisCash: any[];
export declare const cisCasino: any[];
export declare const cisCastConnected: any[];
export declare const cisCastForEducation: any[];
export declare const cisCast: any[];
export declare const cisCat: any[];
export declare const cisCc: any[];
export declare const cisCenterFocusWeak: any[];
export declare const cisCenterFocus: any[];
export declare const cisChalkboardTeacher: any[];
export declare const cisChartArea: any[];
export declare const cisChartBubble: any[];
export declare const cisChartDonut: any[];
export declare const cisChartLine: any[];
export declare const cisChartMultiline: any[];
export declare const cisChartPie: any[];
export declare const cisChartShow: any[];
export declare const cisChartTable: any[];
export declare const cisChart: any[];
export declare const cisChatBubble: any[];
export declare const cisChatSquare: any[];
export declare const cisCheckAlt: any[];
export declare const cisCheckCircle: any[];
export declare const cisCheckDoubleAlt: any[];
export declare const cisCheckDouble: any[];
export declare const cisCheck: any[];
export declare const cisChevronBottomAlt: any[];
export declare const cisChevronBottom: any[];
export declare const cisChevronCircleDownAlt: any[];
export declare const cisChevronCircleDown: any[];
export declare const cisChevronCircleLeftAlt: any[];
export declare const cisChevronCircleLeft: any[];
export declare const cisChevronCircleRightAlt: any[];
export declare const cisChevronCircleRight: any[];
export declare const cisChevronCircleUpAlt: any[];
export declare const cisChevronCircleUp: any[];
export declare const cisChevronDoubleDownAlt: any[];
export declare const cisChevronDoubleDown: any[];
export declare const cisChevronDoubleLeftAlt: any[];
export declare const cisChevronDoubleLeft: any[];
export declare const cisChevronDoubleRightAlt: any[];
export declare const cisChevronDoubleRight: any[];
export declare const cisChevronDoubleUpAlt: any[];
export declare const cisChevronDoubleUp: any[];
export declare const cisChevronLeftAlt: any[];
export declare const cisChevronLeft: any[];
export declare const cisChevronRightAlt: any[];
export declare const cisChevronRight: any[];
export declare const cisChevronSquareDownAlt: any[];
export declare const cisChevronSquareDown: any[];
export declare const cisChevronSquareLeftAlt: any[];
export declare const cisChevronSquareLeft: any[];
export declare const cisChevronSquareRightAlt: any[];
export declare const cisChevronSquareRight: any[];
export declare const cisChevronSquareUpAlt: any[];
export declare const cisChevronSquareUp: any[];
export declare const cisChevronTopAlt: any[];
export declare const cisChevronTop: any[];
export declare const cisChildFriendly: any[];
export declare const cisChild: any[];
export declare const cisCircle: any[];
export declare const cisCity: any[];
export declare const cisClearAll: any[];
export declare const cisClipboard: any[];
export declare const cisClock: any[];
export declare const cisClone: any[];
export declare const cisClosedCaptioning: any[];
export declare const cisCloudCheck: any[];
export declare const cisCloudCircle: any[];
export declare const cisCloudData: any[];
export declare const cisCloudDownload: any[];
export declare const cisCloudSlash: any[];
export declare const cisCloudUpload: any[];
export declare const cisCloud: any[];
export declare const cisCloudy: any[];
export declare const cisCode: any[];
export declare const cisCoffee: any[];
export declare const cisCog: any[];
export declare const cisColorBorder: any[];
export declare const cisColorFill: any[];
export declare const cisColorPalette: any[];
export declare const cisColumns: any[];
export declare const cisCommand: any[];
export declare const cisCommentBubbleCheck: any[];
export declare const cisCommentBubbleEdit: any[];
export declare const cisCommentBubbleExclamation: any[];
export declare const cisCommentBubbleLines: any[];
export declare const cisCommentBubbleMinus: any[];
export declare const cisCommentBubblePlus: any[];
export declare const cisCommentBubbleQuestion: any[];
export declare const cisCommentBubbleSmile: any[];
export declare const cisCommentBubbleX: any[];
export declare const cisCommentBubble: any[];
export declare const cisCommentSquareCheck: any[];
export declare const cisCommentSquareEdit: any[];
export declare const cisCommentSquareExclamation: any[];
export declare const cisCommentSquareImage: any[];
export declare const cisCommentSquareLines: any[];
export declare const cisCommentSquareMinus: any[];
export declare const cisCommentSquarePlus: any[];
export declare const cisCommentSquareRateReview: any[];
export declare const cisCommentSquareSmile: any[];
export declare const cisCommentSquareX: any[];
export declare const cisCommentSquare: any[];
export declare const cisCommute: any[];
export declare const cisCompare: any[];
export declare const cisCompassCalibration: any[];
export declare const cisCompassSlash: any[];
export declare const cisCompass: any[];
export declare const cisCompressWide: any[];
export declare const cisCompress: any[];
export declare const cisContactMail: any[];
export declare const cisContactPhone: any[];
export declare const cisContact: any[];
export declare const cisContacts: any[];
export declare const cisContrast: any[];
export declare const cisControl: any[];
export declare const cisCopy: any[];
export declare const cisCopyright: any[];
export declare const cisCouch: any[];
export declare const cisCreditCard: any[];
export declare const cisCropRotate: any[];
export declare const cisCrop: any[];
export declare const cisCursorMove: any[];
export declare const cisCursor: any[];
export declare const cisCut: any[];
export declare const cisDataTransferDown: any[];
export declare const cisDataTransferUp: any[];
export declare const cisDeaf: any[];
export declare const cisDelete: any[];
export declare const cisDescription: any[];
export declare const cisDeveloperBoard: any[];
export declare const cisDeviceUnknown: any[];
export declare const cisDevicesImportant: any[];
export declare const cisDevicesOther: any[];
export declare const cisDevicesSlash: any[];
export declare const cisDevices: any[];
export declare const cisDial: any[];
export declare const cisDialpad: any[];
export declare const cisDiamond: any[];
export declare const cisDinner: any[];
export declare const cisDirections: any[];
export declare const cisDisabled: any[];
export declare const cisDns: any[];
export declare const cisDock: any[];
export declare const cisDocument: any[];
export declare const cisDog: any[];
export declare const cisDollarCircleSlash: any[];
export declare const cisDollarCircle: any[];
export declare const cisDollarSlash: any[];
export declare const cisDollar: any[];
export declare const cisDonate: any[];
export declare const cisDoor: any[];
export declare const cisDoubleQuoteSansLeft: any[];
export declare const cisDoubleQuoteSansRight: any[];
export declare const cisDoubleQuoteSerifLeft: any[];
export declare const cisDoubleQuoteSerifRight: any[];
export declare const cisDrinkAlcohol: any[];
export declare const cisDrink: any[];
export declare const cisDropSlash: any[];
export declare const cisDrop: any[];
export declare const cisDvr: any[];
export declare const cisEar: any[];
export declare const cisEco: any[];
export declare const cisEducation: any[];
export declare const cisElevator: any[];
export declare const cisEllipsis: any[];
export declare const cisEnergyCircle: any[];
export declare const cisEnergy: any[];
export declare const cisEnvelopeClosed: any[];
export declare const cisEnvelopeLetter: any[];
export declare const cisEnvelopeMinus: any[];
export declare const cisEnvelopeOpen: any[];
export declare const cisEnvelopePlus: any[];
export declare const cisEqualizer: any[];
export declare const cisEthernetAlt: any[];
export declare const cisEthernet: any[];
export declare const cisEuroCircleSlash: any[];
export declare const cisEuroCircle: any[];
export declare const cisEuroSlash: any[];
export declare const cisEuro: any[];
export declare const cisEvStation: any[];
export declare const cisExcerpt: any[];
export declare const cisExclamationCircle: any[];
export declare const cisExclamation: any[];
export declare const cisExitToApp: any[];
export declare const cisExpandDown: any[];
export declare const cisExpandLeft: any[];
export declare const cisExpandRight: any[];
export declare const cisExpandUp: any[];
export declare const cisExposure: any[];
export declare const cisExternalLink: any[];
export declare const cisEyeSlash: any[];
export declare const cisEye: any[];
export declare const cisEyedropper: any[];
export declare const cisFaceDead: any[];
export declare const cisFace: any[];
export declare const cisFactorySlash: any[];
export declare const cisFactory: any[];
export declare const cisFastfood: any[];
export declare const cisFax: any[];
export declare const cisFeaturedPlaylist: any[];
export declare const cisFeaturedVideo: any[];
export declare const cisFiberDvr: any[];
export declare const cisFiberManual: any[];
export declare const cisFiberNew: any[];
export declare const cisFiberPin: any[];
export declare const cisFiberSmart: any[];
export declare const cisFileAcrobat: any[];
export declare const cisFileAdd: any[];
export declare const cisFileArchive: any[];
export declare const cisFileAudio: any[];
export declare const cisFileCode: any[];
export declare const cisFileDoc: any[];
export declare const cisFileExcel: any[];
export declare const cisFileImage: any[];
export declare const cisFilePdf: any[];
export declare const cisFilePowerpoint: any[];
export declare const cisFilePpt: any[];
export declare const cisFileVideo: any[];
export declare const cisFileWord: any[];
export declare const cisFileXls: any[];
export declare const cisFile: any[];
export declare const cisFilterFrames: any[];
export declare const cisFilterPhoto: any[];
export declare const cisFilterSquare: any[];
export declare const cisFilterX: any[];
export declare const cisFilter: any[];
export declare const cisFindInPage: any[];
export declare const cisFindReplace: any[];
export declare const cisFingerprint: any[];
export declare const cisFire: any[];
export declare const cisFlagAlt: any[];
export declare const cisFlagRectangle: any[];
export declare const cisFlagTriangle: any[];
export declare const cisFlag: any[];
export declare const cisFlame: any[];
export declare const cisFlash: any[];
export declare const cisFlightLand: any[];
export declare const cisFlightTakeoff: any[];
export declare const cisFlipToBack: any[];
export declare const cisFlipToFront: any[];
export declare const cisFlip: any[];
export declare const cisFlower: any[];
export declare const cisFolderAlt: any[];
export declare const cisFolderArrowLeft: any[];
export declare const cisFolderArrowRight: any[];
export declare const cisFolderBack: any[];
export declare const cisFolderMove: any[];
export declare const cisFolderOpen: any[];
export declare const cisFolderPlus: any[];
export declare const cisFolderShared: any[];
export declare const cisFolderSpecial: any[];
export declare const cisFolder: any[];
export declare const cisFont: any[];
export declare const cisFootball: any[];
export declare const cisFork: any[];
export declare const cisFridge: any[];
export declare const cisFrown: any[];
export declare const cisFullscreenExit: any[];
export declare const cisFullscreen: any[];
export declare const cisFunctionsAlt: any[];
export declare const cisFunctions: any[];
export declare const cisGamepad: any[];
export declare const cisGarage: any[];
export declare const cisGauge: any[];
export declare const cisGem: any[];
export declare const cisGif: any[];
export declare const cisGift: any[];
export declare const cisGlass: any[];
export declare const cisGlobeAltLock: any[];
export declare const cisGlobeAlt: any[];
export declare const cisGlobeLock: any[];
export declare const cisGlobe: any[];
export declare const cisGolfAlt: any[];
export declare const cisGolf: any[];
export declare const cisGradient: any[];
export declare const cisGrain: any[];
export declare const cisGraph: any[];
export declare const cisGridSlash: any[];
export declare const cisGrid: any[];
export declare const cisGripDotsHorizontal: any[];
export declare const cisGripDotsVertical: any[];
export declare const cisGripDots: any[];
export declare const cisGripHorizontal: any[];
export declare const cisGripLinesHorizontal: any[];
export declare const cisGripLinesVertical: any[];
export declare const cisGripLines: any[];
export declare const cisGripVertical: any[];
export declare const cisGrip: any[];
export declare const cisGroupMinus: any[];
export declare const cisGroupPlus: any[];
export declare const cisGroupX: any[];
export declare const cisGroup: any[];
export declare const cisHamburgerMenu: any[];
export declare const cisHandLizard: any[];
export declare const cisHandPaper: any[];
export declare const cisHandPeace: any[];
export declare const cisHandPointDown: any[];
export declare const cisHandPointLeft: any[];
export declare const cisHandPointRight: any[];
export declare const cisHandPointUp: any[];
export declare const cisHandPointer: any[];
export declare const cisHandRock: any[];
export declare const cisHandScissors: any[];
export declare const cisHandSpock: any[];
export declare const cisHandshake: any[];
export declare const cisHappy: any[];
export declare const cisHardDrive: any[];
export declare const cisHd: any[];
export declare const cisHdrSlash: any[];
export declare const cisHdr: any[];
export declare const cisHeader: any[];
export declare const cisHeadphonesMic: any[];
export declare const cisHeadphonesMute: any[];
export declare const cisHeadphones: any[];
export declare const cisHealing: any[];
export declare const cisHeart: any[];
export declare const cisHighQuality: any[];
export declare const cisHighlighter: any[];
export declare const cisHighligt: any[];
export declare const cisHistory: any[];
export declare const cisHome: any[];
export declare const cisHospital: any[];
export declare const cisHotTub: any[];
export declare const cisHotel: any[];
export declare const cisHourglass: any[];
export declare const cisHouse: any[];
export declare const cisHq: any[];
export declare const cisHttp: any[];
export declare const cisHttps: any[];
export declare const cisIdBadge: any[];
export declare const cisIdCard: any[];
export declare const cisImageBroken: any[];
export declare const cisImagePlus: any[];
export declare const cisImage: any[];
export declare const cisImages: any[];
export declare const cisInboxIn: any[];
export declare const cisInboxOut: any[];
export declare const cisInbox: any[];
export declare const cisIndentDecrease: any[];
export declare const cisIndentIncrease: any[];
export declare const cisIndustrySlash: any[];
export declare const cisIndustry: any[];
export declare const cisInfinity: any[];
export declare const cisInfoCircle: any[];
export declare const cisInfo: any[];
export declare const cisInputAntenna: any[];
export declare const cisInputComponent: any[];
export declare const cisInputHdmi: any[];
export declare const cisInputPowerOff: any[];
export declare const cisInputPower: any[];
export declare const cisInputSvideo: any[];
export declare const cisInput: any[];
export declare const cisInstitution: any[];
export declare const cisInvert: any[];
export declare const cisItalic: any[];
export declare const cisJustifyCenter: any[];
export declare const cisJustifyLeft: any[];
export declare const cisJustifyRight: any[];
export declare const cisKeyAlt: any[];
export declare const cisKey: any[];
export declare const cisKeyboardHide: any[];
export declare const cisKeyboard: any[];
export declare const cisKitchen: any[];
export declare const cisLan: any[];
export declare const cisLanguage: any[];
export declare const cisLaptop: any[];
export declare const cisLaundry: any[];
export declare const cisLayersSlash: any[];
export declare const cisLayers: any[];
export declare const cisLeaf: any[];
export declare const cisLemon: any[];
export declare const cisLevelDown: any[];
export declare const cisLevelUp: any[];
export declare const cisLibraryAdd: any[];
export declare const cisLibraryBookmark: any[];
export declare const cisLibraryBooks: any[];
export declare const cisLibraryBuilding: any[];
export declare const cisLibraryMusic: any[];
export declare const cisLibrary: any[];
export declare const cisLifeRing: any[];
export declare const cisLightbulb: any[];
export declare const cisLineSpacing: any[];
export declare const cisLineStyle: any[];
export declare const cisLineWeight: any[];
export declare const cisLinkAlt: any[];
export declare const cisLinkBroken: any[];
export declare const cisLinkIntact: any[];
export declare const cisLinkSlash: any[];
export declare const cisLink: any[];
export declare const cisListFilter: any[];
export declare const cisListHighPriority: any[];
export declare const cisListLowPriority: any[];
export declare const cisListNumberedRtl: any[];
export declare const cisListNumbered: any[];
export declare const cisListRich: any[];
export declare const cisList: any[];
export declare const cisLocationGpsFixed: any[];
export declare const cisLocationGpsOff: any[];
export declare const cisLocationGps: any[];
export declare const cisLocationPinCheck: any[];
export declare const cisLocationPinEdit: any[];
export declare const cisLocationPinPlus: any[];
export declare const cisLocationPinSlash: any[];
export declare const cisLocationPin: any[];
export declare const cisLockLocked: any[];
export declare const cisLockMinus: any[];
export declare const cisLockPlus: any[];
export declare const cisLockUnlocked: any[];
export declare const cisLocomotive: any[];
export declare const cisLoop1: any[];
export declare const cisLoopCircular: any[];
export declare const cisLoopSquare: any[];
export declare const cisLoop: any[];
export declare const cisLowVision: any[];
export declare const cisLoyalty: any[];
export declare const cisMagnifyingGlass: any[];
export declare const cisMail: any[];
export declare const cisMailbox: any[];
export declare const cisMapAlt: any[];
export declare const cisMap: any[];
export declare const cisMediaEjectCircle: any[];
export declare const cisMediaEjectSquare: any[];
export declare const cisMediaEject: any[];
export declare const cisMediaPauseCircle: any[];
export declare const cisMediaPauseSquare: any[];
export declare const cisMediaPause: any[];
export declare const cisMediaPlayCircle: any[];
export declare const cisMediaPlaySquare: any[];
export declare const cisMediaPlay: any[];
export declare const cisMediaRecordCircle: any[];
export declare const cisMediaRecordSquare: any[];
export declare const cisMediaRecord: any[];
export declare const cisMediaSkipBackwardCircle: any[];
export declare const cisMediaSkipBackwardSquare: any[];
export declare const cisMediaSkipBackward: any[];
export declare const cisMediaSkipForwardCircle: any[];
export declare const cisMediaSkipForwardSquare: any[];
export declare const cisMediaSkipForward: any[];
export declare const cisMediaStepBackwardCircle: any[];
export declare const cisMediaStepBackwardSquare: any[];
export declare const cisMediaStepBackward: any[];
export declare const cisMediaStepForwardCircle: any[];
export declare const cisMediaStepForwardSquare: any[];
export declare const cisMediaStepForward: any[];
export declare const cisMediaStopCircle: any[];
export declare const cisMediaStopSquare: any[];
export declare const cisMediaStop: any[];
export declare const cisMedicalCross: any[];
export declare const cisMeh: any[];
export declare const cisMemory: any[];
export declare const cisMenu: any[];
export declare const cisMicAlt: any[];
export declare const cisMicSettings: any[];
export declare const cisMicSlash: any[];
export declare const cisMic: any[];
export declare const cisMicrochip: any[];
export declare const cisMicrophoneAlt: any[];
export declare const cisMicrophoneSettings: any[];
export declare const cisMicrophoneSlash: any[];
export declare const cisMicrophone: any[];
export declare const cisMinusCircle: any[];
export declare const cisMinusSquare: any[];
export declare const cisMinus: any[];
export declare const cisMobileArrowAdd: any[];
export declare const cisMobileArrowRemove: any[];
export declare const cisMobileCheck: any[];
export declare const cisMobileDeveloperMode: any[];
export declare const cisMobileLandscape: any[];
export declare const cisMobileLock: any[];
export declare const cisMobileMinus: any[];
export declare const cisMobilePlus: any[];
export declare const cisMobilePortrait: any[];
export declare const cisMobileSettings: any[];
export declare const cisMobileSlash: any[];
export declare const cisMobileSms: any[];
export declare const cisMobileSpeaker: any[];
export declare const cisMobileVolume: any[];
export declare const cisMobileX: any[];
export declare const cisMobile: any[];
export declare const cisMoneyBillAlt: any[];
export declare const cisMoneyBillAlt2: any[];
export declare const cisMoneyBill: any[];
export declare const cisMoney: any[];
export declare const cisMonitor: any[];
export declare const cisMoodBad: any[];
export declare const cisMoodGood: any[];
export declare const cisMoodVeryBad: any[];
export declare const cisMoodVeryGood: any[];
export declare const cisMoon: any[];
export declare const cisMore: any[];
export declare const cisMotorbike: any[];
export declare const cisMouseAlt: any[];
export declare const cisMouse: any[];
export declare const cisMouthSlash: any[];
export declare const cisMouth: any[];
export declare const cisMoveHorizontal: any[];
export declare const cisMoveVertical: any[];
export declare const cisMove: any[];
export declare const cisMovieAlt: any[];
export declare const cisMovie: any[];
export declare const cisMugTea: any[];
export declare const cisMug: any[];
export declare const cisMusicNoteAlt: any[];
export declare const cisMusicNoteSlash: any[];
export declare const cisMusicNote: any[];
export declare const cisMusicVideo: any[];
export declare const cisNetworkCheck: any[];
export declare const cisNewReleases: any[];
export declare const cisNew: any[];
export declare const cisNewspaper: any[];
export declare const cisNoteAdd: any[];
export declare const cisNote: any[];
export declare const cisNotes: any[];
export declare const cisObjectGroup: any[];
export declare const cisObjectUngroup: any[];
export declare const cisOpacity: any[];
export declare const cisOpentype: any[];
export declare const cisOptionsAlt: any[];
export declare const cisOptions: any[];
export declare const cisOven: any[];
export declare const cisOverscanSettings: any[];
export declare const cisOverscan: any[];
export declare const cisPageRestore: any[];
export declare const cisPage: any[];
export declare const cisPageview: any[];
export declare const cisPaintBucket: any[];
export declare const cisPaint: any[];
export declare const cisPaperPlane: any[];
export declare const cisPaperclip: any[];
export declare const cisParagraph: any[];
export declare const cisParking: any[];
export declare const cisPaw: any[];
export declare const cisPenAlt: any[];
export declare const cisPenFancy: any[];
export declare const cisPenNib: any[];
export declare const cisPen: any[];
export declare const cisPencil: any[];
export declare const cisPeopleMinus: any[];
export declare const cisPeoplePlus: any[];
export declare const cisPeopleX: any[];
export declare const cisPeople: any[];
export declare const cisPercent: any[];
export declare const cisPersonFemale: any[];
export declare const cisPerson: any[];
export declare const cisPetrolStation: any[];
export declare const cisPhoneBluetooth: any[];
export declare const cisPhoneCallEnd: any[];
export declare const cisPhoneCall: any[];
export declare const cisPhoneCallback: any[];
export declare const cisPhoneCheck: any[];
export declare const cisPhoneForward: any[];
export declare const cisPhoneInTalk: any[];
export declare const cisPhoneLock: any[];
export declare const cisPhoneMinus: any[];
export declare const cisPhoneMissed: any[];
export declare const cisPhonePaused: any[];
export declare const cisPhonePlus: any[];
export declare const cisPhoneRingVolume: any[];
export declare const cisPhoneSettings: any[];
export declare const cisPhoneSlash: any[];
export declare const cisPhoneSquare: any[];
export declare const cisPhoneVolume: any[];
export declare const cisPhoneX: any[];
export declare const cisPhone: any[];
export declare const cisPictureInPictureAlt: any[];
export declare const cisPictureInPicture: any[];
export declare const cisPin: any[];
export declare const cisPizza: any[];
export declare const cisPlant: any[];
export declare const cisPlaylistAddCheck: any[];
export declare const cisPlaylistAdd: any[];
export declare const cisPlaylistPlay: any[];
export declare const cisPlusCircle: any[];
export declare const cisPlusOne: any[];
export declare const cisPlusSquare: any[];
export declare const cisPlus: any[];
export declare const cisPool: any[];
export declare const cisPortableWifiOff: any[];
export declare const cisPortableWifi: any[];
export declare const cisPowerSettings: any[];
export declare const cisPowerStandby: any[];
export declare const cisPregnant: any[];
export declare const cisPrint: any[];
export declare const cisPrinterSlash: any[];
export declare const cisPrinter: any[];
export declare const cisPushchair: any[];
export declare const cisPuzzlePiece: any[];
export declare const cisPuzzle: any[];
export declare const cisQrCode: any[];
export declare const cisQueueAdd: any[];
export declare const cisQueueMusic: any[];
export declare const cisQueuePlayNext: any[];
export declare const cisQueueRemove: any[];
export declare const cisQueue: any[];
export declare const cisRadio: any[];
export declare const cisRailway: any[];
export declare const cisRain: any[];
export declare const cisRandom: any[];
export declare const cisRecentActors: any[];
export declare const cisRectangle: any[];
export declare const cisRecycle: any[];
export declare const cisRegistered: any[];
export declare const cisReload: any[];
export declare const cisRemoteControl: any[];
export declare const cisRemoteSettings: any[];
export declare const cisReplay: any[];
export declare const cisReportSlash: any[];
export declare const cisReport: any[];
export declare const cisResizeBoth: any[];
export declare const cisResizeHeight: any[];
export declare const cisResizeWidth: any[];
export declare const cisRestaurantMenu: any[];
export declare const cisRestaurant: any[];
export declare const cisRestore: any[];
export declare const cisRights: any[];
export declare const cisRoomSlash: any[];
export declare const cisRoom: any[];
export declare const cisRotateLeft: any[];
export declare const cisRotateRight: any[];
export declare const cisRoundedCorner: any[];
export declare const cisRouter: any[];
export declare const cisRowing: any[];
export declare const cisRssAlt: any[];
export declare const cisRssSquare: any[];
export declare const cisRss: any[];
export declare const cisRubleCircleSlash: any[];
export declare const cisRubleCircle: any[];
export declare const cisRubleSlash: any[];
export declare const cisRuble: any[];
export declare const cisRunning: any[];
export declare const cisSad: any[];
export declare const cisSatelite: any[];
export declare const cisSave: any[];
export declare const cisScaleImage: any[];
export declare const cisScale: any[];
export declare const cisScanner: any[];
export declare const cisSchool: any[];
export declare const cisScooter: any[];
export declare const cisScreenDeskopSlash: any[];
export declare const cisScreenDesktop: any[];
export declare const cisScreenHorizontal: any[];
export declare const cisScreenLandscape: any[];
export declare const cisScreenLockHorizontal: any[];
export declare const cisScreenLockLandscape: any[];
export declare const cisScreenLockPortrait: any[];
export declare const cisScreenLockRotation: any[];
export declare const cisScreenLockVertical: any[];
export declare const cisScreenMirroring: any[];
export declare const cisScreenPortrait: any[];
export declare const cisScreenRotation: any[];
export declare const cisScreenSmartphone: any[];
export declare const cisScreenVertical: any[];
export declare const cisScript: any[];
export declare const cisScrubber: any[];
export declare const cisSdcard: any[];
export declare const cisSearch: any[];
export declare const cisSecurity: any[];
export declare const cisSelectAll: any[];
export declare const cisSelect: any[];
export declare const cisSend: any[];
export declare const cisSettingsAlt: any[];
export declare const cisSettings: any[];
export declare const cisShareAll: any[];
export declare const cisShareAlt: any[];
export declare const cisShareBoxed: any[];
export declare const cisShare: any[];
export declare const cisShieldAlt: any[];
export declare const cisShieldCheck: any[];
export declare const cisShieldMinus: any[];
export declare const cisShieldPlus: any[];
export declare const cisShieldSlash: any[];
export declare const cisShieldX: any[];
export declare const cisShield: any[];
export declare const cisShopMediaTwo: any[];
export declare const cisShopMedia: any[];
export declare const cisShortText: any[];
export declare const cisShower: any[];
export declare const cisSignLanguage: any[];
export declare const cisSignalCellular0: any[];
export declare const cisSignalCellular1: any[];
export declare const cisSignalCellular2: any[];
export declare const cisSignalCellular3: any[];
export declare const cisSignalCellular4: any[];
export declare const cisSignalCellularNoInternet0: any[];
export declare const cisSignalCellularNoInternet1: any[];
export declare const cisSignalCellularNoInternet2: any[];
export declare const cisSignalCellularNoInternet3: any[];
export declare const cisSignalCellularNoInternet4: any[];
export declare const cisSignalCellularOff: any[];
export declare const cisSignalCellularOff_1: any[];
export declare const cisSignal: any[];
export declare const cisSignpost: any[];
export declare const cisSimSlash: any[];
export declare const cisSim: any[];
export declare const cisSitemap: any[];
export declare const cisSlowMotion: any[];
export declare const cisSmilePlus: any[];
export declare const cisSmile: any[];
export declare const cisSmokeFree: any[];
export declare const cisSmokeSlash: any[];
export declare const cisSmoke: any[];
export declare const cisSmokingRoom: any[];
export declare const cisSnow: any[];
export declare const cisSnowflake: any[];
export declare const cisSoccer: any[];
export declare const cisSofa: any[];
export declare const cisSorroundSound: any[];
export declare const cisSortAlphaDown: any[];
export declare const cisSortAlphaUp: any[];
export declare const cisSortAscending: any[];
export declare const cisSortDescending: any[];
export declare const cisSortNumericDown: any[];
export declare const cisSortNumericUp: any[];
export declare const cisSound: any[];
export declare const cisSpa: any[];
export declare const cisSpaceBar: any[];
export declare const cisSpeak: any[];
export declare const cisSpeakerGroup: any[];
export declare const cisSpeaker: any[];
export declare const cisSpeechBubble: any[];
export declare const cisSpeechNotesSlash: any[];
export declare const cisSpeechNotes: any[];
export declare const cisSpeech: any[];
export declare const cisSpeedometer: any[];
export declare const cisSpreadsheet: any[];
export declare const cisSquare: any[];
export declare const cisStarCircle: any[];
export declare const cisStarHalf: any[];
export declare const cisStar: any[];
export declare const cisStickyNote: any[];
export declare const cisStorage: any[];
export declare const cisStore: any[];
export declare const cisStream: any[];
export declare const cisStrikethrough: any[];
export declare const cisSubtitles: any[];
export declare const cisSubway: any[];
export declare const cisSun: any[];
export declare const cisSwapHorizontalCircle: any[];
export declare const cisSwapHorizontal: any[];
export declare const cisSwapVerticalCircle: any[];
export declare const cisSwapVertical: any[];
export declare const cisSwimming: any[];
export declare const cisSyncDisabled: any[];
export declare const cisSyncProblem: any[];
export declare const cisSync: any[];
export declare const cisTablet: any[];
export declare const cisTag: any[];
export declare const cisTags: any[];
export declare const cisTarget: any[];
export declare const cisTask: any[];
export declare const cisTaxi: any[];
export declare const cisTemperatureAlt: any[];
export declare const cisTemperatureHigh: any[];
export declare const cisTemperatureLow: any[];
export declare const cisTemperature: any[];
export declare const cisTennisBall: any[];
export declare const cisTennis: any[];
export declare const cisTerminal: any[];
export declare const cisTerrain: any[];
export declare const cisTextDirectionLtr: any[];
export declare const cisTextDirectionRtl: any[];
export declare const cisTextFormatClear: any[];
export declare const cisTextHeight: any[];
export declare const cisTextRotateVertical: any[];
export declare const cisTextRotationDown: any[];
export declare const cisTextRotationNone: any[];
export declare const cisTextRotationUp: any[];
export declare const cisTextShapes: any[];
export declare const cisTextSize: any[];
export declare const cisTextSquare: any[];
export declare const cisTextStrike: any[];
export declare const cisTextWidth: any[];
export declare const cisText: any[];
export declare const cisThermometerAlt: any[];
export declare const cisThermometer: any[];
export declare const cisThumbDown: any[];
export declare const cisThumbUp: any[];
export declare const cisTimeline: any[];
export declare const cisTimer: any[];
export declare const cisToggleOff: any[];
export declare const cisToggleOn: any[];
export declare const cisToilet: any[];
export declare const cisToll: any[];
export declare const cisTouchApp: any[];
export declare const cisTrademark: any[];
export declare const cisTraffic: any[];
export declare const cisTrainAlt: any[];
export declare const cisTrain: any[];
export declare const cisTram: any[];
export declare const cisTransferWithinAStation: any[];
export declare const cisTransfer: any[];
export declare const cisTranslate: any[];
export declare const cisTrashAlt: any[];
export declare const cisTrashArrowUp: any[];
export declare const cisTrashSweep: any[];
export declare const cisTrashX: any[];
export declare const cisTrash: any[];
export declare const cisTriangle: any[];
export declare const cisTruck: any[];
export declare const cisTty: any[];
export declare const cisTvDvr: any[];
export declare const cisTvLive: any[];
export declare const cisTvSlash: any[];
export declare const cisTv: any[];
export declare const cisUnderline: any[];
export declare const cisUniversalAccess: any[];
export declare const cisUpdate: any[];
export declare const cisUsb: any[];
export declare const cisUserFemaleFollow: any[];
export declare const cisUserFemaleMinus: any[];
export declare const cisUserFemalePlus: any[];
export declare const cisUserFemaleUnfollow: any[];
export declare const cisUserFemaleX: any[];
export declare const cisUserFemale: any[];
export declare const cisUserFollow: any[];
export declare const cisUserMinus: any[];
export declare const cisUserPlus: any[];
export declare const cisUserSecret: any[];
export declare const cisUserUnfollow: any[];
export declare const cisUserX: any[];
export declare const cisUser: any[];
export declare const cisVector: any[];
export declare const cisVericalSplit: any[];
export declare const cisVerticalAlignBottom: any[];
export declare const cisVerticalAlignCenter: any[];
export declare const cisVerticalAlignTop: any[];
export declare const cisVideoLabel: any[];
export declare const cisVideoLibrary: any[];
export declare const cisVideoMissed: any[];
export declare const cisVideoPlus: any[];
export declare const cisVideoSlash: any[];
export declare const cisVideoSwitch: any[];
export declare const cisVideo: any[];
export declare const cisVideogame: any[];
export declare const cisViewAgenda: any[];
export declare const cisViewArray: any[];
export declare const cisViewCarousel: any[];
export declare const cisViewColumn: any[];
export declare const cisViewList: any[];
export declare const cisViewModule: any[];
export declare const cisViewQuilt: any[];
export declare const cisViewRow: any[];
export declare const cisViewStream: any[];
export declare const cisVoiceOverRecord: any[];
export declare const cisVoiceOverSlash: any[];
export declare const cisVoice: any[];
export declare const cisVoicemail: any[];
export declare const cisVolumeHigh: any[];
export declare const cisVolumeLow: any[];
export declare const cisVolumeOff: any[];
export declare const cisVolume: any[];
export declare const cisVote: any[];
export declare const cisWalk: any[];
export declare const cisWallet: any[];
export declare const cisWallpaper: any[];
export declare const cisWarning: any[];
export declare const cisWatch: any[];
export declare const cisWaves: any[];
export declare const cisWc: any[];
export declare const cisWebcloud: any[];
export declare const cisWeightlifitng: any[];
export declare const cisWeights: any[];
export declare const cisWheelchair: any[];
export declare const cisWidgets: any[];
export declare const cisWifiLock: any[];
export declare const cisWifiSignal0: any[];
export declare const cisWifiSignal1: any[];
export declare const cisWifiSignal2: any[];
export declare const cisWifiSignal3: any[];
export declare const cisWifiSignal4: any[];
export declare const cisWifiSignalLock0: any[];
export declare const cisWifiSignalLock1: any[];
export declare const cisWifiSignalLock2: any[];
export declare const cisWifiSignalLock3: any[];
export declare const cisWifiSignalLock4: any[];
export declare const cisWifiSignalOff: any[];
export declare const cisWifi: any[];
export declare const cisWindowMaximize: any[];
export declare const cisWindowMinimize: any[];
export declare const cisWindowRestore: any[];
export declare const cisWindow: any[];
export declare const cisWrapText: any[];
export declare const cisXCircle: any[];
export declare const cisXSquare: any[];
export declare const cisX: any[];
export declare const cisYenCircleSlash: any[];
export declare const cisYenCircle: any[];
export declare const cisYenSlash: any[];
export declare const cisYen: any[];
export declare const cisZoomIn: any[];
export declare const cisZoomOut: any[];
export declare const cisZoom: any[];