export declare const duotoneSet: {
  "cid3dRotate": any[];
  "cid3d": any[];
  "cid4k": any[];
  "cidAccessible": any[];
  "cidAccountLogout": any[];
  "cidActionRedo": any[];
  "cidActionUndo": any[];
  "cidAddressBook": any[];
  "cidAddressCard": any[];
  "cidAirplaneModeOff": any[];
  "cidAirplaneMode": any[];
  "cidAirplay": any[];
  "cidAlarmAdd": any[];
  "cidAlarmOff": any[];
  "cidAlarmOn": any[];
  "cidAlarmSnooze": any[];
  "cidAlarm": any[];
  "cidAlbum": any[];
  "cidAlignCenter": any[];
  "cidAlignLeft": any[];
  "cidAlignRight": any[];
  "cidAmericanFootball": any[];
  "cidAnimal": any[];
  "cidAperture": any[];
  "cidApple": any[];
  "cidApplicationsSettings": any[];
  "cidApplications": any[];
  "cidAppsSettings": any[];
  "cidApps": any[];
  "cidArchive": any[];
  "cidArrowCircleBottom": any[];
  "cidArrowCircleLeft": any[];
  "cidArrowCircleRight": any[];
  "cidArrowCircleTop": any[];
  "cidArrowThickCircleDown": any[];
  "cidArrowThickCircleLeft": any[];
  "cidArrowThickCircleRight": any[];
  "cidArrowThickCircleUp": any[];
  "cidArrowThickFromBottom": any[];
  "cidArrowThickFromLeft": any[];
  "cidArrowThickFromRight": any[];
  "cidArrowThickFromTop": any[];
  "cidArrowThickSquareDown": any[];
  "cidArrowThickSquareLeft": any[];
  "cidArrowThickSquareRight": any[];
  "cidArrowThickSquareUp": any[];
  "cidArrowThickToBottom": any[];
  "cidArrowThickToLeft": any[];
  "cidArrowThickToRight": any[];
  "cidArrowThickToTop": any[];
  "cidArtTrack": any[];
  "cidAspectRatio": any[];
  "cidAssistiveListeningSystem": any[];
  "cidAsteriskCircle": any[];
  "cidAt": any[];
  "cidAudioDescription": any[];
  "cidAudioSpectrum": any[];
  "cidAudio": any[];
  "cidAvTimer": any[];
  "cidBabyCarriage": any[];
  "cidBaby": any[];
  "cidBackspace": any[];
  "cidBadge": any[];
  "cidBalanceScaleLeft": any[];
  "cidBalanceScaleRight": any[];
  "cidBalanceScale": any[];
  "cidBan": any[];
  "cidBank": any[];
  "cidBarChart": any[];
  "cidBarcode": any[];
  "cidBaseball": any[];
  "cidBasketArrowDown": any[];
  "cidBasketLoaded": any[];
  "cidBasketPlus": any[];
  "cidBasket": any[];
  "cidBasketball": any[];
  "cidBath": any[];
  "cidBathroom": any[];
  "cidBattery0": any[];
  "cidBattery1": any[];
  "cidBattery2": any[];
  "cidBattery3": any[];
  "cidBattery4": any[];
  "cidBattery5": any[];
  "cidBatteryAlert": any[];
  "cidBatteryAlt0": any[];
  "cidBatteryAlt1": any[];
  "cidBatteryAlt2": any[];
  "cidBatteryAlt3": any[];
  "cidBatteryAltEmpty": any[];
  "cidBatteryAltFull": any[];
  "cidBatteryAltSlash": any[];
  "cidBatteryCharge": any[];
  "cidBatteryEmpty": any[];
  "cidBatteryFull": any[];
  "cidBatterySlash": any[];
  "cidBatteryUnknown": any[];
  "cidBatteryX": any[];
  "cidBeachAccess": any[];
  "cidBeaker": any[];
  "cidBed": any[];
  "cidBellExclamation": any[];
  "cidBellPlus": any[];
  "cidBellRing": any[];
  "cidBellSlash": any[];
  "cidBell": any[];
  "cidBikeAlt": any[];
  "cidBike": any[];
  "cidBirthdayCake": any[];
  "cidBlind": any[];
  "cidBluetoothConnected": any[];
  "cidBluetoothSearching": any[];
  "cidBluetoothSettings": any[];
  "cidBluetoothSlash": any[];
  "cidBluetooth": any[];
  "cidBoatAlt": any[];
  "cidBoat": any[];
  "cidBold": any[];
  "cidBoltCircle": any[];
  "cidBookOpen": any[];
  "cidBook": any[];
  "cidBookmark": any[];
  "cidBookmarks": any[];
  "cidBorderAll": any[];
  "cidBorderBottom": any[];
  "cidBorderClear": any[];
  "cidBorderHorizontal": any[];
  "cidBorderInner": any[];
  "cidBorderLeft": any[];
  "cidBorderOuter": any[];
  "cidBorderRight": any[];
  "cidBorderStyle": any[];
  "cidBorderTop": any[];
  "cidBorderVertical": any[];
  "cidBowlingPins": any[];
  "cidBowling": any[];
  "cidBoxAlt": any[];
  "cidBox": any[];
  "cidBraille": any[];
  "cidBrandingWatermark": any[];
  "cidBriefcaseArrowLeft": any[];
  "cidBriefcaseArrowRight": any[];
  "cidBriefcaseSlash": any[];
  "cidBriefcase": any[];
  "cidBrightnessAuto": any[];
  "cidBrightnessHigh": any[];
  "cidBrightnessLow": any[];
  "cidBrightnessMedium": any[];
  "cidBrightness": any[];
  "cidBritishPoundCircle": any[];
  "cidBritishPoundSlash": any[];
  "cidBritishPound": any[];
  "cidBroadcastTower": any[];
  "cidBrowser": any[];
  "cidBrushAlt": any[];
  "cidBrush": any[];
  "cidBug": any[];
  "cidBuildingBusinessSlash": any[];
  "cidBuildingBusiness": any[];
  "cidBuildingSlash": any[];
  "cidBuilding": any[];
  "cidBullhorn": any[];
  "cidBurger": any[];
  "cidBurn": any[];
  "cidBusAlt": any[];
  "cidBusTimer": any[];
  "cidBus": any[];
  "cidCalculator": any[];
  "cidCalendarCheck": any[];
  "cidCalendarEvent": any[];
  "cidCalendarMinus": any[];
  "cidCalendarNote": any[];
  "cidCalendarPlus": any[];
  "cidCalendarTimes": any[];
  "cidCalendarToday": any[];
  "cidCalendarViewDay": any[];
  "cidCalendar": any[];
  "cidCallMade": any[];
  "cidCallMerge": any[];
  "cidCallMissedOutgoing": any[];
  "cidCallMissed": any[];
  "cidCallReceived": any[];
  "cidCallSplit": any[];
  "cidCallSwapCalls": any[];
  "cidCallToAction": any[];
  "cidCameraControl": any[];
  "cidCameraEnhance": any[];
  "cidCameraPlus": any[];
  "cidCameraRoll": any[];
  "cidCameraSwitch": any[];
  "cidCamera": any[];
  "cidCarAlt": any[];
  "cidCar": any[];
  "cidCardGiftcard": any[];
  "cidCardMembership": any[];
  "cidCardTravel": any[];
  "cidCaretBottom": any[];
  "cidCaretLeft": any[];
  "cidCaretRight": any[];
  "cidCaretTop": any[];
  "cidCartArrowDown": any[];
  "cidCartLoaded": any[];
  "cidCartPlus": any[];
  "cidCartSlash": any[];
  "cidCart": any[];
  "cidCash": any[];
  "cidCasino": any[];
  "cidCastConnected": any[];
  "cidCastForEducation": any[];
  "cidCast": any[];
  "cidCat": any[];
  "cidCc": any[];
  "cidCenterFocusWeak": any[];
  "cidCenterFocus": any[];
  "cidChalkboardTeacher": any[];
  "cidChartArea": any[];
  "cidChartBubble": any[];
  "cidChartDonut": any[];
  "cidChartLine": any[];
  "cidChartMultiline": any[];
  "cidChartPie": any[];
  "cidChartShow": any[];
  "cidChartTable": any[];
  "cidChart": any[];
  "cidChatBubble": any[];
  "cidChatSquare": any[];
  "cidCheckAlt": any[];
  "cidCheckCircle": any[];
  "cidCheckDoubleAlt": any[];
  "cidCheckDouble": any[];
  "cidCheck": any[];
  "cidChevronBottomAlt": any[];
  "cidChevronCircleDownAlt": any[];
  "cidChevronCircleDown": any[];
  "cidChevronCircleLeftAlt": any[];
  "cidChevronCircleLeft": any[];
  "cidChevronCircleRightAlt": any[];
  "cidChevronCircleRight": any[];
  "cidChevronCircleUpAlt": any[];
  "cidChevronCircleUp": any[];
  "cidChevronDoubleDownAlt": any[];
  "cidChevronDoubleDown": any[];
  "cidChevronDoubleLeftAlt": any[];
  "cidChevronDoubleLeft": any[];
  "cidChevronDoubleRightAlt": any[];
  "cidChevronDoubleRight": any[];
  "cidChevronDoubleUpAlt": any[];
  "cidChevronDoubleUp": any[];
  "cidChevronLeftAlt": any[];
  "cidChevronRightAlt": any[];
  "cidChevronSquareDownAlt": any[];
  "cidChevronSquareDown": any[];
  "cidChevronSquareLeftAlt": any[];
  "cidChevronSquareLeft": any[];
  "cidChevronSquareRightAlt": any[];
  "cidChevronSquareRight": any[];
  "cidChevronSquareUpAlt": any[];
  "cidChevronSquareUp": any[];
  "cidChevronTopAlt": any[];
  "cidChildFriendly": any[];
  "cidChild": any[];
  "cidCity": any[];
  "cidClearAll": any[];
  "cidClipboard": any[];
  "cidClock": any[];
  "cidClone": any[];
  "cidClosedCaptioning": any[];
  "cidCloudCheck": any[];
  "cidCloudCircle": any[];
  "cidCloudData": any[];
  "cidCloudDownload": any[];
  "cidCloudSlash": any[];
  "cidCloudUpload": any[];
  "cidCloudy": any[];
  "cidCode": any[];
  "cidCoffee": any[];
  "cidCog": any[];
  "cidColorBorder": any[];
  "cidColorFill": any[];
  "cidColorPalette": any[];
  "cidColumns": any[];
  "cidCommand": any[];
  "cidCommentBubbleCheck": any[];
  "cidCommentBubbleEdit": any[];
  "cidCommentBubbleExclamation": any[];
  "cidCommentBubbleLines": any[];
  "cidCommentBubbleMinus": any[];
  "cidCommentBubblePlus": any[];
  "cidCommentBubbleQuestion": any[];
  "cidCommentBubbleSmile": any[];
  "cidCommentBubbleX": any[];
  "cidCommentBubble": any[];
  "cidCommentSquareCheck": any[];
  "cidCommentSquareEdit": any[];
  "cidCommentSquareExclamation": any[];
  "cidCommentSquareImage": any[];
  "cidCommentSquareLines": any[];
  "cidCommentSquareMinus": any[];
  "cidCommentSquarePlus": any[];
  "cidCommentSquareRateReview": any[];
  "cidCommentSquareSmile": any[];
  "cidCommentSquareX": any[];
  "cidCommentSquare": any[];
  "cidCommute": any[];
  "cidCompare": any[];
  "cidCompassCalibration": any[];
  "cidCompassSlash": any[];
  "cidCompass": any[];
  "cidCompressWide": any[];
  "cidCompress": any[];
  "cidContactMail": any[];
  "cidContactPhone": any[];
  "cidContact": any[];
  "cidContacts": any[];
  "cidContrast": any[];
  "cidControl": any[];
  "cidCopy": any[];
  "cidCopyright": any[];
  "cidCouch": any[];
  "cidCreditCard": any[];
  "cidCropRotate": any[];
  "cidCrop": any[];
  "cidCursorMove": any[];
  "cidCursor": any[];
  "cidCut": any[];
  "cidDataTransferDown": any[];
  "cidDataTransferUp": any[];
  "cidDeaf": any[];
  "cidDelete": any[];
  "cidDescription": any[];
  "cidDeveloperBoard": any[];
  "cidDeviceUnknown": any[];
  "cidDevicesImportant": any[];
  "cidDevicesOther": any[];
  "cidDevicesSlash": any[];
  "cidDevices": any[];
  "cidDial": any[];
  "cidDialpad": any[];
  "cidDiamond": any[];
  "cidDinner": any[];
  "cidDirections": any[];
  "cidDisabled": any[];
  "cidDns": any[];
  "cidDock": any[];
  "cidDocument": any[];
  "cidDog": any[];
  "cidDollarCircleSlash": any[];
  "cidDollarCircle": any[];
  "cidDollarSlash": any[];
  "cidDollar": any[];
  "cidDonate": any[];
  "cidDoor": any[];
  "cidDoubleQuoteSansLeft": any[];
  "cidDoubleQuoteSansRight": any[];
  "cidDoubleQuoteSerifLeft": any[];
  "cidDoubleQuoteSerifRight": any[];
  "cidDrinkAlcohol": any[];
  "cidDrink": any[];
  "cidDropSlash": any[];
  "cidDrop": any[];
  "cidDvr": any[];
  "cidEar": any[];
  "cidEco": any[];
  "cidEducation": any[];
  "cidElevator": any[];
  "cidEllipsis": any[];
  "cidEnergyCircle": any[];
  "cidEnvelopeClosed": any[];
  "cidEnvelopeLetter": any[];
  "cidEnvelopeMinus": any[];
  "cidEnvelopeOpen": any[];
  "cidEnvelopePlus": any[];
  "cidEqualizer": any[];
  "cidEthernetAlt": any[];
  "cidEthernet": any[];
  "cidEuroCircleSlash": any[];
  "cidEuroCircle": any[];
  "cidEuroSlash": any[];
  "cidEuro": any[];
  "cidEvStation": any[];
  "cidExcerpt": any[];
  "cidExclamationCircle": any[];
  "cidExclamation": any[];
  "cidExitToApp": any[];
  "cidExpandDown": any[];
  "cidExpandLeft": any[];
  "cidExpandRight": any[];
  "cidExpandUp": any[];
  "cidExposure": any[];
  "cidExternalLink": any[];
  "cidEyeSlash": any[];
  "cidEye": any[];
  "cidEyedropper": any[];
  "cidFaceDead": any[];
  "cidFace": any[];
  "cidFactorySlash": any[];
  "cidFactory": any[];
  "cidFastfood": any[];
  "cidFax": any[];
  "cidFeaturedPlaylist": any[];
  "cidFeaturedVideo": any[];
  "cidFiberDvr": any[];
  "cidFiberManual": any[];
  "cidFiberNew": any[];
  "cidFiberPin": any[];
  "cidFiberSmart": any[];
  "cidFileAcrobat": any[];
  "cidFileAdd": any[];
  "cidFileArchive": any[];
  "cidFileAudio": any[];
  "cidFileCode": any[];
  "cidFileDoc": any[];
  "cidFileExcel": any[];
  "cidFileImage": any[];
  "cidFilePdf": any[];
  "cidFilePowerpoint": any[];
  "cidFilePpt": any[];
  "cidFileVideo": any[];
  "cidFileWord": any[];
  "cidFileXls": any[];
  "cidFile": any[];
  "cidFilterFrames": any[];
  "cidFilterPhoto": any[];
  "cidFilterSquare": any[];
  "cidFilterX": any[];
  "cidFilter": any[];
  "cidFindInPage": any[];
  "cidFindReplace": any[];
  "cidFingerprint": any[];
  "cidFire": any[];
  "cidFlagAlt": any[];
  "cidFlagRectangle": any[];
  "cidFlagTriangle": any[];
  "cidFlag": any[];
  "cidFlightLand": any[];
  "cidFlightTakeoff": any[];
  "cidFlipToBack": any[];
  "cidFlipToFront": any[];
  "cidFlip": any[];
  "cidFlower": any[];
  "cidFolderAlt": any[];
  "cidFolderArrowLeft": any[];
  "cidFolderArrowRight": any[];
  "cidFolderBack": any[];
  "cidFolderMove": any[];
  "cidFolderOpen": any[];
  "cidFolderPlus": any[];
  "cidFolderShared": any[];
  "cidFolderSpecial": any[];
  "cidFolder": any[];
  "cidFont": any[];
  "cidFootball": any[];
  "cidFork": any[];
  "cidFridge": any[];
  "cidFrown": any[];
  "cidFullscreenExit": any[];
  "cidFullscreen": any[];
  "cidFunctionsAlt": any[];
  "cidFunctions": any[];
  "cidGamepad": any[];
  "cidGarage": any[];
  "cidGauge": any[];
  "cidGem": any[];
  "cidGif": any[];
  "cidGift": any[];
  "cidGlass": any[];
  "cidGlobeAltLock": any[];
  "cidGlobeAlt": any[];
  "cidGlobeLock": any[];
  "cidGlobe": any[];
  "cidGolfAlt": any[];
  "cidGolf": any[];
  "cidGradient": any[];
  "cidGrain": any[];
  "cidGraph": any[];
  "cidGridSlash": any[];
  "cidGrid": any[];
  "cidGripDotsHorizontal": any[];
  "cidGripDotsVertical": any[];
  "cidGripDots": any[];
  "cidGripHorizontal": any[];
  "cidGripLinesHorizontal": any[];
  "cidGripLinesVertical": any[];
  "cidGripLines": any[];
  "cidGripVertical": any[];
  "cidGrip": any[];
  "cidGroupMinus": any[];
  "cidGroupPlus": any[];
  "cidGroupX": any[];
  "cidGroup": any[];
  "cidHamburgerMenu": any[];
  "cidHandPointer": any[];
  "cidHandshake": any[];
  "cidHappy": any[];
  "cidHardDrive": any[];
  "cidHd": any[];
  "cidHdrSlash": any[];
  "cidHdr": any[];
  "cidHeader": any[];
  "cidHeadphonesMic": any[];
  "cidHeadphonesMute": any[];
  "cidHeadphones": any[];
  "cidHealing": any[];
  "cidHighQuality": any[];
  "cidHighlighter": any[];
  "cidHighligt": any[];
  "cidHistory": any[];
  "cidHome": any[];
  "cidHospital": any[];
  "cidHotTub": any[];
  "cidHotel": any[];
  "cidHourglass": any[];
  "cidHouse": any[];
  "cidHq": any[];
  "cidHttp": any[];
  "cidHttps": any[];
  "cidIdBadge": any[];
  "cidIdCard": any[];
  "cidImageBroken": any[];
  "cidImagePlus": any[];
  "cidImage": any[];
  "cidImages": any[];
  "cidInboxIn": any[];
  "cidInboxOut": any[];
  "cidInbox": any[];
  "cidIndentDecrease": any[];
  "cidIndentIncrease": any[];
  "cidIndustrySlash": any[];
  "cidIndustry": any[];
  "cidInfinity": any[];
  "cidInfoCircle": any[];
  "cidInfo": any[];
  "cidInputAntenna": any[];
  "cidInputComponent": any[];
  "cidInputHdmi": any[];
  "cidInputPowerOff": any[];
  "cidInputPower": any[];
  "cidInputSvideo": any[];
  "cidInput": any[];
  "cidInstitution": any[];
  "cidInvert": any[];
  "cidItalic": any[];
  "cidJustifyCenter": any[];
  "cidJustifyLeft": any[];
  "cidJustifyRight": any[];
  "cidKeyAlt": any[];
  "cidKey": any[];
  "cidKeyboardHide": any[];
  "cidKeyboard": any[];
  "cidKitchen": any[];
  "cidLan": any[];
  "cidLanguage": any[];
  "cidLaptop": any[];
  "cidLaundry": any[];
  "cidLayersSlash": any[];
  "cidLayers": any[];
  "cidLeaf": any[];
  "cidLemon": any[];
  "cidLevelDown": any[];
  "cidLevelUp": any[];
  "cidLibraryAdd": any[];
  "cidLibraryBookmark": any[];
  "cidLibraryBooks": any[];
  "cidLibraryBuilding": any[];
  "cidLibraryMusic": any[];
  "cidLibrary": any[];
  "cidLifeRing": any[];
  "cidLightbulb": any[];
  "cidLineSpacing": any[];
  "cidLineStyle": any[];
  "cidLineWeight": any[];
  "cidLinkAlt": any[];
  "cidLinkBroken": any[];
  "cidLinkIntact": any[];
  "cidLinkSlash": any[];
  "cidLink": any[];
  "cidListFilter": any[];
  "cidListHighPriority": any[];
  "cidListLowPriority": any[];
  "cidListNumberedRtl": any[];
  "cidListNumbered": any[];
  "cidListRich": any[];
  "cidList": any[];
  "cidLocationGpsFixed": any[];
  "cidLocationGpsOff": any[];
  "cidLocationGps": any[];
  "cidLocationPinCheck": any[];
  "cidLocationPinEdit": any[];
  "cidLocationPinPlus": any[];
  "cidLocationPinSlash": any[];
  "cidLocationPin": any[];
  "cidLockLocked": any[];
  "cidLockMinus": any[];
  "cidLockPlus": any[];
  "cidLockUnlocked": any[];
  "cidLocomotive": any[];
  "cidLoop1": any[];
  "cidLoopCircular": any[];
  "cidLoopSquare": any[];
  "cidLoop": any[];
  "cidLowVision": any[];
  "cidLoyalty": any[];
  "cidMadiaSkipBackward": any[];
  "cidMagnifyingGlass": any[];
  "cidMail": any[];
  "cidMailbox": any[];
  "cidMapAlt": any[];
  "cidMap": any[];
  "cidMediaEjectCircle": any[];
  "cidMediaEjectSquare": any[];
  "cidMediaEject": any[];
  "cidMediaPauseCircle": any[];
  "cidMediaPauseSquare": any[];
  "cidMediaPlayCircle": any[];
  "cidMediaPlaySquare": any[];
  "cidMediaRecordCircle": any[];
  "cidMediaRecordSquare": any[];
  "cidMediaSkipBackwardCircle": any[];
  "cidMediaSkipBackwardSquare": any[];
  "cidMediaSkipForwardCircle": any[];
  "cidMediaSkipForwardSquare": any[];
  "cidMediaSkipForward": any[];
  "cidMediaStepBackwardCircle": any[];
  "cidMediaStepBackwardSquare": any[];
  "cidMediaStepBackward": any[];
  "cidMediaStepForwardCircle": any[];
  "cidMediaStepForwardSquare": any[];
  "cidMediaStepForward": any[];
  "cidMediaStopCircle": any[];
  "cidMediaStopSquare": any[];
  "cidMedicalCross": any[];
  "cidMeh": any[];
  "cidMemory": any[];
  "cidMenu": any[];
  "cidMicAlt": any[];
  "cidMicSettings": any[];
  "cidMicSlash": any[];
  "cidMic": any[];
  "cidMicrochip": any[];
  "cidMicrophoneAlt": any[];
  "cidMicrophoneSettings": any[];
  "cidMicrophoneSlash": any[];
  "cidMicrophone": any[];
  "cidMinusCircle": any[];
  "cidMinusSquare": any[];
  "cidMobileArrowAdd": any[];
  "cidMobileArrowRemove": any[];
  "cidMobileCheck": any[];
  "cidMobileDeveloperMode": any[];
  "cidMobileLandscape": any[];
  "cidMobileLock": any[];
  "cidMobileMinus": any[];
  "cidMobilePlus": any[];
  "cidMobilePortrait": any[];
  "cidMobileSettings": any[];
  "cidMobileSlash": any[];
  "cidMobileSms": any[];
  "cidMobileSpeaker": any[];
  "cidMobileVolume": any[];
  "cidMobileX": any[];
  "cidMobile": any[];
  "cidMoneyBillAlt": any[];
  "cidMoneyBillAlt2": any[];
  "cidMoneyBill": any[];
  "cidMoney": any[];
  "cidMonitor": any[];
  "cidMoodBad": any[];
  "cidMoodGood": any[];
  "cidMoodVeryBad": any[];
  "cidMoodVeryGood": any[];
  "cidMoon": any[];
  "cidMore": any[];
  "cidMotorbike": any[];
  "cidMouseAlt": any[];
  "cidMouse": any[];
  "cidMouthSlash": any[];
  "cidMouth": any[];
  "cidMove": any[];
  "cidMovieAlt": any[];
  "cidMovie": any[];
  "cidMugTea": any[];
  "cidMug": any[];
  "cidMusicNoteAlt": any[];
  "cidMusicNoteSlash": any[];
  "cidMusicNote": any[];
  "cidMusicVideo": any[];
  "cidNetworkCheck": any[];
  "cidNewReleases": any[];
  "cidNew": any[];
  "cidNewspaper": any[];
  "cidNoteAdd": any[];
  "cidNote": any[];
  "cidNotes": any[];
  "cidObjectGroup": any[];
  "cidObjectUngroup": any[];
  "cidOpacity": any[];
  "cidOpentype": any[];
  "cidOptionsAlt": any[];
  "cidOptions": any[];
  "cidOven": any[];
  "cidOverscanSettings": any[];
  "cidOverscan": any[];
  "cidPageRestore": any[];
  "cidPage": any[];
  "cidPageview": any[];
  "cidPaintBucket": any[];
  "cidPaint": any[];
  "cidPaperPlane": any[];
  "cidPaperclip": any[];
  "cidParagraph": any[];
  "cidParking": any[];
  "cidPaw": any[];
  "cidPenAlt": any[];
  "cidPenFancy": any[];
  "cidPenNib": any[];
  "cidPen": any[];
  "cidPencil": any[];
  "cidPeopleMinus": any[];
  "cidPeoplePlus": any[];
  "cidPeopleX": any[];
  "cidPeople": any[];
  "cidPercent": any[];
  "cidPersonFemale": any[];
  "cidPerson": any[];
  "cidPetrolStation": any[];
  "cidPhoneBluetooth": any[];
  "cidPhoneCallEnd": any[];
  "cidPhoneCall": any[];
  "cidPhoneCallback": any[];
  "cidPhoneCheck": any[];
  "cidPhoneForward": any[];
  "cidPhoneInTalk": any[];
  "cidPhoneLock": any[];
  "cidPhoneMinus": any[];
  "cidPhoneMissed": any[];
  "cidPhonePaused": any[];
  "cidPhonePlus": any[];
  "cidPhoneRingVolume": any[];
  "cidPhoneSettings": any[];
  "cidPhoneSlash": any[];
  "cidPhoneSquare": any[];
  "cidPhoneVolume": any[];
  "cidPhoneX": any[];
  "cidPhone": any[];
  "cidPictureInPictureAlt": any[];
  "cidPictureInPicture": any[];
  "cidPin": any[];
  "cidPizza": any[];
  "cidPlant": any[];
  "cidPlaylistAddCheck": any[];
  "cidPlaylistAdd": any[];
  "cidPlaylistPlay": any[];
  "cidPlusCircle": any[];
  "cidPlusOne": any[];
  "cidPlusSquare": any[];
  "cidPool": any[];
  "cidPortableWifiOff": any[];
  "cidPortableWifi": any[];
  "cidPowerSettings": any[];
  "cidPowerStandby": any[];
  "cidPregnant": any[];
  "cidPrint": any[];
  "cidPrinterSlash": any[];
  "cidPrinter": any[];
  "cidPushchair": any[];
  "cidQrCode": any[];
  "cidQueueAdd": any[];
  "cidQueueMusic": any[];
  "cidQueuePlayNext": any[];
  "cidQueueRemove": any[];
  "cidQueue": any[];
  "cidRadio": any[];
  "cidRailway": any[];
  "cidRain": any[];
  "cidRandom": any[];
  "cidRecentActors": any[];
  "cidRecycle": any[];
  "cidRegistered": any[];
  "cidReload": any[];
  "cidRemoteControl": any[];
  "cidRemoteSettings": any[];
  "cidReplay": any[];
  "cidReportSlash": any[];
  "cidReport": any[];
  "cidResizeBoth": any[];
  "cidResizeHeight": any[];
  "cidResizeWidth": any[];
  "cidRestaurantMenu": any[];
  "cidRestaurant": any[];
  "cidRestore": any[];
  "cidRights": any[];
  "cidRoomSlash": any[];
  "cidRoom": any[];
  "cidRotateLeft": any[];
  "cidRotateRight": any[];
  "cidRoundedCorner": any[];
  "cidRouter": any[];
  "cidRowing": any[];
  "cidRssAlt": any[];
  "cidRssSquare": any[];
  "cidRss": any[];
  "cidRubleCircleSlash": any[];
  "cidRubleCircle": any[];
  "cidRubleSlash": any[];
  "cidRuble": any[];
  "cidSad": any[];
  "cidSatelite": any[];
  "cidSave": any[];
  "cidScaleImage": any[];
  "cidScale": any[];
  "cidScanner": any[];
  "cidSchool": any[];
  "cidScooter": any[];
  "cidScreenDeskopSlash": any[];
  "cidScreenDesktop": any[];
  "cidScreenHorizontal": any[];
  "cidScreenLandscape": any[];
  "cidScreenLockHorizontal": any[];
  "cidScreenLockLandscape": any[];
  "cidScreenLockPortrait": any[];
  "cidScreenLockRotation": any[];
  "cidScreenLockVertical": any[];
  "cidScreenMirroring": any[];
  "cidScreenPortrait": any[];
  "cidScreenRotation": any[];
  "cidScreenSmartphone": any[];
  "cidScreenVertical": any[];
  "cidScript": any[];
  "cidScrubber": any[];
  "cidSdcard": any[];
  "cidSearch": any[];
  "cidSecurity": any[];
  "cidSelectAll": any[];
  "cidSelect": any[];
  "cidSend": any[];
  "cidSettingsAlt": any[];
  "cidSettings": any[];
  "cidShareAll": any[];
  "cidShareAlt": any[];
  "cidShareBoxed": any[];
  "cidShare": any[];
  "cidShieldAlt": any[];
  "cidShieldCheck": any[];
  "cidShieldMinus": any[];
  "cidShieldPlus": any[];
  "cidShieldSlash": any[];
  "cidShieldX": any[];
  "cidShield": any[];
  "cidShopMediaTwo": any[];
  "cidShopMedia": any[];
  "cidShortText": any[];
  "cidShower": any[];
  "cidSignLanguage": any[];
  "cidSignalCellular0": any[];
  "cidSignalCellular1": any[];
  "cidSignalCellular2": any[];
  "cidSignalCellular3": any[];
  "cidSignalCellular4": any[];
  "cidSignalCellularNoInternet0": any[];
  "cidSignalCellularNoInternet1": any[];
  "cidSignalCellularNoInternet2": any[];
  "cidSignalCellularNoInternet3": any[];
  "cidSignalCellularNoInternet4": any[];
  "cidSignalCellularOff": any[];
  "cidSignpost": any[];
  "cidSimSlash": any[];
  "cidSim": any[];
  "cidSitemap": any[];
  "cidSlowMotion": any[];
  "cidSmilePlus": any[];
  "cidSmile": any[];
  "cidSmokeFree": any[];
  "cidSmokeSlash": any[];
  "cidSmoke": any[];
  "cidSmokingRoom": any[];
  "cidSnow": any[];
  "cidSnowflake": any[];
  "cidSoccer": any[];
  "cidSofa": any[];
  "cidSorroundSound": any[];
  "cidSortAlphaDown": any[];
  "cidSortAlphaUp": any[];
  "cidSortAscending": any[];
  "cidSortDescending": any[];
  "cidSortNumericDown": any[];
  "cidSortNumericUp": any[];
  "cidSound": any[];
  "cidSpa": any[];
  "cidSpaceBar": any[];
  "cidSpeak": any[];
  "cidSpeakerGroup": any[];
  "cidSpeaker": any[];
  "cidSpeechBubble": any[];
  "cidSpeechNotesSlash": any[];
  "cidSpeechNotes": any[];
  "cidSpeech": any[];
  "cidSpeedometer": any[];
  "cidSpreadsheet": any[];
  "cidStarCircle": any[];
  "cidStarHalf": any[];
  "cidStickyNote": any[];
  "cidStorage": any[];
  "cidStore": any[];
  "cidStream": any[];
  "cidStrikethrough": any[];
  "cidSubtitles": any[];
  "cidSubway": any[];
  "cidSun": any[];
  "cidSwapHorizontalCircle": any[];
  "cidSwapHorizontal": any[];
  "cidSwapVerticalCircle": any[];
  "cidSwapVertical": any[];
  "cidSwimming": any[];
  "cidSyncDisabled": any[];
  "cidSyncProblem": any[];
  "cidSync": any[];
  "cidTablet": any[];
  "cidTag": any[];
  "cidTags": any[];
  "cidTarget": any[];
  "cidTask": any[];
  "cidTaxi": any[];
  "cidTemperatureAlt": any[];
  "cidTemperatureHigh": any[];
  "cidTemperatureLow": any[];
  "cidTemperature": any[];
  "cidTennisBall": any[];
  "cidTennis": any[];
  "cidTerminal": any[];
  "cidTerrain": any[];
  "cidTextDirectionLtr": any[];
  "cidTextDirectionRtl": any[];
  "cidTextFormatClear": any[];
  "cidTextHeight": any[];
  "cidTextRotateVertical": any[];
  "cidTextRotationDown": any[];
  "cidTextRotationNone": any[];
  "cidTextRotationUp": any[];
  "cidTextShapes": any[];
  "cidTextSize": any[];
  "cidTextSquare": any[];
  "cidTextStrike": any[];
  "cidTextWidth": any[];
  "cidText": any[];
  "cidThermometerAlt": any[];
  "cidThermometer": any[];
  "cidThumbDown": any[];
  "cidThumbUp": any[];
  "cidTimeline": any[];
  "cidTimer": any[];
  "cidToggleOff": any[];
  "cidToggleOn": any[];
  "cidToilet": any[];
  "cidToll": any[];
  "cidTouchApp": any[];
  "cidTrademark": any[];
  "cidTraffic": any[];
  "cidTrainAlt": any[];
  "cidTrain": any[];
  "cidTram": any[];
  "cidTransferWithinAStation": any[];
  "cidTransfer": any[];
  "cidTranslate": any[];
  "cidTrashAlt": any[];
  "cidTrashArrowUp": any[];
  "cidTrashSweep": any[];
  "cidTrashX": any[];
  "cidTrash": any[];
  "cidTruck": any[];
  "cidTty": any[];
  "cidTvDvr": any[];
  "cidTvLive": any[];
  "cidTvSlash": any[];
  "cidTv": any[];
  "cidUnderline": any[];
  "cidUniversalAccess": any[];
  "cidUpdate": any[];
  "cidUsb": any[];
  "cidUserFemaleFollow": any[];
  "cidUserFemaleMinus": any[];
  "cidUserFemalePlus": any[];
  "cidUserFemaleUnfollow": any[];
  "cidUserFemaleX": any[];
  "cidUserFemale": any[];
  "cidUserFollow": any[];
  "cidUserMinus": any[];
  "cidUserPlus": any[];
  "cidUserSecret": any[];
  "cidUserUnfollow": any[];
  "cidUser": any[];
  "cidVector": any[];
  "cidVericalSplit": any[];
  "cidVerticalAlignBottom": any[];
  "cidVerticalAlignCenter": any[];
  "cidVerticalAlignTop": any[];
  "cidVideoLabel": any[];
  "cidVideoLibrary": any[];
  "cidVideoMissed": any[];
  "cidVideoPlus": any[];
  "cidVideoSlash": any[];
  "cidVideoSwitch": any[];
  "cidVideo": any[];
  "cidVideogame": any[];
  "cidViewAgenda": any[];
  "cidViewArray": any[];
  "cidViewCarousel": any[];
  "cidViewColumn": any[];
  "cidViewList": any[];
  "cidViewModule": any[];
  "cidViewQuilt": any[];
  "cidViewRow": any[];
  "cidViewStream": any[];
  "cidVoiceOverRecord": any[];
  "cidVoiceOverSlash": any[];
  "cidVoice": any[];
  "cidVoicemail": any[];
  "cidVolumeHigh": any[];
  "cidVolumeLow": any[];
  "cidVolumeOff": any[];
  "cidVolume": any[];
  "cidVote": any[];
  "cidWallet": any[];
  "cidWallpaper": any[];
  "cidWarning": any[];
  "cidWatch": any[];
  "cidWaves": any[];
  "cidWc": any[];
  "cidWebcloud": any[];
  "cidWeightlifitng": any[];
  "cidWeights": any[];
  "cidWheelchair": any[];
  "cidWidgets": any[];
  "cidWifiLock": any[];
  "cidWifiSignal0": any[];
  "cidWifiSignal1": any[];
  "cidWifiSignal2": any[];
  "cidWifiSignal3": any[];
  "cidWifiSignal4": any[];
  "cidWifiSignalLock0": any[];
  "cidWifiSignalLock1": any[];
  "cidWifiSignalLock2": any[];
  "cidWifiSignalLock3": any[];
  "cidWifiSignalLock4": any[];
  "cidWifiSignalOff": any[];
  "cidWifi": any[];
  "cidWindowMaximize": any[];
  "cidWindowMinimize": any[];
  "cidWindowRestore": any[];
  "cidWindow": any[];
  "cidWrapText": any[];
  "cidXCircle": any[];
  "cidXSquare": any[];
  "cidYenCircleSlash": any[];
  "cidYenCircle": any[];
  "cidYenSlash": any[];
  "cidYen": any[];
  "cidZoomIn": any[];
  "cidZoomOut": any[];
  "cidZoom": any[];
}
export declare const cid3dRotate: any[];
export declare const cid3d: any[];
export declare const cid4k: any[];
export declare const cidAccessible: any[];
export declare const cidAccountLogout: any[];
export declare const cidActionRedo: any[];
export declare const cidActionUndo: any[];
export declare const cidAddressBook: any[];
export declare const cidAddressCard: any[];
export declare const cidAirplaneModeOff: any[];
export declare const cidAirplaneMode: any[];
export declare const cidAirplay: any[];
export declare const cidAlarmAdd: any[];
export declare const cidAlarmOff: any[];
export declare const cidAlarmOn: any[];
export declare const cidAlarmSnooze: any[];
export declare const cidAlarm: any[];
export declare const cidAlbum: any[];
export declare const cidAlignCenter: any[];
export declare const cidAlignLeft: any[];
export declare const cidAlignRight: any[];
export declare const cidAmericanFootball: any[];
export declare const cidAnimal: any[];
export declare const cidAperture: any[];
export declare const cidApple: any[];
export declare const cidApplicationsSettings: any[];
export declare const cidApplications: any[];
export declare const cidAppsSettings: any[];
export declare const cidApps: any[];
export declare const cidArchive: any[];
export declare const cidArrowCircleBottom: any[];
export declare const cidArrowCircleLeft: any[];
export declare const cidArrowCircleRight: any[];
export declare const cidArrowCircleTop: any[];
export declare const cidArrowThickCircleDown: any[];
export declare const cidArrowThickCircleLeft: any[];
export declare const cidArrowThickCircleRight: any[];
export declare const cidArrowThickCircleUp: any[];
export declare const cidArrowThickFromBottom: any[];
export declare const cidArrowThickFromLeft: any[];
export declare const cidArrowThickFromRight: any[];
export declare const cidArrowThickFromTop: any[];
export declare const cidArrowThickSquareDown: any[];
export declare const cidArrowThickSquareLeft: any[];
export declare const cidArrowThickSquareRight: any[];
export declare const cidArrowThickSquareUp: any[];
export declare const cidArrowThickToBottom: any[];
export declare const cidArrowThickToLeft: any[];
export declare const cidArrowThickToRight: any[];
export declare const cidArrowThickToTop: any[];
export declare const cidArtTrack: any[];
export declare const cidAspectRatio: any[];
export declare const cidAssistiveListeningSystem: any[];
export declare const cidAsteriskCircle: any[];
export declare const cidAt: any[];
export declare const cidAudioDescription: any[];
export declare const cidAudioSpectrum: any[];
export declare const cidAudio: any[];
export declare const cidAvTimer: any[];
export declare const cidBabyCarriage: any[];
export declare const cidBaby: any[];
export declare const cidBackspace: any[];
export declare const cidBadge: any[];
export declare const cidBalanceScaleLeft: any[];
export declare const cidBalanceScaleRight: any[];
export declare const cidBalanceScale: any[];
export declare const cidBan: any[];
export declare const cidBank: any[];
export declare const cidBarChart: any[];
export declare const cidBarcode: any[];
export declare const cidBaseball: any[];
export declare const cidBasketArrowDown: any[];
export declare const cidBasketLoaded: any[];
export declare const cidBasketPlus: any[];
export declare const cidBasket: any[];
export declare const cidBasketball: any[];
export declare const cidBath: any[];
export declare const cidBathroom: any[];
export declare const cidBattery0: any[];
export declare const cidBattery1: any[];
export declare const cidBattery2: any[];
export declare const cidBattery3: any[];
export declare const cidBattery4: any[];
export declare const cidBattery5: any[];
export declare const cidBatteryAlert: any[];
export declare const cidBatteryAlt0: any[];
export declare const cidBatteryAlt1: any[];
export declare const cidBatteryAlt2: any[];
export declare const cidBatteryAlt3: any[];
export declare const cidBatteryAltEmpty: any[];
export declare const cidBatteryAltFull: any[];
export declare const cidBatteryAltSlash: any[];
export declare const cidBatteryCharge: any[];
export declare const cidBatteryEmpty: any[];
export declare const cidBatteryFull: any[];
export declare const cidBatterySlash: any[];
export declare const cidBatteryUnknown: any[];
export declare const cidBatteryX: any[];
export declare const cidBeachAccess: any[];
export declare const cidBeaker: any[];
export declare const cidBed: any[];
export declare const cidBellExclamation: any[];
export declare const cidBellPlus: any[];
export declare const cidBellRing: any[];
export declare const cidBellSlash: any[];
export declare const cidBell: any[];
export declare const cidBikeAlt: any[];
export declare const cidBike: any[];
export declare const cidBirthdayCake: any[];
export declare const cidBlind: any[];
export declare const cidBluetoothConnected: any[];
export declare const cidBluetoothSearching: any[];
export declare const cidBluetoothSettings: any[];
export declare const cidBluetoothSlash: any[];
export declare const cidBluetooth: any[];
export declare const cidBoatAlt: any[];
export declare const cidBoat: any[];
export declare const cidBold: any[];
export declare const cidBoltCircle: any[];
export declare const cidBookOpen: any[];
export declare const cidBook: any[];
export declare const cidBookmark: any[];
export declare const cidBookmarks: any[];
export declare const cidBorderAll: any[];
export declare const cidBorderBottom: any[];
export declare const cidBorderClear: any[];
export declare const cidBorderHorizontal: any[];
export declare const cidBorderInner: any[];
export declare const cidBorderLeft: any[];
export declare const cidBorderOuter: any[];
export declare const cidBorderRight: any[];
export declare const cidBorderStyle: any[];
export declare const cidBorderTop: any[];
export declare const cidBorderVertical: any[];
export declare const cidBowlingPins: any[];
export declare const cidBowling: any[];
export declare const cidBoxAlt: any[];
export declare const cidBox: any[];
export declare const cidBraille: any[];
export declare const cidBrandingWatermark: any[];
export declare const cidBriefcaseArrowLeft: any[];
export declare const cidBriefcaseArrowRight: any[];
export declare const cidBriefcaseSlash: any[];
export declare const cidBriefcase: any[];
export declare const cidBrightnessAuto: any[];
export declare const cidBrightnessHigh: any[];
export declare const cidBrightnessLow: any[];
export declare const cidBrightnessMedium: any[];
export declare const cidBrightness: any[];
export declare const cidBritishPoundCircle: any[];
export declare const cidBritishPoundSlash: any[];
export declare const cidBritishPound: any[];
export declare const cidBroadcastTower: any[];
export declare const cidBrowser: any[];
export declare const cidBrushAlt: any[];
export declare const cidBrush: any[];
export declare const cidBug: any[];
export declare const cidBuildingBusinessSlash: any[];
export declare const cidBuildingBusiness: any[];
export declare const cidBuildingSlash: any[];
export declare const cidBuilding: any[];
export declare const cidBullhorn: any[];
export declare const cidBurger: any[];
export declare const cidBurn: any[];
export declare const cidBusAlt: any[];
export declare const cidBusTimer: any[];
export declare const cidBus: any[];
export declare const cidCalculator: any[];
export declare const cidCalendarCheck: any[];
export declare const cidCalendarEvent: any[];
export declare const cidCalendarMinus: any[];
export declare const cidCalendarNote: any[];
export declare const cidCalendarPlus: any[];
export declare const cidCalendarTimes: any[];
export declare const cidCalendarToday: any[];
export declare const cidCalendarViewDay: any[];
export declare const cidCalendar: any[];
export declare const cidCallMade: any[];
export declare const cidCallMerge: any[];
export declare const cidCallMissedOutgoing: any[];
export declare const cidCallMissed: any[];
export declare const cidCallReceived: any[];
export declare const cidCallSplit: any[];
export declare const cidCallSwapCalls: any[];
export declare const cidCallToAction: any[];
export declare const cidCameraControl: any[];
export declare const cidCameraEnhance: any[];
export declare const cidCameraPlus: any[];
export declare const cidCameraRoll: any[];
export declare const cidCameraSwitch: any[];
export declare const cidCamera: any[];
export declare const cidCarAlt: any[];
export declare const cidCar: any[];
export declare const cidCardGiftcard: any[];
export declare const cidCardMembership: any[];
export declare const cidCardTravel: any[];
export declare const cidCaretBottom: any[];
export declare const cidCaretLeft: any[];
export declare const cidCaretRight: any[];
export declare const cidCaretTop: any[];
export declare const cidCartArrowDown: any[];
export declare const cidCartLoaded: any[];
export declare const cidCartPlus: any[];
export declare const cidCartSlash: any[];
export declare const cidCart: any[];
export declare const cidCash: any[];
export declare const cidCasino: any[];
export declare const cidCastConnected: any[];
export declare const cidCastForEducation: any[];
export declare const cidCast: any[];
export declare const cidCat: any[];
export declare const cidCc: any[];
export declare const cidCenterFocusWeak: any[];
export declare const cidCenterFocus: any[];
export declare const cidChalkboardTeacher: any[];
export declare const cidChartArea: any[];
export declare const cidChartBubble: any[];
export declare const cidChartDonut: any[];
export declare const cidChartLine: any[];
export declare const cidChartMultiline: any[];
export declare const cidChartPie: any[];
export declare const cidChartShow: any[];
export declare const cidChartTable: any[];
export declare const cidChart: any[];
export declare const cidChatBubble: any[];
export declare const cidChatSquare: any[];
export declare const cidCheckAlt: any[];
export declare const cidCheckCircle: any[];
export declare const cidCheckDoubleAlt: any[];
export declare const cidCheckDouble: any[];
export declare const cidCheck: any[];
export declare const cidChevronBottomAlt: any[];
export declare const cidChevronCircleDownAlt: any[];
export declare const cidChevronCircleDown: any[];
export declare const cidChevronCircleLeftAlt: any[];
export declare const cidChevronCircleLeft: any[];
export declare const cidChevronCircleRightAlt: any[];
export declare const cidChevronCircleRight: any[];
export declare const cidChevronCircleUpAlt: any[];
export declare const cidChevronCircleUp: any[];
export declare const cidChevronDoubleDownAlt: any[];
export declare const cidChevronDoubleDown: any[];
export declare const cidChevronDoubleLeftAlt: any[];
export declare const cidChevronDoubleLeft: any[];
export declare const cidChevronDoubleRightAlt: any[];
export declare const cidChevronDoubleRight: any[];
export declare const cidChevronDoubleUpAlt: any[];
export declare const cidChevronDoubleUp: any[];
export declare const cidChevronLeftAlt: any[];
export declare const cidChevronRightAlt: any[];
export declare const cidChevronSquareDownAlt: any[];
export declare const cidChevronSquareDown: any[];
export declare const cidChevronSquareLeftAlt: any[];
export declare const cidChevronSquareLeft: any[];
export declare const cidChevronSquareRightAlt: any[];
export declare const cidChevronSquareRight: any[];
export declare const cidChevronSquareUpAlt: any[];
export declare const cidChevronSquareUp: any[];
export declare const cidChevronTopAlt: any[];
export declare const cidChildFriendly: any[];
export declare const cidChild: any[];
export declare const cidCity: any[];
export declare const cidClearAll: any[];
export declare const cidClipboard: any[];
export declare const cidClock: any[];
export declare const cidClone: any[];
export declare const cidClosedCaptioning: any[];
export declare const cidCloudCheck: any[];
export declare const cidCloudCircle: any[];
export declare const cidCloudData: any[];
export declare const cidCloudDownload: any[];
export declare const cidCloudSlash: any[];
export declare const cidCloudUpload: any[];
export declare const cidCloudy: any[];
export declare const cidCode: any[];
export declare const cidCoffee: any[];
export declare const cidCog: any[];
export declare const cidColorBorder: any[];
export declare const cidColorFill: any[];
export declare const cidColorPalette: any[];
export declare const cidColumns: any[];
export declare const cidCommand: any[];
export declare const cidCommentBubbleCheck: any[];
export declare const cidCommentBubbleEdit: any[];
export declare const cidCommentBubbleExclamation: any[];
export declare const cidCommentBubbleLines: any[];
export declare const cidCommentBubbleMinus: any[];
export declare const cidCommentBubblePlus: any[];
export declare const cidCommentBubbleQuestion: any[];
export declare const cidCommentBubbleSmile: any[];
export declare const cidCommentBubbleX: any[];
export declare const cidCommentBubble: any[];
export declare const cidCommentSquareCheck: any[];
export declare const cidCommentSquareEdit: any[];
export declare const cidCommentSquareExclamation: any[];
export declare const cidCommentSquareImage: any[];
export declare const cidCommentSquareLines: any[];
export declare const cidCommentSquareMinus: any[];
export declare const cidCommentSquarePlus: any[];
export declare const cidCommentSquareRateReview: any[];
export declare const cidCommentSquareSmile: any[];
export declare const cidCommentSquareX: any[];
export declare const cidCommentSquare: any[];
export declare const cidCommute: any[];
export declare const cidCompare: any[];
export declare const cidCompassCalibration: any[];
export declare const cidCompassSlash: any[];
export declare const cidCompass: any[];
export declare const cidCompressWide: any[];
export declare const cidCompress: any[];
export declare const cidContactMail: any[];
export declare const cidContactPhone: any[];
export declare const cidContact: any[];
export declare const cidContacts: any[];
export declare const cidContrast: any[];
export declare const cidControl: any[];
export declare const cidCopy: any[];
export declare const cidCopyright: any[];
export declare const cidCouch: any[];
export declare const cidCreditCard: any[];
export declare const cidCropRotate: any[];
export declare const cidCrop: any[];
export declare const cidCursorMove: any[];
export declare const cidCursor: any[];
export declare const cidCut: any[];
export declare const cidDataTransferDown: any[];
export declare const cidDataTransferUp: any[];
export declare const cidDeaf: any[];
export declare const cidDelete: any[];
export declare const cidDescription: any[];
export declare const cidDeveloperBoard: any[];
export declare const cidDeviceUnknown: any[];
export declare const cidDevicesImportant: any[];
export declare const cidDevicesOther: any[];
export declare const cidDevicesSlash: any[];
export declare const cidDevices: any[];
export declare const cidDial: any[];
export declare const cidDialpad: any[];
export declare const cidDiamond: any[];
export declare const cidDinner: any[];
export declare const cidDirections: any[];
export declare const cidDisabled: any[];
export declare const cidDns: any[];
export declare const cidDock: any[];
export declare const cidDocument: any[];
export declare const cidDog: any[];
export declare const cidDollarCircleSlash: any[];
export declare const cidDollarCircle: any[];
export declare const cidDollarSlash: any[];
export declare const cidDollar: any[];
export declare const cidDonate: any[];
export declare const cidDoor: any[];
export declare const cidDoubleQuoteSansLeft: any[];
export declare const cidDoubleQuoteSansRight: any[];
export declare const cidDoubleQuoteSerifLeft: any[];
export declare const cidDoubleQuoteSerifRight: any[];
export declare const cidDrinkAlcohol: any[];
export declare const cidDrink: any[];
export declare const cidDropSlash: any[];
export declare const cidDrop: any[];
export declare const cidDvr: any[];
export declare const cidEar: any[];
export declare const cidEco: any[];
export declare const cidEducation: any[];
export declare const cidElevator: any[];
export declare const cidEllipsis: any[];
export declare const cidEnergyCircle: any[];
export declare const cidEnvelopeClosed: any[];
export declare const cidEnvelopeLetter: any[];
export declare const cidEnvelopeMinus: any[];
export declare const cidEnvelopeOpen: any[];
export declare const cidEnvelopePlus: any[];
export declare const cidEqualizer: any[];
export declare const cidEthernetAlt: any[];
export declare const cidEthernet: any[];
export declare const cidEuroCircleSlash: any[];
export declare const cidEuroCircle: any[];
export declare const cidEuroSlash: any[];
export declare const cidEuro: any[];
export declare const cidEvStation: any[];
export declare const cidExcerpt: any[];
export declare const cidExclamationCircle: any[];
export declare const cidExclamation: any[];
export declare const cidExitToApp: any[];
export declare const cidExpandDown: any[];
export declare const cidExpandLeft: any[];
export declare const cidExpandRight: any[];
export declare const cidExpandUp: any[];
export declare const cidExposure: any[];
export declare const cidExternalLink: any[];
export declare const cidEyeSlash: any[];
export declare const cidEye: any[];
export declare const cidEyedropper: any[];
export declare const cidFaceDead: any[];
export declare const cidFace: any[];
export declare const cidFactorySlash: any[];
export declare const cidFactory: any[];
export declare const cidFastfood: any[];
export declare const cidFax: any[];
export declare const cidFeaturedPlaylist: any[];
export declare const cidFeaturedVideo: any[];
export declare const cidFiberDvr: any[];
export declare const cidFiberManual: any[];
export declare const cidFiberNew: any[];
export declare const cidFiberPin: any[];
export declare const cidFiberSmart: any[];
export declare const cidFileAcrobat: any[];
export declare const cidFileAdd: any[];
export declare const cidFileArchive: any[];
export declare const cidFileAudio: any[];
export declare const cidFileCode: any[];
export declare const cidFileDoc: any[];
export declare const cidFileExcel: any[];
export declare const cidFileImage: any[];
export declare const cidFilePdf: any[];
export declare const cidFilePowerpoint: any[];
export declare const cidFilePpt: any[];
export declare const cidFileVideo: any[];
export declare const cidFileWord: any[];
export declare const cidFileXls: any[];
export declare const cidFile: any[];
export declare const cidFilterFrames: any[];
export declare const cidFilterPhoto: any[];
export declare const cidFilterSquare: any[];
export declare const cidFilterX: any[];
export declare const cidFilter: any[];
export declare const cidFindInPage: any[];
export declare const cidFindReplace: any[];
export declare const cidFingerprint: any[];
export declare const cidFire: any[];
export declare const cidFlagAlt: any[];
export declare const cidFlagRectangle: any[];
export declare const cidFlagTriangle: any[];
export declare const cidFlag: any[];
export declare const cidFlightLand: any[];
export declare const cidFlightTakeoff: any[];
export declare const cidFlipToBack: any[];
export declare const cidFlipToFront: any[];
export declare const cidFlip: any[];
export declare const cidFlower: any[];
export declare const cidFolderAlt: any[];
export declare const cidFolderArrowLeft: any[];
export declare const cidFolderArrowRight: any[];
export declare const cidFolderBack: any[];
export declare const cidFolderMove: any[];
export declare const cidFolderOpen: any[];
export declare const cidFolderPlus: any[];
export declare const cidFolderShared: any[];
export declare const cidFolderSpecial: any[];
export declare const cidFolder: any[];
export declare const cidFont: any[];
export declare const cidFootball: any[];
export declare const cidFork: any[];
export declare const cidFridge: any[];
export declare const cidFrown: any[];
export declare const cidFullscreenExit: any[];
export declare const cidFullscreen: any[];
export declare const cidFunctionsAlt: any[];
export declare const cidFunctions: any[];
export declare const cidGamepad: any[];
export declare const cidGarage: any[];
export declare const cidGauge: any[];
export declare const cidGem: any[];
export declare const cidGif: any[];
export declare const cidGift: any[];
export declare const cidGlass: any[];
export declare const cidGlobeAltLock: any[];
export declare const cidGlobeAlt: any[];
export declare const cidGlobeLock: any[];
export declare const cidGlobe: any[];
export declare const cidGolfAlt: any[];
export declare const cidGolf: any[];
export declare const cidGradient: any[];
export declare const cidGrain: any[];
export declare const cidGraph: any[];
export declare const cidGridSlash: any[];
export declare const cidGrid: any[];
export declare const cidGripDotsHorizontal: any[];
export declare const cidGripDotsVertical: any[];
export declare const cidGripDots: any[];
export declare const cidGripHorizontal: any[];
export declare const cidGripLinesHorizontal: any[];
export declare const cidGripLinesVertical: any[];
export declare const cidGripLines: any[];
export declare const cidGripVertical: any[];
export declare const cidGrip: any[];
export declare const cidGroupMinus: any[];
export declare const cidGroupPlus: any[];
export declare const cidGroupX: any[];
export declare const cidGroup: any[];
export declare const cidHamburgerMenu: any[];
export declare const cidHandPointer: any[];
export declare const cidHandshake: any[];
export declare const cidHappy: any[];
export declare const cidHardDrive: any[];
export declare const cidHd: any[];
export declare const cidHdrSlash: any[];
export declare const cidHdr: any[];
export declare const cidHeader: any[];
export declare const cidHeadphonesMic: any[];
export declare const cidHeadphonesMute: any[];
export declare const cidHeadphones: any[];
export declare const cidHealing: any[];
export declare const cidHighQuality: any[];
export declare const cidHighlighter: any[];
export declare const cidHighligt: any[];
export declare const cidHistory: any[];
export declare const cidHome: any[];
export declare const cidHospital: any[];
export declare const cidHotTub: any[];
export declare const cidHotel: any[];
export declare const cidHourglass: any[];
export declare const cidHouse: any[];
export declare const cidHq: any[];
export declare const cidHttp: any[];
export declare const cidHttps: any[];
export declare const cidIdBadge: any[];
export declare const cidIdCard: any[];
export declare const cidImageBroken: any[];
export declare const cidImagePlus: any[];
export declare const cidImage: any[];
export declare const cidImages: any[];
export declare const cidInboxIn: any[];
export declare const cidInboxOut: any[];
export declare const cidInbox: any[];
export declare const cidIndentDecrease: any[];
export declare const cidIndentIncrease: any[];
export declare const cidIndustrySlash: any[];
export declare const cidIndustry: any[];
export declare const cidInfinity: any[];
export declare const cidInfoCircle: any[];
export declare const cidInfo: any[];
export declare const cidInputAntenna: any[];
export declare const cidInputComponent: any[];
export declare const cidInputHdmi: any[];
export declare const cidInputPowerOff: any[];
export declare const cidInputPower: any[];
export declare const cidInputSvideo: any[];
export declare const cidInput: any[];
export declare const cidInstitution: any[];
export declare const cidInvert: any[];
export declare const cidItalic: any[];
export declare const cidJustifyCenter: any[];
export declare const cidJustifyLeft: any[];
export declare const cidJustifyRight: any[];
export declare const cidKeyAlt: any[];
export declare const cidKey: any[];
export declare const cidKeyboardHide: any[];
export declare const cidKeyboard: any[];
export declare const cidKitchen: any[];
export declare const cidLan: any[];
export declare const cidLanguage: any[];
export declare const cidLaptop: any[];
export declare const cidLaundry: any[];
export declare const cidLayersSlash: any[];
export declare const cidLayers: any[];
export declare const cidLeaf: any[];
export declare const cidLemon: any[];
export declare const cidLevelDown: any[];
export declare const cidLevelUp: any[];
export declare const cidLibraryAdd: any[];
export declare const cidLibraryBookmark: any[];
export declare const cidLibraryBooks: any[];
export declare const cidLibraryBuilding: any[];
export declare const cidLibraryMusic: any[];
export declare const cidLibrary: any[];
export declare const cidLifeRing: any[];
export declare const cidLightbulb: any[];
export declare const cidLineSpacing: any[];
export declare const cidLineStyle: any[];
export declare const cidLineWeight: any[];
export declare const cidLinkAlt: any[];
export declare const cidLinkBroken: any[];
export declare const cidLinkIntact: any[];
export declare const cidLinkSlash: any[];
export declare const cidLink: any[];
export declare const cidListFilter: any[];
export declare const cidListHighPriority: any[];
export declare const cidListLowPriority: any[];
export declare const cidListNumberedRtl: any[];
export declare const cidListNumbered: any[];
export declare const cidListRich: any[];
export declare const cidList: any[];
export declare const cidLocationGpsFixed: any[];
export declare const cidLocationGpsOff: any[];
export declare const cidLocationGps: any[];
export declare const cidLocationPinCheck: any[];
export declare const cidLocationPinEdit: any[];
export declare const cidLocationPinPlus: any[];
export declare const cidLocationPinSlash: any[];
export declare const cidLocationPin: any[];
export declare const cidLockLocked: any[];
export declare const cidLockMinus: any[];
export declare const cidLockPlus: any[];
export declare const cidLockUnlocked: any[];
export declare const cidLocomotive: any[];
export declare const cidLoop1: any[];
export declare const cidLoopCircular: any[];
export declare const cidLoopSquare: any[];
export declare const cidLoop: any[];
export declare const cidLowVision: any[];
export declare const cidLoyalty: any[];
export declare const cidMadiaSkipBackward: any[];
export declare const cidMagnifyingGlass: any[];
export declare const cidMail: any[];
export declare const cidMailbox: any[];
export declare const cidMapAlt: any[];
export declare const cidMap: any[];
export declare const cidMediaEjectCircle: any[];
export declare const cidMediaEjectSquare: any[];
export declare const cidMediaEject: any[];
export declare const cidMediaPauseCircle: any[];
export declare const cidMediaPauseSquare: any[];
export declare const cidMediaPlayCircle: any[];
export declare const cidMediaPlaySquare: any[];
export declare const cidMediaRecordCircle: any[];
export declare const cidMediaRecordSquare: any[];
export declare const cidMediaSkipBackwardCircle: any[];
export declare const cidMediaSkipBackwardSquare: any[];
export declare const cidMediaSkipForwardCircle: any[];
export declare const cidMediaSkipForwardSquare: any[];
export declare const cidMediaSkipForward: any[];
export declare const cidMediaStepBackwardCircle: any[];
export declare const cidMediaStepBackwardSquare: any[];
export declare const cidMediaStepBackward: any[];
export declare const cidMediaStepForwardCircle: any[];
export declare const cidMediaStepForwardSquare: any[];
export declare const cidMediaStepForward: any[];
export declare const cidMediaStopCircle: any[];
export declare const cidMediaStopSquare: any[];
export declare const cidMedicalCross: any[];
export declare const cidMeh: any[];
export declare const cidMemory: any[];
export declare const cidMenu: any[];
export declare const cidMicAlt: any[];
export declare const cidMicSettings: any[];
export declare const cidMicSlash: any[];
export declare const cidMic: any[];
export declare const cidMicrochip: any[];
export declare const cidMicrophoneAlt: any[];
export declare const cidMicrophoneSettings: any[];
export declare const cidMicrophoneSlash: any[];
export declare const cidMicrophone: any[];
export declare const cidMinusCircle: any[];
export declare const cidMinusSquare: any[];
export declare const cidMobileArrowAdd: any[];
export declare const cidMobileArrowRemove: any[];
export declare const cidMobileCheck: any[];
export declare const cidMobileDeveloperMode: any[];
export declare const cidMobileLandscape: any[];
export declare const cidMobileLock: any[];
export declare const cidMobileMinus: any[];
export declare const cidMobilePlus: any[];
export declare const cidMobilePortrait: any[];
export declare const cidMobileSettings: any[];
export declare const cidMobileSlash: any[];
export declare const cidMobileSms: any[];
export declare const cidMobileSpeaker: any[];
export declare const cidMobileVolume: any[];
export declare const cidMobileX: any[];
export declare const cidMobile: any[];
export declare const cidMoneyBillAlt: any[];
export declare const cidMoneyBillAlt2: any[];
export declare const cidMoneyBill: any[];
export declare const cidMoney: any[];
export declare const cidMonitor: any[];
export declare const cidMoodBad: any[];
export declare const cidMoodGood: any[];
export declare const cidMoodVeryBad: any[];
export declare const cidMoodVeryGood: any[];
export declare const cidMoon: any[];
export declare const cidMore: any[];
export declare const cidMotorbike: any[];
export declare const cidMouseAlt: any[];
export declare const cidMouse: any[];
export declare const cidMouthSlash: any[];
export declare const cidMouth: any[];
export declare const cidMove: any[];
export declare const cidMovieAlt: any[];
export declare const cidMovie: any[];
export declare const cidMugTea: any[];
export declare const cidMug: any[];
export declare const cidMusicNoteAlt: any[];
export declare const cidMusicNoteSlash: any[];
export declare const cidMusicNote: any[];
export declare const cidMusicVideo: any[];
export declare const cidNetworkCheck: any[];
export declare const cidNewReleases: any[];
export declare const cidNew: any[];
export declare const cidNewspaper: any[];
export declare const cidNoteAdd: any[];
export declare const cidNote: any[];
export declare const cidNotes: any[];
export declare const cidObjectGroup: any[];
export declare const cidObjectUngroup: any[];
export declare const cidOpacity: any[];
export declare const cidOpentype: any[];
export declare const cidOptionsAlt: any[];
export declare const cidOptions: any[];
export declare const cidOven: any[];
export declare const cidOverscanSettings: any[];
export declare const cidOverscan: any[];
export declare const cidPageRestore: any[];
export declare const cidPage: any[];
export declare const cidPageview: any[];
export declare const cidPaintBucket: any[];
export declare const cidPaint: any[];
export declare const cidPaperPlane: any[];
export declare const cidPaperclip: any[];
export declare const cidParagraph: any[];
export declare const cidParking: any[];
export declare const cidPaw: any[];
export declare const cidPenAlt: any[];
export declare const cidPenFancy: any[];
export declare const cidPenNib: any[];
export declare const cidPen: any[];
export declare const cidPencil: any[];
export declare const cidPeopleMinus: any[];
export declare const cidPeoplePlus: any[];
export declare const cidPeopleX: any[];
export declare const cidPeople: any[];
export declare const cidPercent: any[];
export declare const cidPersonFemale: any[];
export declare const cidPerson: any[];
export declare const cidPetrolStation: any[];
export declare const cidPhoneBluetooth: any[];
export declare const cidPhoneCallEnd: any[];
export declare const cidPhoneCall: any[];
export declare const cidPhoneCallback: any[];
export declare const cidPhoneCheck: any[];
export declare const cidPhoneForward: any[];
export declare const cidPhoneInTalk: any[];
export declare const cidPhoneLock: any[];
export declare const cidPhoneMinus: any[];
export declare const cidPhoneMissed: any[];
export declare const cidPhonePaused: any[];
export declare const cidPhonePlus: any[];
export declare const cidPhoneRingVolume: any[];
export declare const cidPhoneSettings: any[];
export declare const cidPhoneSlash: any[];
export declare const cidPhoneSquare: any[];
export declare const cidPhoneVolume: any[];
export declare const cidPhoneX: any[];
export declare const cidPhone: any[];
export declare const cidPictureInPictureAlt: any[];
export declare const cidPictureInPicture: any[];
export declare const cidPin: any[];
export declare const cidPizza: any[];
export declare const cidPlant: any[];
export declare const cidPlaylistAddCheck: any[];
export declare const cidPlaylistAdd: any[];
export declare const cidPlaylistPlay: any[];
export declare const cidPlusCircle: any[];
export declare const cidPlusOne: any[];
export declare const cidPlusSquare: any[];
export declare const cidPool: any[];
export declare const cidPortableWifiOff: any[];
export declare const cidPortableWifi: any[];
export declare const cidPowerSettings: any[];
export declare const cidPowerStandby: any[];
export declare const cidPregnant: any[];
export declare const cidPrint: any[];
export declare const cidPrinterSlash: any[];
export declare const cidPrinter: any[];
export declare const cidPushchair: any[];
export declare const cidQrCode: any[];
export declare const cidQueueAdd: any[];
export declare const cidQueueMusic: any[];
export declare const cidQueuePlayNext: any[];
export declare const cidQueueRemove: any[];
export declare const cidQueue: any[];
export declare const cidRadio: any[];
export declare const cidRailway: any[];
export declare const cidRain: any[];
export declare const cidRandom: any[];
export declare const cidRecentActors: any[];
export declare const cidRecycle: any[];
export declare const cidRegistered: any[];
export declare const cidReload: any[];
export declare const cidRemoteControl: any[];
export declare const cidRemoteSettings: any[];
export declare const cidReplay: any[];
export declare const cidReportSlash: any[];
export declare const cidReport: any[];
export declare const cidResizeBoth: any[];
export declare const cidResizeHeight: any[];
export declare const cidResizeWidth: any[];
export declare const cidRestaurantMenu: any[];
export declare const cidRestaurant: any[];
export declare const cidRestore: any[];
export declare const cidRights: any[];
export declare const cidRoomSlash: any[];
export declare const cidRoom: any[];
export declare const cidRotateLeft: any[];
export declare const cidRotateRight: any[];
export declare const cidRoundedCorner: any[];
export declare const cidRouter: any[];
export declare const cidRowing: any[];
export declare const cidRssAlt: any[];
export declare const cidRssSquare: any[];
export declare const cidRss: any[];
export declare const cidRubleCircleSlash: any[];
export declare const cidRubleCircle: any[];
export declare const cidRubleSlash: any[];
export declare const cidRuble: any[];
export declare const cidSad: any[];
export declare const cidSatelite: any[];
export declare const cidSave: any[];
export declare const cidScaleImage: any[];
export declare const cidScale: any[];
export declare const cidScanner: any[];
export declare const cidSchool: any[];
export declare const cidScooter: any[];
export declare const cidScreenDeskopSlash: any[];
export declare const cidScreenDesktop: any[];
export declare const cidScreenHorizontal: any[];
export declare const cidScreenLandscape: any[];
export declare const cidScreenLockHorizontal: any[];
export declare const cidScreenLockLandscape: any[];
export declare const cidScreenLockPortrait: any[];
export declare const cidScreenLockRotation: any[];
export declare const cidScreenLockVertical: any[];
export declare const cidScreenMirroring: any[];
export declare const cidScreenPortrait: any[];
export declare const cidScreenRotation: any[];
export declare const cidScreenSmartphone: any[];
export declare const cidScreenVertical: any[];
export declare const cidScript: any[];
export declare const cidScrubber: any[];
export declare const cidSdcard: any[];
export declare const cidSearch: any[];
export declare const cidSecurity: any[];
export declare const cidSelectAll: any[];
export declare const cidSelect: any[];
export declare const cidSend: any[];
export declare const cidSettingsAlt: any[];
export declare const cidSettings: any[];
export declare const cidShareAll: any[];
export declare const cidShareAlt: any[];
export declare const cidShareBoxed: any[];
export declare const cidShare: any[];
export declare const cidShieldAlt: any[];
export declare const cidShieldCheck: any[];
export declare const cidShieldMinus: any[];
export declare const cidShieldPlus: any[];
export declare const cidShieldSlash: any[];
export declare const cidShieldX: any[];
export declare const cidShield: any[];
export declare const cidShopMediaTwo: any[];
export declare const cidShopMedia: any[];
export declare const cidShortText: any[];
export declare const cidShower: any[];
export declare const cidSignLanguage: any[];
export declare const cidSignalCellular0: any[];
export declare const cidSignalCellular1: any[];
export declare const cidSignalCellular2: any[];
export declare const cidSignalCellular3: any[];
export declare const cidSignalCellular4: any[];
export declare const cidSignalCellularNoInternet0: any[];
export declare const cidSignalCellularNoInternet1: any[];
export declare const cidSignalCellularNoInternet2: any[];
export declare const cidSignalCellularNoInternet3: any[];
export declare const cidSignalCellularNoInternet4: any[];
export declare const cidSignalCellularOff: any[];
export declare const cidSignpost: any[];
export declare const cidSimSlash: any[];
export declare const cidSim: any[];
export declare const cidSitemap: any[];
export declare const cidSlowMotion: any[];
export declare const cidSmilePlus: any[];
export declare const cidSmile: any[];
export declare const cidSmokeFree: any[];
export declare const cidSmokeSlash: any[];
export declare const cidSmoke: any[];
export declare const cidSmokingRoom: any[];
export declare const cidSnow: any[];
export declare const cidSnowflake: any[];
export declare const cidSoccer: any[];
export declare const cidSofa: any[];
export declare const cidSorroundSound: any[];
export declare const cidSortAlphaDown: any[];
export declare const cidSortAlphaUp: any[];
export declare const cidSortAscending: any[];
export declare const cidSortDescending: any[];
export declare const cidSortNumericDown: any[];
export declare const cidSortNumericUp: any[];
export declare const cidSound: any[];
export declare const cidSpa: any[];
export declare const cidSpaceBar: any[];
export declare const cidSpeak: any[];
export declare const cidSpeakerGroup: any[];
export declare const cidSpeaker: any[];
export declare const cidSpeechBubble: any[];
export declare const cidSpeechNotesSlash: any[];
export declare const cidSpeechNotes: any[];
export declare const cidSpeech: any[];
export declare const cidSpeedometer: any[];
export declare const cidSpreadsheet: any[];
export declare const cidStarCircle: any[];
export declare const cidStarHalf: any[];
export declare const cidStickyNote: any[];
export declare const cidStorage: any[];
export declare const cidStore: any[];
export declare const cidStream: any[];
export declare const cidStrikethrough: any[];
export declare const cidSubtitles: any[];
export declare const cidSubway: any[];
export declare const cidSun: any[];
export declare const cidSwapHorizontalCircle: any[];
export declare const cidSwapHorizontal: any[];
export declare const cidSwapVerticalCircle: any[];
export declare const cidSwapVertical: any[];
export declare const cidSwimming: any[];
export declare const cidSyncDisabled: any[];
export declare const cidSyncProblem: any[];
export declare const cidSync: any[];
export declare const cidTablet: any[];
export declare const cidTag: any[];
export declare const cidTags: any[];
export declare const cidTarget: any[];
export declare const cidTask: any[];
export declare const cidTaxi: any[];
export declare const cidTemperatureAlt: any[];
export declare const cidTemperatureHigh: any[];
export declare const cidTemperatureLow: any[];
export declare const cidTemperature: any[];
export declare const cidTennisBall: any[];
export declare const cidTennis: any[];
export declare const cidTerminal: any[];
export declare const cidTerrain: any[];
export declare const cidTextDirectionLtr: any[];
export declare const cidTextDirectionRtl: any[];
export declare const cidTextFormatClear: any[];
export declare const cidTextHeight: any[];
export declare const cidTextRotateVertical: any[];
export declare const cidTextRotationDown: any[];
export declare const cidTextRotationNone: any[];
export declare const cidTextRotationUp: any[];
export declare const cidTextShapes: any[];
export declare const cidTextSize: any[];
export declare const cidTextSquare: any[];
export declare const cidTextStrike: any[];
export declare const cidTextWidth: any[];
export declare const cidText: any[];
export declare const cidThermometerAlt: any[];
export declare const cidThermometer: any[];
export declare const cidThumbDown: any[];
export declare const cidThumbUp: any[];
export declare const cidTimeline: any[];
export declare const cidTimer: any[];
export declare const cidToggleOff: any[];
export declare const cidToggleOn: any[];
export declare const cidToilet: any[];
export declare const cidToll: any[];
export declare const cidTouchApp: any[];
export declare const cidTrademark: any[];
export declare const cidTraffic: any[];
export declare const cidTrainAlt: any[];
export declare const cidTrain: any[];
export declare const cidTram: any[];
export declare const cidTransferWithinAStation: any[];
export declare const cidTransfer: any[];
export declare const cidTranslate: any[];
export declare const cidTrashAlt: any[];
export declare const cidTrashArrowUp: any[];
export declare const cidTrashSweep: any[];
export declare const cidTrashX: any[];
export declare const cidTrash: any[];
export declare const cidTruck: any[];
export declare const cidTty: any[];
export declare const cidTvDvr: any[];
export declare const cidTvLive: any[];
export declare const cidTvSlash: any[];
export declare const cidTv: any[];
export declare const cidUnderline: any[];
export declare const cidUniversalAccess: any[];
export declare const cidUpdate: any[];
export declare const cidUsb: any[];
export declare const cidUserFemaleFollow: any[];
export declare const cidUserFemaleMinus: any[];
export declare const cidUserFemalePlus: any[];
export declare const cidUserFemaleUnfollow: any[];
export declare const cidUserFemaleX: any[];
export declare const cidUserFemale: any[];
export declare const cidUserFollow: any[];
export declare const cidUserMinus: any[];
export declare const cidUserPlus: any[];
export declare const cidUserSecret: any[];
export declare const cidUserUnfollow: any[];
export declare const cidUser: any[];
export declare const cidVector: any[];
export declare const cidVericalSplit: any[];
export declare const cidVerticalAlignBottom: any[];
export declare const cidVerticalAlignCenter: any[];
export declare const cidVerticalAlignTop: any[];
export declare const cidVideoLabel: any[];
export declare const cidVideoLibrary: any[];
export declare const cidVideoMissed: any[];
export declare const cidVideoPlus: any[];
export declare const cidVideoSlash: any[];
export declare const cidVideoSwitch: any[];
export declare const cidVideo: any[];
export declare const cidVideogame: any[];
export declare const cidViewAgenda: any[];
export declare const cidViewArray: any[];
export declare const cidViewCarousel: any[];
export declare const cidViewColumn: any[];
export declare const cidViewList: any[];
export declare const cidViewModule: any[];
export declare const cidViewQuilt: any[];
export declare const cidViewRow: any[];
export declare const cidViewStream: any[];
export declare const cidVoiceOverRecord: any[];
export declare const cidVoiceOverSlash: any[];
export declare const cidVoice: any[];
export declare const cidVoicemail: any[];
export declare const cidVolumeHigh: any[];
export declare const cidVolumeLow: any[];
export declare const cidVolumeOff: any[];
export declare const cidVolume: any[];
export declare const cidVote: any[];
export declare const cidWallet: any[];
export declare const cidWallpaper: any[];
export declare const cidWarning: any[];
export declare const cidWatch: any[];
export declare const cidWaves: any[];
export declare const cidWc: any[];
export declare const cidWebcloud: any[];
export declare const cidWeightlifitng: any[];
export declare const cidWeights: any[];
export declare const cidWheelchair: any[];
export declare const cidWidgets: any[];
export declare const cidWifiLock: any[];
export declare const cidWifiSignal0: any[];
export declare const cidWifiSignal1: any[];
export declare const cidWifiSignal2: any[];
export declare const cidWifiSignal3: any[];
export declare const cidWifiSignal4: any[];
export declare const cidWifiSignalLock0: any[];
export declare const cidWifiSignalLock1: any[];
export declare const cidWifiSignalLock2: any[];
export declare const cidWifiSignalLock3: any[];
export declare const cidWifiSignalLock4: any[];
export declare const cidWifiSignalOff: any[];
export declare const cidWifi: any[];
export declare const cidWindowMaximize: any[];
export declare const cidWindowMinimize: any[];
export declare const cidWindowRestore: any[];
export declare const cidWindow: any[];
export declare const cidWrapText: any[];
export declare const cidXCircle: any[];
export declare const cidXSquare: any[];
export declare const cidYenCircleSlash: any[];
export declare const cidYenCircle: any[];
export declare const cidYenSlash: any[];
export declare const cidYen: any[];
export declare const cidZoomIn: any[];
export declare const cidZoomOut: any[];
export declare const cidZoom: any[];